export interface ArticleCard {
  icon: string
  title: string
  desc: string
  href: string
  tag: string
  tagColor: string
}

export interface Category {
  label: string
  color: string
  headingColor: string
  articles: ArticleCard[]
}

export const CATEGORIES: Category[] = [
  {
    label: 'Understanding Your Policy',
    color: 'bg-amber-50 border-amber-200',
    headingColor: 'text-amber-900',
    articles: [
      {
        icon: '📋',
        title: 'Policy Interpretation Guide',
        desc: 'Coverages A, B, C, D explained. HO3 vs named peril, commercial vs residential, co-insurance, endorsements, and how to read your entire policy.',
        href: '/resources/policy-interpretation',
        tag: 'Start Here',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📄',
        title: 'How to Read Your Declarations Page',
        desc: 'Your dec page walkthrough: coverages, limits, deductibles, and hidden coverages like debris removal and extended replacement cost.',
        href: '/resources/declarations-page',
        tag: 'Fundamentals',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '📖',
        title: 'How to Read Your Entire Insurance Policy',
        desc: 'A section-by-section walkthrough of your HO-3 policy booklet — insuring agreement, definitions, coverages, exclusions, conditions, and endorsements.',
        href: '/resources/how-to-read-your-policy',
        tag: 'Start Here',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🔍',
        title: 'Exclusions: What\'s Not Covered',
        desc: 'Earth movement, flood, ordinance & law, mold, wear & tear — how to identify exclusions and when they may not apply.',
        href: '/resources/exclusions',
        tag: 'Policy',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '🛡️',
        title: 'Wear and Tear: The Most Misused Exclusion',
        desc: 'Your policy excludes wear and tear as a CAUSE of loss — not damage to property that happens to be worn. If wind blew the shingles off, the cause is wind.',
        href: '/resources/wear-and-tear-cause-of-loss',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '💲',
        title: 'ACV vs. RCV: Actual vs. Replacement Cost',
        desc: 'The most important distinction in a contents claim. How depreciation is calculated and how to get full replacement cost.',
        href: '/resources/acv-rcv',
        tag: 'Contents',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '🏗️',
        title: 'Building Code & Ordinance or Law Coverage',
        desc: 'Code upgrade coverage, historical requirements, zoning, and how O&L can add 25–50% to your claim.',
        href: '/resources/ordinance-law',
        tag: 'Policy',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '🔧',
        title: 'Code Upgrades: Electrical, Structural, Title 24 & More',
        desc: 'California-specific code upgrade requirements — electrical, structural, Title 24 energy, plumbing, roofing, zoning, and how to maximize L&O recovery.',
        href: '/resources/code-upgrade-coverage',
        tag: 'Deep Dive',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📑',
        title: 'Loss Settlement Provisions',
        desc: 'How your payout is actually calculated — ACV, RCV, holdback, rebuilding requirements, and what "like kind and quality" means.',
        href: '/resources/loss-settlement-provisions',
        tag: 'Policy',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '🏠',
        title: 'Replacement Cost vs. 100% Replacement Cost (Guaranteed, Extended, Unlimited)',
        desc: 'Standard RC, extended RC, and guaranteed RC are not the same. Learn the difference and why it matters most after a disaster.',
        href: '/resources/replacement-cost-vs-guaranteed',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📊',
        title: 'Coinsurance Penalties',
        desc: 'What coinsurance is, how the penalty works, and how being underinsured can cost you more than you think.',
        href: '/resources/coinsurance-penalty',
        tag: 'Policy',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '🤝',
        title: 'Agreed Value vs. Stated Value vs. Replacement Cost',
        desc: 'Three valuation methods that are not the same. The difference determines whether your claim gets paid in full or reduced.',
        href: '/resources/agreed-value-policies',
        tag: 'Policy',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '🏢',
        title: 'Vacancy and Unoccupancy Clauses',
        desc: 'An empty home can lose coverage. The difference between vacant and unoccupied — and why a mattress might save your claim.',
        href: '/resources/vacancy-unoccupancy',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '💎',
        title: 'Pair and Set Clauses',
        desc: 'When only part of a matched pair or set is destroyed, insurers try to pay for only the damaged item. Building components and personal property.',
        href: '/resources/pair-and-set',
        tag: 'Policy',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '🏘️',
        title: 'Condo and HOA Insurance Claims',
        desc: 'Two policies cover your condo. CC&Rs control the split. The tenant improvement trap, and what to do when the HOA refuses to act.',
        href: '/resources/condo-hoa-claims',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏢',
        title: 'Loss Assessment Coverage for Condo & HOA Owners',
        desc: 'When the HOA master policy falls short, the shortfall is assessed to you. Your HO-6 includes loss assessment coverage — but $1,000 is dangerously inadequate.',
        href: '/resources/loss-assessment-coverage',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏚️',
        title: 'Landlord vs. Tenant Insurance Claims',
        desc: 'DP-3 vs. HO-4 — who files which claim, the coverage gap that leaves real damage unpaid, subrogation between landlord and tenant, and lease provisions that matter.',
        href: '/resources/landlord-vs-tenant-claims',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏗️',
        title: 'Builder\'s Risk Insurance',
        desc: 'Coverage for buildings under construction, renovation, or remodeling — what\'s covered, what\'s excluded, soft costs, and the critical transition to permanent coverage.',
        href: '/resources/builders-risk',
        tag: 'Specialty',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '🚢',
        title: 'Inland Marine Insurance (Not What You Think)',
        desc: 'Despite the name, inland marine has nothing to do with water. It covers cell towers, bridges, contractor equipment, fine art floaters, and specialized property.',
        href: '/resources/inland-marine',
        tag: 'Specialty',
        tagColor: 'bg-amber-100 text-amber-700',
      },
      {
        icon: '🔥',
        title: 'DIC Policies: Making the FAIR Plan Work',
        desc: 'A DIC policy fills the gaps the FAIR Plan leaves. Without the underlying FAIR Plan, you likely have no fire coverage. These two policies are a pair.',
        href: '/resources/dic-policies',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🔒',
        title: 'Special Limits of Liability',
        desc: 'Hidden dollar caps on jewelry, firearms, coins, and collectibles. The sub-limits that silently reduce your claim — and how scheduling overcomes them.',
        href: '/resources/special-limits-of-liability',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏠',
        title: 'Insurable Interest & Life Estates',
        desc: 'When a home is in a trust with a retained life estate, the policyholder may only recover a fraction of the property value. Learn how life estates are valued and the estate-planning mistake that creates the gap.',
        href: '/resources/insurable-interest',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
    ],
  },
  {
    label: 'Filing & Managing Your Claim',
    color: 'bg-green-50 border-green-200',
    headingColor: 'text-green-900',
    articles: [
      {
        icon: '🗂',
        title: 'Step-by-Step Claims Guide',
        desc: 'From first notice of loss to final settlement. What happens at each stage, who does what, and how to protect yourself.',
        href: '/resources/claims-process',
        tag: 'Start Here',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📝',
        title: 'Proof of Loss',
        desc: 'What a sworn proof of loss is, when it\'s required, deadlines, and how to complete one correctly.',
        href: '/resources/proof-of-loss',
        tag: 'Process',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '📂',
        title: 'Duties After Loss',
        desc: 'Your obligations after a loss — reporting, exhibiting damages, proof of loss — and how failure to comply can affect your claim.',
        href: '/resources/duties-after-loss',
        tag: 'Process',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '🤝',
        title: 'Dealing with the Insurance Adjuster',
        desc: 'The insurer\'s adjuster works for them, not you. Your rights, what to do before and during the inspection, and common tactics to watch for.',
        href: '/resources/dealing-with-adjuster',
        tag: 'Process',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '🛋',
        title: 'Documenting Personal Property',
        desc: 'How to create a defensible contents inventory. Room-by-room methodology, cleaning vs total loss, pack-out and storage.',
        href: '/resources/contents-claims',
        tag: 'Contents',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '🏨',
        title: 'Additional Living Expenses (ALE) & Fair Rental Value',
        desc: 'What ALE and FRV cover, how to document expenses, what insurers try to limit, and how to fight termination.',
        href: '/resources/ale-frv',
        tag: 'ALE / FRV',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '💻',
        title: 'Electronics & Specialty Items',
        desc: 'TVs, computers, jewelry, art, instruments — how these are valued differently and when you need a specialist.',
        href: '/resources/specialty-items',
        tag: 'Contents',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '📋',
        title: 'Scheduled Property, Floaters & Exotic Items',
        desc: 'How to schedule high-value items by agreed value, what personal articles floaters cover, and insurance for racehorses, collector cars, fine art, and appreciating collectibles.',
        href: '/resources/scheduled-personal-property',
        tag: 'Deep Dive',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🌳',
        title: 'Electronics, Rugs & Landscaping: Special Considerations',
        desc: 'Surge damage, smoke-damaged electronics, Oriental rug valuations, and the tree sub-limit trap — three categories insurers consistently underpay.',
        href: '/resources/personal-property-special-considerations',
        tag: 'Deep Dive',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🚛',
        title: 'Debris Removal Coverage',
        desc: 'More than just the dwelling — debris removal applies to other structures, trees, and personal property. The additional 5% provision.',
        href: '/resources/debris-removal',
        tag: 'Coverage',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '🔧',
        title: 'Emergency Repairs: Your Duty to Protect Property',
        desc: 'Your policy requires you to prevent further damage. What emergency repairs are covered and how to document them.',
        href: '/resources/temporary-emergency-repairs',
        tag: 'Process',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '📋',
        title: 'Filing Supplemental Claims',
        desc: 'How to file a supplement when the insurance company\'s estimate missed damage — hidden damage, code upgrades, and more.',
        href: '/resources/supplemental-claims',
        tag: 'Process',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '🏠',
        title: 'Maximizing Your Loss of Use (ALE) Claim',
        desc: 'Coverage D pays your additional living expenses. Most policyholders leave thousands on the table.',
        href: '/resources/loss-of-use-maximizing',
        tag: 'ALE',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '🗣️',
        title: 'Examination Under Oath (EUO)',
        desc: 'What an EUO is, when insurers request one, your rights during the process, how to prepare, and what happens after.',
        href: '/resources/examination-under-oath',
        tag: 'Process',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '🎙️',
        title: 'Recorded Statements and SIU Investigations',
        desc: 'What to expect when your insurance company requests a recorded statement or launches an SIU review.',
        href: '/resources/recorded-statements-siu',
        tag: 'Process',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '💵',
        title: 'Insurance Checks: What to Do',
        desc: 'Restrictive "full and final" language, mortgage company names, ACV vs. holdback payments — what to watch for before you cash that check.',
        href: '/resources/insurance-checks',
        tag: 'Know This',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏦',
        title: 'Mortgage Company Holds',
        desc: 'Your lender\'s name is on the check. How the hold and release process works, what lenders can and cannot do, and the 2025 interest law.',
        href: '/resources/mortgage-company-holds',
        tag: 'Process',
        tagColor: 'bg-green-100 text-green-700',
      },
      {
        icon: '🛡️',
        title: 'Disaster Preparedness & Pre-Loss Mitigation',
        desc: 'Your policy may reimburse mitigation efforts. NFIP covers sandbagging costs. Create inventories, store documents off-site, and prepare before the loss.',
        href: '/resources/disaster-preparedness',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🚨',
        title: 'Avoiding Post-Disaster Scams',
        desc: 'Contractor fraud, deductible waiver schemes, unlicensed claim negotiators, AOB abuse — protect yourself after a loss.',
        href: '/resources/post-disaster-scams',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📝',
        title: 'Assignment of Benefits & Claims After Home Sale',
        desc: 'Work authorizations, direction of payment, preferred vendors, and how to assign a claim when selling a damaged home.',
        href: '/resources/assignment-of-benefits',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏛️',
        title: 'Building Permits and Insurance Claims',
        desc: 'The insurer owes for permits even before they\'re pulled. How to calculate fees and why permits aren\'t an "incurred" cost.',
        href: '/resources/building-permits-claims',
        tag: 'Process',
        tagColor: 'bg-green-100 text-green-700',
      },
    ],
  },
  {
    label: 'Carrier Tactics & Real Stories',
    color: 'bg-red-50 border-red-200',
    headingColor: 'text-red-900',
    articles: [
      {
        icon: '🎯',
        title: 'Games Insurance Companies Play',
        desc: '15 common insurer tactics on property claims — how to identify them and how to defeat them.',
        href: '/insurer-tactics',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📖',
        title: 'Real Stories from the Claims Trenches',
        desc: '35 true stories from both sides of the insurance desk — lowball offers, delay tactics, depreciation tricks, and more.',
        href: '/stories',
        tag: '35 Stories',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🚫',
        title: 'Never Accept the Insurer\'s First Offer',
        desc: 'Why the initial settlement offer is almost always too low — incomplete scope, low pricing, missing coverages — and how to respond.',
        href: '/resources/first-offer-lowball',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '⏳',
        title: 'Insurance Company Delay Tactics',
        desc: 'How insurance companies use delay to pressure you into accepting less — and what California law says about it.',
        href: '/resources/insurance-delay-tactics',
        tag: 'Tactics',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏢',
        title: 'The Consulting Industry Behind Claim Underpayments',
        desc: 'How McKinsey & Company redesigned insurance claims handling to maximize profits — the documented history, the internal slides, and why it became an industry-wide approach.',
        href: '/resources/carrier-claims-tactics',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🎭',
        title: 'Biased Insurance Experts',
        desc: 'How to identify and challenge the insurer\'s hired engineers, hygienists, and estimators who consistently minimize claims.',
        href: '/resources/biased-insurance-experts',
        tag: 'Tactics',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🔍',
        title: 'Insurer\'s Duty to Investigate',
        desc: 'Your insurer must conduct a thorough, fair investigation. When they don\'t, it\'s bad faith.',
        href: '/resources/duty-to-investigate',
        tag: 'Bad Faith',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏦',
        title: 'Force-Placed Insurance',
        desc: 'What lender-placed insurance is, why it\'s expensive, what it doesn\'t cover, and how to avoid it.',
        href: '/resources/force-placed-insurance',
        tag: 'Coverage Gap',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📁',
        title: 'The CLUE Database',
        desc: 'What the CLUE database is, how insurance companies use your claims history, and what you can do about it.',
        href: '/resources/clue-database',
        tag: 'Know This',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🎨',
        title: 'Cosmetic Damage Denials',
        desc: 'Insurers increasingly deny "cosmetic" damage. Why this argument fails and how to fight back.',
        href: '/resources/cosmetic-damage-denials',
        tag: 'Disputes',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '⚔️',
        title: 'Pre-Existing vs. Storm Damage',
        desc: 'Fighting the "wear and tear" denial — directional patterns, timeline evidence, and California\'s efficient proximate cause doctrine.',
        href: '/resources/pre-existing-vs-storm-damage',
        tag: 'Disputes',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '💰',
        title: 'Insurance Reserves and Adjuster Authority',
        desc: 'How reserves work, why your adjuster changed mid-claim, authority levels, the three-adjuster problem, and settling just under the limit.',
        href: '/resources/reserves-and-authority',
        tag: 'Insider',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📱',
        title: 'Social Media and Insurance Claims',
        desc: 'How insurers monitor social media, satellite imagery, and digital evidence during property claims — and what you should and shouldn\'t post.',
        href: '/resources/social-media-claims',
        tag: 'Tactics',
        tagColor: 'bg-red-100 text-red-700',
      },
    ],
  },
  {
    label: 'Disputes & Fighting Back',
    color: 'bg-orange-50 border-orange-200',
    headingColor: 'text-orange-900',
    articles: [
      {
        icon: '♟',
        title: 'Claim Negotiation Tactics',
        desc: 'The chess game with your adjuster. Responding to lowball offers, reservation of rights letters, and delay tactics.',
        href: '/resources/negotiation',
        tag: 'Strategy',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '🎯',
        title: 'Multiple Reasons to Replace',
        desc: 'Don\'t get stuck arguing one reason when you have seven. If only one of seven reasons is valid, the item may still need to go.',
        href: '/resources/multiple-reasons-to-replace',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '✉️',
        title: 'How to Write an Effective Claim Letter',
        desc: 'Your written communications become the record of your claim. Templates, structure, and what to include.',
        href: '/resources/claim-negotiation-letters',
        tag: 'Strategy',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '📐',
        title: 'Xactimate Estimates: What You Need to Know',
        desc: 'How to read a scope of loss, identify missing line items, understand labor and material rates, and dispute underpayment.',
        href: '/resources/xactimate',
        tag: 'Estimates',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '🔎',
        title: 'Commonly Missed Items on Total Loss Claims',
        desc: 'Light bulbs, low-voltage wiring, house numbers, thresholds, scribe moldings, pressure-treated sole plates — a checklist of items adjusters routinely miss.',
        href: '/resources/commonly-missed-items',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🪞',
        title: 'Matching: Achieving Uniform Appearance',
        desc: 'When partial repairs don\'t match — your right to a uniform appearance under the Model Fair Claims Act.',
        href: '/resources/matching',
        tag: 'Disputes',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '📏',
        title: 'Scope of Loss Disputes',
        desc: 'When the insurer misses damage — how to document, dispute, and recover the full cost of repairs.',
        href: '/resources/scope-of-loss',
        tag: 'Disputes',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '❓',
        title: 'Coverage Disputes',
        desc: 'The most fundamental question: is your loss covered at all? How to fight a denial and establish coverage.',
        href: '/resources/coverage-disputes',
        tag: 'Disputes',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '🔨',
        title: 'Insurance Appraisal in California',
        desc: 'The standard fire policy, the arbitration code, key case law, and how to protect your rights in appraisal.',
        href: '/resources/appraisal',
        tag: 'California',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '🤝',
        title: 'Insurance Mediation',
        desc: 'How mediation works, when it resolves disputes faster and cheaper than litigation, and how to prepare.',
        href: '/resources/insurance-mediation',
        tag: 'Dispute Resolution',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '💰',
        title: 'Overhead & Profit',
        desc: 'Insurance companies routinely refuse to include overhead and profit. Learn what O&P is and when you\'re entitled to it.',
        href: '/resources/overhead-and-profit',
        tag: 'Estimates',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '📊',
        title: 'Soft Costs: The Hidden Expenses Carriers Strip',
        desc: 'Engineering fees, permits, supervision, interior design, environmental testing — the 15-25% of real construction costs carriers routinely remove from estimates.',
        href: '/resources/soft-costs-claims',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '👷',
        title: 'Labor Depreciation',
        desc: 'A growing number of states have ruled that insurance companies cannot depreciate labor costs. California is one of them.',
        href: '/resources/labor-depreciation',
        tag: 'Depreciation',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '📉',
        title: 'Excessive Depreciation: How to Fight Back',
        desc: 'No depreciation on labor, long-life components, or undamaged matching areas. The rules insurers break and how to challenge every one.',
        href: '/resources/excessive-depreciation',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🔧',
        title: 'Right to Repair Clauses',
        desc: 'Insurance companies increasingly use right to repair clauses to control repairs. Know your rights.',
        href: '/resources/right-to-repair',
        tag: 'Policy',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '🔬',
        title: 'Defeating Carrier Engineer Reports',
        desc: 'How carrier engineers operate, common report flaws, and a step-by-step rebuttal process to overturn engineer-based denials.',
        href: '/resources/defeating-carrier-engineers',
        tag: 'Roof Claims',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '📐',
        title: 'When Engineering Reports Cross the Line',
        desc: 'Engineers determine how things failed — not whether damage is covered. The difference between engineering causation and legal causation under California law.',
        href: '/resources/engineering-reports-vs-coverage',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🛡️',
        title: 'Know Your Rights as a Policyholder',
        desc: 'Your insurance company has obligations under the policy, state law, and regulations. Here\'s what they owe you.',
        href: '/resources/policyholder-rights',
        tag: 'Your Rights',
        tagColor: 'bg-orange-100 text-orange-700',
      },
    ],
  },
  {
    label: 'Types of Damage',
    color: 'bg-teal-50 border-teal-200',
    headingColor: 'text-teal-900',
    articles: [
      {
        icon: '🔥',
        title: 'Common Types of Claims',
        desc: 'Fire, water, vandalism, vehicle impact, sewage, flood, smoke — how each type of claim has unique considerations.',
        href: '/types-of-claims',
        tag: 'Overview',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🌲',
        title: 'Wildfire Claims Guide',
        desc: 'Forest fire vs urban wildfire smoke, contamination testing, coverage, and step-by-step wildfire claims guidance.',
        href: '/resources/wildfire-guide',
        tag: 'Wildfire',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '💨',
        title: 'Smoke Damage Claims',
        desc: 'Testing, remediation standards, the Smoke Damage Recovery Act, and why a visual walk-through is not enough.',
        href: '/resources/smoke-damage-claims',
        tag: 'Wildfire',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '💧',
        title: 'Water Damage Claims',
        desc: 'From emergency response to final settlement — burst pipes, leaks, mitigation, and fighting for full payment.',
        href: '/resources/water-damage-claims',
        tag: 'Water',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🚰',
        title: 'Accidental Discharge or Overflow',
        desc: 'The ISO HO-3 peril that covers burst pipes, failed appliances, and overflows. The 14-day endorsement trap, tear-out coverage, and carrier denial tactics.',
        href: '/resources/accidental-discharge-overflow',
        tag: 'Water',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🚿',
        title: 'Blockage & Overflow vs. Sewer Backup',
        desc: 'A plumbing blockage is not a backup. Learn the mechanical difference, why using the wrong word can cost you coverage, and what the courts say.',
        href: '/resources/blockage-vs-backup',
        tag: 'Water',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '❌',
        title: 'Fire Claim Denied? Here\'s What to Do',
        desc: 'Common denial reasons, your appeal rights, steps to fight back, and when a denial becomes bad faith.',
        href: '/resources/fire-claim-denied',
        tag: 'Denied Claims',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏠',
        title: 'Roof Damage Insurance Claims',
        desc: 'The most common homeowner claim — causes, coverage, matching disputes, repair vs. replacement, and getting full payment.',
        href: '/resources/roof-damage',
        tag: 'Roof Claims',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🧊',
        title: 'Hail Damage Claims',
        desc: 'Documenting hail damage, fighting for matching, and getting full replacement when your roof needs it.',
        href: '/resources/hail-damage-claims',
        tag: 'Hail',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🔬',
        title: 'The Science of Hail Damage',
        desc: 'Test square methodology, impact patterns, collateral evidence, and how to counter carrier engineer mischaracterizations.',
        href: '/resources/hail-damage-science',
        tag: 'Hail',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🌬️',
        title: 'Wind Damage Claims',
        desc: 'How wind damage claims work and disputes over wind vs. wear-and-tear damage.',
        href: '/resources/wind-damage-claims',
        tag: 'Wind',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🦠',
        title: 'Mold Losses',
        desc: 'Is mold covered? Ensuing loss doctrine, mold limits, and why the insurance company\'s mold argument may be wrong.',
        href: '/resources/mold-losses',
        tag: 'Mold',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🧫',
        title: 'The Mold Coverage Paradox',
        desc: 'Covered, excluded, and everything in between. Cause-vs-result, proper cost allocation, and why the difference is $14,000 on a single claim.',
        href: '/resources/mold-coverage-paradox',
        tag: 'Deep Dive',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🔨',
        title: 'Vandalism Claims',
        desc: 'How to prove vandalism and push back when insurers relabel your claim as wear and tear.',
        href: '/resources/vandalism-claims',
        tag: 'Vandalism',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🏚️',
        title: 'Total Loss Claims',
        desc: 'When your home is a complete loss — every coverage that activates, rebuilding vs. cashing out, and California protections.',
        href: '/resources/total-loss',
        tag: 'Total Loss',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📉',
        title: 'Underinsured After a Wildfire',
        desc: 'Why so many homeowners are underinsured, and strategies to maximize recovery when policy limits fall short.',
        href: '/resources/underinsured-after-wildfire',
        tag: 'Wildfire',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🌡️',
        title: 'Thermal & Heat Damage from Nearby Wildfires',
        desc: 'Your home survived — but radiant heat can warp siding, compromise windows, damage wiring, and degrade roofing without any flame contact.',
        href: '/resources/thermal-heat-damage',
        tag: 'Wildfire',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '⚡',
        title: 'Lightning Damage Claims',
        desc: 'Hidden wiring damage, failed breakers, destroyed low-voltage systems, and why insurers reclassify lightning as a power surge.',
        href: '/resources/lightning-damage',
        tag: 'Lightning',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🔧',
        title: 'Slab Leak Claims: Hidden Damage and the Underground Pipe Myth',
        desc: 'Surface drying hides the real damage. Fill dirt pipes aren\'t underground. Coverage pays for access, not the pipe. Leak detection, copper defects, and what carriers miss.',
        href: '/resources/slab-leak-claims',
        tag: 'Slab Leaks',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏗️',
        title: 'Foundation Damage Claims',
        desc: 'When a water leak causes settlement, the earth movement exclusion may not apply. Heaving vs. settlement, repair methods, and California case law.',
        href: '/resources/foundation-damage',
        tag: 'Foundation',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🏚️',
        title: 'Collapse Coverage',
        desc: 'Collapse is excluded then added back as an Additional Coverage with strict qualifying causes. The definition of collapse is the central battleground.',
        href: '/resources/collapse-coverage',
        tag: 'Deep Dive',
        tagColor: 'bg-purple-100 text-purple-700',
      },
      {
        icon: '🌊',
        title: 'Flood Insurance: NFIP vs. Private Flood',
        desc: 'Private flood carriers use the NFIP form but adjust under state law. More protections, bad faith remedies, and flexible proof of loss.',
        href: '/resources/flood-insurance-nfip-vs-private',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🌎',
        title: 'Earthquake Insurance: CEA and Private Carriers',
        desc: 'You can buy earthquake insurance from private carriers, not just the CEA. Deductible structures, coverage gaps, and claims handling differences.',
        href: '/resources/earthquake-insurance',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏔️',
        title: 'Earth Movement & Landslide',
        desc: 'Generally excluded — but NOT when caused by wildfire, vehicle impact, or water discharge. California\'s efficient proximate cause doctrine changes everything.',
        href: '/resources/earth-movement-landslide',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🔑',
        title: 'Theft & Burglary Claims',
        desc: 'Coverage across A, B, and C. Sublimits on jewelry and cash, the mysterious disappearance exclusion, vacancy rules, and SIU investigations.',
        href: '/resources/theft-burglary-claims',
        tag: 'Theft',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🌳',
        title: 'Tree & Falling Object Damage',
        desc: 'Your own policy pays when a neighbor\'s tree falls on your house. Tree removal limits, debris removal, hidden structural damage, and the dead tree argument.',
        href: '/resources/tree-falling-object-damage',
        tag: 'Trees',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🪟',
        title: 'Glass Breakage Claims',
        desc: 'Vandalism glass exclusions, gunshot as explosion, acrylic isn\'t glass, tempered glass code upgrades, thermal stress cracks, and specialty glass replacement.',
        href: '/resources/glass-breakage-claims',
        tag: 'Glass',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🦝',
        title: 'Animal & Pest Damage',
        desc: 'The rodent exclusion doesn\'t cover raccoons. Raccoon roundworm requires professional hygienist cleanup. Resulting damage from animals may still be covered.',
        href: '/resources/animal-pest-damage',
        tag: 'Animals',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🏗️',
        title: 'Stucco & EIFS Claims',
        desc: 'Traditional stucco vs. synthetic EIFS — water intrusion, cracking, construction defect vs. covered peril, moisture testing, and repair vs. replacement.',
        href: '/resources/stucco-eifs-claims',
        tag: 'Stucco',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🌾',
        title: 'Crop & Agricultural Insurance',
        desc: 'California is the #1 agricultural state. Crop losses can exceed $1M. MPCI, revenue protection, smoke taint on wine grapes, livestock mortality, and nursery stock.',
        href: '/resources/crop-agricultural-insurance',
        tag: 'Specialty',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🏊',
        title: 'Swimming Pool Damage Claims',
        desc: 'Coverage B limits, scheduled endorsements, coverage stacking, pool pop-outs, wildfire ash chemistry, freeze damage, and equipment breakdown.',
        href: '/resources/swimming-pool-damage',
        tag: 'Deep Dive',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏗️',
        title: 'Roofing Systems: A Technical Deep Dive',
        desc: 'TPO, EPDM, metal, asphalt, wood shake — material-specific claim issues, Title 24 cool roofs, multiple layers, space decking, and solar panels.',
        href: '/resources/roofing-systems-claims',
        tag: 'Deep Dive',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏢',
        title: 'Large & Complex Commercial Property Losses',
        desc: 'How large commercial claims differ from residential — carrier teams, multiple coverage parts, business income, soft costs, ordinance or law, and why you need a PA.',
        href: '/resources/large-commercial-losses',
        tag: 'Commercial',
        tagColor: 'bg-red-100 text-red-700',
      },
    ],
  },
  {
    label: 'Getting Professional Help',
    color: 'bg-purple-50 border-purple-200',
    headingColor: 'text-purple-900',
    articles: [
      {
        icon: '🧑‍💼',
        title: 'Working With a Public Adjuster',
        desc: 'What a PA does, how fees work, when to hire one, and how the process works alongside your insurer.',
        href: '/resources/public-adjuster',
        tag: 'Professional Help',
        tagColor: 'bg-purple-100 text-purple-700',
      },
      {
        icon: '💰',
        title: 'Public Adjuster Fees',
        desc: 'What PAs cost, how contingency fees work, California\'s disaster fee cap, and questions to ask before signing.',
        href: '/resources/public-adjuster-fees',
        tag: 'Fees & Costs',
        tagColor: 'bg-purple-100 text-purple-700',
      },
      {
        icon: '👔',
        title: 'Types of Insurance Adjusters',
        desc: 'Staff adjusters, independent adjusters, desk adjusters, public adjusters — learn who each one works for.',
        href: '/resources/adjuster-types',
        tag: 'Know This',
        tagColor: 'bg-purple-100 text-purple-700',
      },
      {
        icon: '🏗️',
        title: 'Choosing Your Own Contractor',
        desc: 'You have the right to choose your own contractor. How to evaluate one and why the carrier\'s preferred vendor may not be best.',
        href: '/resources/choosing-your-contractor',
        tag: 'Contractors',
        tagColor: 'bg-purple-100 text-purple-700',
      },
      {
        icon: '⚖️',
        title: 'When to Hire an Attorney',
        desc: 'Not every claim needs a lawyer — but some absolutely do. How to know when it\'s time.',
        href: '/resources/when-to-hire-attorney',
        tag: 'Legal',
        tagColor: 'bg-purple-100 text-purple-700',
      },
      {
        icon: '🏦',
        title: 'When a Mortgage Company Tries to Hire a PA',
        desc: 'Mortgagee rights, the loss payable endorsement, privacy laws, and why a lender cannot hire a public adjuster unless it is an insured.',
        href: '/resources/mortgage-company-public-adjuster',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
    ],
  },
  {
    label: 'California Law & Regulations',
    color: 'bg-blue-50 border-blue-200',
    headingColor: 'text-blue-900',
    articles: [
      {
        icon: '⚖️',
        title: 'Fair Claims Settlement Practices Act (10 CCR 2695)',
        desc: 'The California regulation that governs every step of your claim. Deadlines, required disclosures, and prohibited practices.',
        href: '/resources/california-fair-claims',
        tag: 'Essential Reading',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🚨',
        title: 'Bad Faith Insurance Practices',
        desc: 'What constitutes bad faith in California, your remedies, and how to document violations for leverage or litigation.',
        href: '/resources/bad-faith',
        tag: 'California',
        tagColor: 'bg-blue-100 text-blue-700',
      },
      {
        icon: '📜',
        title: 'Insurance Code 790.03 and the 790 Letter',
        desc: 'What the statute prohibits, how to write a 790 letter putting your insurer on formal notice, and why it changes the dynamic of your claim.',
        href: '/resources/insurance-code-790',
        tag: 'California',
        tagColor: 'bg-blue-100 text-blue-700',
      },
      {
        icon: '✍️',
        title: 'The White Waiver: California\'s Settlement-Privilege Waiver',
        desc: 'What the White waiver is, why insurers ask you to sign one, and why signing too quickly can give up your most powerful bad-faith evidence.',
        href: '/resources/white-waiver',
        tag: 'California',
        tagColor: 'bg-blue-100 text-blue-700',
      },
      {
        icon: '📁',
        title: 'Filing a CDI Complaint',
        desc: 'How to file a complaint with the California Department of Insurance — when to do it and how to write one that gets results.',
        href: '/resources/cdi-complaint',
        tag: 'California',
        tagColor: 'bg-blue-100 text-blue-700',
      },
      {
        icon: '⏱️',
        title: 'Equitable Tolling of the Statute of Limitations',
        desc: 'The one-year suit limitation is not as simple as it appears. How equitable tolling pauses the clock.',
        href: '/resources/equitable-tolling',
        tag: 'California',
        tagColor: 'bg-blue-100 text-blue-700',
      },
      {
        icon: '⏳',
        title: 'Equitable Tolling Edge Cases',
        desc: 'The hard part — closed files without notice, partial closures, reopened claims, clock calculations, filing without serving, and the one-year vs. two-year trap.',
        href: '/resources/equitable-tolling-nuances',
        tag: 'Deep Dive',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🏚️',
        title: 'California\'s Insurance Crisis',
        desc: 'Why insurers are cancelling policies, leaving the market, and raising rates — and what homeowners can do.',
        href: '/resources/california-insurance-crisis',
        tag: 'California',
        tagColor: 'bg-blue-100 text-blue-700',
      },
      {
        icon: '🏛️',
        title: 'The California FAIR Plan',
        desc: 'Last-resort fire coverage: what it covers, what it doesn\'t, how to apply, and the DIC policy you need alongside it.',
        href: '/resources/california-fair-plan',
        tag: 'California',
        tagColor: 'bg-blue-100 text-blue-700',
      },
      {
        icon: '🚫',
        title: 'Is Your Policy Illegal? When Policy Language Conflicts with Law',
        desc: 'A court ruled the FAIR Plan\'s fire policy "unlawful." Here are 10 ways your policy may conflict with California statutes, case law, and regulations.',
        href: '/resources/policy-vs-law',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📜',
        title: 'SB 495: New Contents Payment Rule',
        desc: 'How SB 495 changes personal property claims in disasters — automatic 60% contents payments, no inventory for 100 days.',
        href: '/resources/sb49-contents-rule',
        tag: 'New Law',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '⚡',
        title: 'Inverse Condemnation: Suing Utilities',
        desc: 'When a utility causes a wildfire, you may have a strict-liability claim beyond insurance.',
        href: '/resources/inverse-condemnation',
        tag: 'California',
        tagColor: 'bg-blue-100 text-blue-700',
      },
      {
        icon: '📅',
        title: 'California Claim Deadlines & Timeframes',
        desc: 'Every deadline your California insurance company must meet — and what happens when they miss them.',
        href: '/resources/california-claim-deadlines',
        tag: 'Deadlines',
        tagColor: 'bg-blue-100 text-blue-700',
      },
      {
        icon: '🔗',
        title: 'Anti-Concurrent Causation Clauses',
        desc: 'ACC clauses let insurers deny claims when any excluded peril contributes. In California, these clauses are unenforceable.',
        href: '/resources/anti-concurrent-causation',
        tag: 'Must Read',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '🔄',
        title: 'Subrogation: Your Right to Recover',
        desc: 'How subrogation works, the regulation requiring your insurer to notify you, deductible recovery, and the made-whole doctrine.',
        href: '/resources/subrogation',
        tag: 'California',
        tagColor: 'bg-blue-100 text-blue-700',
      },
    ],
  },
  {
    label: 'Research & Academic Studies',
    color: 'bg-indigo-50 border-indigo-200',
    headingColor: 'text-indigo-900',
    articles: [
      {
        icon: '🧊',
        title: 'What Hailstone Research Tells Us About Insurance Claims',
        desc: 'IBHS measured 2,500+ hailstones and found they are not perfect spheres, maximum sizes are twice the average, and lab tests overstate impact force.',
        href: '/resources/hailstone-damage-research',
        tag: 'Hail Science',
        tagColor: 'bg-indigo-100 text-indigo-700',
      },
      {
        icon: '🧊',
        title: 'Sub-Severe Hail: Why Small Hailstones Cause Big Problems',
        desc: 'IBHS research proves shingles hit by small hail become ten times more vulnerable to future storms.',
        href: '/resources/sub-severe-hail-cumulative-damage',
        tag: 'Hail Science',
        tagColor: 'bg-indigo-100 text-indigo-700',
      },
      {
        icon: '🧊',
        title: 'Hail Damage Thresholds: What Size Hail Actually Damages Your Roof',
        desc: 'Haag Engineering research establishes the minimum hail sizes needed to damage common roofing materials.',
        href: '/resources/hail-damage-threshold-sizes',
        tag: 'Hail Science',
        tagColor: 'bg-indigo-100 text-indigo-700',
      },
      {
        icon: '🧊',
        title: 'RICOWI Field Investigations: What Hail Actually Does to Roofs',
        desc: 'Expert teams document real hail damage after major storms. Their findings often contradict carrier assessments.',
        href: '/resources/ricowi-hail-field-investigations',
        tag: 'Hail Science',
        tagColor: 'bg-indigo-100 text-indigo-700',
      },
      {
        icon: '🔥',
        title: 'NIST Camp Fire Investigation: What Government Scientists Found',
        desc: 'NIST investigation of the 2018 Camp Fire reveals how wildfire damages buildings and why insurers underestimate repair costs.',
        href: '/resources/nist-camp-fire-investigation',
        tag: 'Wildfire Research',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '🔥',
        title: 'NIST Witch Fire Study: House-by-House Wildfire Damage Analysis',
        desc: 'NIST documented 274 homes after the 2007 Witch Fire, proving wildfire damage depends on exposure conditions.',
        href: '/resources/nist-witch-fire-case-study',
        tag: 'Wildfire Research',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '🔥',
        title: 'The WUI Hazard Scale: How Scientists Measure Wildfire Risk to Buildings',
        desc: 'NIST, CAL FIRE, and IBHS developed a science-based framework for measuring wildfire exposure to structures.',
        href: '/resources/nist-wui-hazard-methodology',
        tag: 'Wildfire Research',
        tagColor: 'bg-orange-100 text-orange-700',
      },
      {
        icon: '🔬',
        title: 'EPA Mold Remediation Guide: The Standard Your Insurer Should Follow',
        desc: 'The EPA official guide establishes the 24-48 hour mold growth timeline and remediation protocols.',
        href: '/resources/epa-mold-remediation-guide',
        tag: 'Mold & Water',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '🔬',
        title: 'Mold Growth Science: How Fast Does Mold Really Develop?',
        desc: 'Mathematical models from VTT and Oak Ridge National Laboratory prove mold develops faster than insurers claim.',
        href: '/resources/mold-growth-prediction-research',
        tag: 'Mold & Water',
        tagColor: 'bg-teal-100 text-teal-700',
      },
      {
        icon: '📋',
        title: 'Government Report: 80% of Sandy Flood Appeals Got More Money',
        desc: 'DHS found nearly 80% of NFIP Sandy claims appeals resulted in additional payments — proving systematic underpayment.',
        href: '/resources/nfip-sandy-claims-underpayment',
        tag: 'Government Reports',
        tagColor: 'bg-red-100 text-red-700',
      },
      {
        icon: '📋',
        title: 'Government Report: FEMA Fails to Oversee Flood Insurance Companies',
        desc: 'The DHS Inspector General found FEMA does not adequately oversee companies handling flood insurance claims.',
        href: '/resources/fema-nfip-oversight-failures',
        tag: 'Government Reports',
        tagColor: 'bg-red-100 text-red-700',
      },
    ],
  },
]

export function slugForCategory(label: string): string {
  return label.toLowerCase().replace(/[^a-z0-9]+/g, '-')
}
