import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: 'The Three Lives of an Xactimate Document: Estimate, Bid, and Invoice',
  description:
    "An Xactimate document can be an estimate, a bid, or an invoice — and the distinction is not semantic. Learn why the carrier's preferred vendor estimate is not a competing bid, and how to challenge underpayments based on uncommitted numbers.",
}

export default function Content() {
  return (
    <>
      <p className="text-gray-700 leading-relaxed mb-4">
        A contractor walks through your fire-damaged home, opens Xactimate on a tablet, photographs every room, measures every wall, and produces a forty-page document listing every line item needed to restore your property. The total is $287,000. You sign a contract with that contractor to perform the work at that price. You submit the document to your insurance company.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Two weeks later, the carrier sends its own contractor &mdash; a &quot;preferred vendor&quot; who has never met you and has no interest in performing the work &mdash; to walk through the same house. That contractor also opens Xactimate, also photographs and measures, and produces a separate forty-page document. The total is $194,000. The carrier tells you it will pay $194,000 because that is what the work &quot;should cost.&quot;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        On the surface, you are looking at two Xactimate documents. They use the same software, the same line-item database, the same general formatting. A reasonable person might assume they represent two competing prices for the same job. The carrier certainly wants you to think so. But these two documents are fundamentally different things. One is a bid. The other is an estimate. The distinction is not semantic &mdash; it is the difference between a price someone will actually honor and a number generated by someone who has no intention of doing the work. And that distinction has legal, practical, and financial consequences that most policyholders &mdash; and many adjusters &mdash; never consider.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Understanding What Xactimate Actually Is</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate is property claims estimating software developed by Xactware Solutions, a subsidiary of Verisk Analytics. It is the dominant estimating platform in the property insurance industry. Carriers, independent adjusters, public adjusters, and contractors all use it. The software contains a database of line items &mdash; thousands of individual tasks such as &quot;remove and replace drywall, 1/2 inch, hung, taped, floated, ready for paint&quot; &mdash; each associated with a price drawn from Verisk&apos;s proprietary pricing database.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The pricing database is updated monthly and organized by geographic region. Verisk describes its methodology as based on &quot;primary sources including labor, equipment, or material providers; contractors and subcontractors; and Xactimate customers,&quot; acquired through surveys, direct data feeds, and completed estimates. The company collects more than 345,000 survey points annually and analyzes millions of estimates to generate what it calls a &quot;single representative price per line item, computed from all valid price points researched within the market.&quot;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        That language sounds precise, but it conceals an important limitation. The price Xactimate assigns to any given line item is a statistical composite &mdash; a calculated midpoint. Verisk&apos;s own pricing research methodology document acknowledges that &quot;some market price data are higher, and some market price data are lower than that which are reported.&quot; Verisk has noted that price variations of 50% from low to high within a single market are common, and that variations of 100% are &quot;not uncommon.&quot;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        And Verisk&apos;s End User License Agreement goes further. Section 12.3 of the Xactware EULA states plainly: <strong>&quot;We do not warrant the accuracy of pricing information in the Price Data.&quot;</strong> Users are expected to &quot;agree not to prohibit or preclude deviations from the Price Data where contractor requirements, market conditions, demand or any other factor warrants the use of different line-item price in the specific situation.&quot;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This is the software&apos;s creator telling its users &mdash; in a binding legal agreement &mdash; that its prices are not guaranteed to be accurate and should be adjusted when real-world conditions warrant it. The EULA effectively characterizes Xactimate pricing as a starting point, not a destination.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        As the <em>Daily Journal</em> observed in a 2024 MCLE article titled &quot;Xactimate Is Not the Law&quot;: nothing in a standard California homeowners policy authorizes an insurer to limit its obligations to whatever figure a third-party software program generates. The policy obligates the carrier to pay what it actually costs to restore the property. Xactimate is a tool for calculating that cost. It is not a substitute for it.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Life One: The Estimate</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        At its most basic, an Xactimate document is an estimate &mdash; a calculation of what work should cost based on the inputs selected by the person who prepared it. An estimate is an opinion. It reflects the estimator&apos;s judgment about what needs to be done (the scope of work) and what it should cost (pricing).
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The word &quot;estimate&quot; carries a specific meaning in contract law. An estimate is not an offer. It does not create contractual obligations. It is not a promise to perform work at the stated price. The Restatement (Second) of Contracts, Section 24, defines an offer as &quot;the manifestation of willingness to enter into a bargain, so made as to justify another person in understanding that his assent to that bargain is invited and will conclude it.&quot; An estimate manifests no such willingness. It communicates information. It does not invite assent.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        When someone produces an Xactimate document, that document is an estimate. Full stop. It may later become something else, depending on context and intent. But at the moment of creation, it is a calculation &mdash; nothing more.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Life Two: The Bid</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        An estimate becomes a bid when it is combined with the intention to win and perform the job. Intent is the dividing line. It is what separates a number on a page from a commitment backed by a contractor&apos;s willingness to actually do the work.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        A retail contractor inspects a damaged property and prepares an Xactimate document. The contractor wants the job. The contractor is willing to perform the work at the price stated. That document is both an estimate (a calculation of cost) and a bid (a commitment to perform). A bid carries an implicit promise. The contractor who submits a bid has evaluated the project, assessed the scope, calculated the costs, accounted for overhead and profit, and is willing to commit company resources at that price. That promise has economic value backed by the contractor&apos;s reputation, license, bond, and insurance.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Under the UCC and common law, a bid from a contractor functioning as a merchant represents something substantively different from a mere price quotation. UCC Section 2-205 provides that a merchant&apos;s signed, written offer is irrevocable for up to three months even without consideration &mdash; the &quot;firm offer&quot; rule. The law treats commitments differently from estimates precisely because commitments carry obligations that estimates do not.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">When an Estimate Is Not a Bid</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        An insured homeowner has already signed a contract with a general contractor. The contractor has begun the permitting process, ordered materials, and scheduled subcontractors. The insurance company sends its preferred vendor to the property to &quot;inspect&quot; and &quot;prepare an estimate.&quot;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The preferred vendor knows another contractor has already been engaged. The preferred vendor is not competing for this job. The preferred vendor has no intention of performing the work. The preferred vendor&apos;s sole purpose is to produce an Xactimate document that the carrier can use to justify a lower payment.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The document that preferred vendor produces is an estimate. It is not a bid. It cannot be a bid, because the essential element &mdash; the intent to win and perform the job &mdash; is absent. The preferred vendor has no intention of doing the work. The preferred vendor has not committed company resources. The preferred vendor is not willing to be held to the price stated in the document.
      </p>

      <CalloutBox variant="tip" title="The Key Question">
        <p>
          The next time an adjuster presents a preferred vendor&apos;s Xactimate document and calls it a &quot;competitive estimate,&quot; ask the question that reframes the entire conversation: <strong>Who is competing?</strong>
        </p>
      </CalloutBox>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">The Tortious Interference Problem</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        California law recognizes the tort of intentional interference with contractual relations. Under CACI 2201, the elements are: (1) a valid contract between the plaintiff and a third party; (2) the defendant&apos;s knowledge of this contract; (3) intentional acts designed to induce a breach or disruption; (4) actual breach or disruption; and (5) resulting damage.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        When a homeowner has signed a contract with a general contractor, a preferred vendor who knows about that contract and attempts to persuade the homeowner to terminate it and hire the preferred vendor instead is engaging in conduct that falls squarely within these elements. California courts have held that intentional interference with contractual relations does not require that the defendant&apos;s conduct be independently wrongful. <em>See Quelimane Co. v. Stewart Title Guaranty Co.</em> (1998) 19 Cal.4th 26, 55-56.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        If a preferred vendor cannot ethically or legally try to win the job, the document they produce cannot honestly be characterized as a competing bid. A bid implies competition. Competition implies intent to win. If the vendor has no intent to win &mdash; and would face legal exposure if they tried &mdash; then the document is not a bid, regardless of what it looks like on the page.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Life Three: The Invoice</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        An Xactimate document can also serve as an invoice &mdash; or more precisely, as the supporting documentation for an invoice. This transition occurs when the insured enters into a contract with the contractor and the contractor completes the work. At that point, the Xactimate document that began as an estimate, became a bid, and supported a contract now serves as the basis for the contractor&apos;s request for payment.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        An invoice represents economic reality &mdash; labor was expended, materials were consumed, the property was restored. The price on the invoice is not theoretical. It is what the work cost. Insurance policies are contracts of indemnity. When the insured presents an invoice, the carrier is confronted with evidence of actual cost.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        California&apos;s Fair Claims Settlement Practices Regulations reinforce this obligation. 10 CCR Section 2695.9(b) requires that estimates be &quot;of an amount which will restore the damaged property to no less than its condition prior to the loss.&quot; Section 2695.9(d) requires that &quot;the insurer shall take reasonable steps to verify that the repair or rebuilding costs utilized by the insurer or its claims agents are accurate and representative of costs in the local market area.&quot;
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">The Critical Insight: Apples and Oranges</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        A homeowner&apos;s contractor submits a bid of $287,000 backed by a contract to perform. The carrier&apos;s preferred vendor produces an estimate of $194,000 with no intention of doing the work. The carrier treats these as equivalent and pays the lower number. But one is a bid and the other is an estimate. The difference is commitment.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        A bid is backed by a promise. If the contractor underbids the job, they absorb the loss. If materials cost more than projected, they bear that risk. An estimate backed by no intent to perform carries none of these commitments. The preferred vendor will never have to buy a single sheet of drywall at that price. The estimate is cost-free for the person who produced it. It is, in the most literal sense, a hypothetical.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">The Market Price Problem</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        A competitive bid is a market price indicator &mdash; what a willing contractor will charge in a specific market at a specific time. A preferred vendor&apos;s estimate is not a market price indicator. It is a software output generated by someone not competing for the job. The vendor is not a willing seller. There is no arm&apos;s-length transaction. The resulting number is an internal carrier document dressed up as a market price.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        10 CCR Section 2695.9(d) requires that repair costs be &quot;accurate and representative of costs in the local market area.&quot; A preferred vendor&apos;s estimate, produced by someone with no intent to perform and no exposure to actual costs, may not satisfy this standard &mdash; particularly when the insured has presented a contractor&apos;s bid that reflects actual market conditions.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">What the Insured Can Do</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Demand the carrier identify the nature of its document.</strong> Ask: <strong>Is this a bid?</strong> If the carrier cannot produce a contractor who will actually do the work for the amount stated, the document is not a bid. It is an estimate without a commitment to perform &mdash; not evidence of what the work will cost, but evidence of what a software program calculated.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Document the contractor&apos;s commitment.</strong> The insured&apos;s Xactimate bid should be accompanied by a written contract. This transforms the document from an estimate into a bid and makes it difficult for the carrier to claim the price is merely theoretical.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Invoke the regulatory framework.</strong> Request a written explanation of the basis for the carrier&apos;s lower figure, as required by Insurance Code Section 790.03(h)(13). A response that amounts to &quot;our Xactimate estimate is lower&quot; does not satisfy this requirement.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Preserve the record for appraisal or litigation.</strong> In appraisal or litigation, depose the preferred vendor to establish that they had no intention of performing, were not competing, and would not have been bound by the price. Each of these facts undermines the carrier&apos;s position.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">The Broader Principle</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Insurance is supposed to be simple in concept. The policyholder suffers a covered loss. The carrier pays what it costs to make the policyholder whole. When a carrier substitutes a preferred vendor&apos;s uncommitted estimate for a contractor&apos;s committed bid, it is not indemnifying the insured. It is paying what the carrier wishes the repair would cost, rather than what the repair will actually cost.
      </p>
      <p className="text-gray-700 leading-relaxed mb-6">
        A number without a commitment is just a number. A bid is a promise. And the distance between the two &mdash; the gap between what a software program calculates and what a contractor will actually charge to restore a family&apos;s home &mdash; is where claims go to die.
      </p>

      <CalloutBox variant="warning" title="Key Legal References">
        <p>
          California Insurance Code Section 790.03(h); 10 CCR 2695.7; 10 CCR 2695.9; CACI 2201; Xactware EULA, Section 12.3; UCC Section 2-205; <em>Gruenberg v. Aetna Insurance Co.</em> (1973) 17 Cal.3d 860; <em>Egan v. Mutual of Omaha Insurance Co.</em> (1979) 24 Cal.3d 809; <em>Quelimane Co. v. Stewart Title Guaranty Co.</em> (1998) 19 Cal.4th 26.
        </p>
      </CalloutBox>
    </>
  )
}
