import Link from 'next/link'

export const meta = {
  title: "The Three Lives of an Xactimate Document: Estimate, Bid, and Invoice",
  description: "Understanding why an Xactimate estimate without a commitment to perform is fundamentally different from a contractor's bid, and how that distinction affects insurance claim payments.",
}

export default function Content() {
  return (
    <>
      <p className="text-gray-700 leading-relaxed mb-4">
        A contractor walks through your fire-damaged home, opens Xactimate on a tablet, photographs every room, measures every wall, and produces a forty-page document listing every line item needed to restore your property. The total is $287,000. You sign a contract with that contractor to perform the work at that price. You submit the document to your insurance company.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Two weeks later, the carrier sends its own contractor &mdash; a &quot;preferred vendor&quot; who has never met you and has no interest in performing the work &mdash; to walk through the same house. That contractor also opens Xactimate, also photographs and measures, and produces a separate forty-page document. The total is $194,000. The carrier tells you it will pay $194,000 because that is what the work &quot;should cost.&quot;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        On the surface, you are looking at two Xactimate documents. They use the same software, the same line-item database, the same general formatting. A reasonable person might assume they represent two competing prices for the same job. The carrier certainly wants you to think so. But these two documents are fundamentally different things. One is a bid. The other is an estimate. The distinction is not semantic &mdash; it is the difference between a price someone will actually honor and a number generated by someone who has no intention of doing the work. And that distinction has legal, practical, and financial consequences that most policyholders &mdash; and many adjusters &mdash; never consider.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Understanding What Xactimate Actually Is</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        Before examining what an Xactimate document means, it helps to understand what Xactimate actually does.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate is property claims estimating software developed by Xactware Solutions, a subsidiary of Verisk Analytics. It is the dominant estimating platform in the property insurance industry. Carriers, independent adjusters, public adjusters, and contractors all use it. The software contains a database of line items &mdash; thousands of individual tasks such as &quot;remove and replace drywall, 1/2 inch, hung, taped, floated, ready for paint&quot; &mdash; each associated with a price drawn from Verisk&apos;s proprietary pricing database.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The pricing database is updated monthly and organized by geographic region. Verisk describes its methodology as based on &quot;primary sources including labor, equipment, or material providers; contractors and subcontractors; and Xactimate customers,&quot; acquired through surveys, direct data feeds, and completed estimates. The company collects more than 345,000 survey points annually and analyzes millions of estimates to generate what it calls a &quot;single representative price per line item, computed from all valid price points researched within the market.&quot;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        That language sounds precise, but it conceals an important limitation. The price Xactimate assigns to any given line item is a statistical composite &mdash; a calculated midpoint. Verisk&apos;s own pricing research methodology document acknowledges that &quot;some market price data are higher, and some market price data are lower than that which are reported.&quot; In plain terms, the Xactimate price for any line item is not necessarily what any specific contractor in a given market would charge. It is what the software calculates based on historical survey data that, by the time it reaches the user, is already at least thirty days old.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Verisk itself has acknowledged this. Its own bulletin on roofing prices has noted that price variations of 50% from low to high within a single market are common, and that variations of 100% are &quot;not uncommon.&quot; When a single line item can vary by a factor of two within the same zip code, the notion that an Xactimate document represents &quot;the price&quot; for any particular job becomes difficult to sustain.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        And Verisk&apos;s End User License Agreement goes further. Section 12.3 of the Xactware EULA states plainly: <strong>&quot;We do not warrant the accuracy of pricing information in the Price Data.&quot;</strong> Users are expected to &quot;agree not to prohibit or preclude deviations from the Price Data where contractor requirements, market conditions, demand or any other factor warrants the use of different line-item price in the specific situation.&quot;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This is the software&apos;s creator telling its users &mdash; in a binding legal agreement &mdash; that its prices are not guaranteed to be accurate and should be adjusted when real-world conditions warrant it. The EULA effectively characterizes Xactimate pricing as a starting point, not a destination.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        As the <em>Daily Journal</em> observed in a 2024 MCLE article titled &quot;Xactimate Is Not the Law&quot;: nothing in a standard California homeowners policy authorizes an insurer to limit its obligations to whatever figure a third-party software program generates. The policy obligates the carrier to pay what it actually costs to restore the property. Xactimate is a tool for calculating that cost. It is not a substitute for it.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Life One: The Estimate</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        At its most basic, an Xactimate document is an estimate &mdash; a calculation of what work should cost based on the inputs selected by the person who prepared it.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        An estimate is an opinion. It reflects the estimator&apos;s judgment about what needs to be done (the scope of work) and what it should cost (pricing). The quality of the estimate depends entirely on the quality of those judgments. An experienced contractor who walks every room, opens every wall cavity, and accounts for code upgrades will produce a different estimate than a desk adjuster who reviews photographs from a tablet. Both are estimates. Neither is inherently authoritative.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The word &quot;estimate&quot; carries a specific meaning in contract law. An estimate is not an offer. It does not create contractual obligations. It is not a promise to perform work at the stated price. It is an approximation &mdash; a projection of probable cost based on available information.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This is not a controversial legal proposition. Courts and commentators have consistently distinguished estimates from offers. The Restatement (Second) of Contracts, &sect;24, defines an offer as &quot;the manifestation of willingness to enter into a bargain, so made as to justify another person in understanding that his assent to that bargain is invited and will conclude it.&quot; An estimate, by contrast, manifests no such willingness. It communicates information. It does not invite assent.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        When someone produces an Xactimate document, that document is an estimate. Full stop. It may later become something else, depending on context and intent. But at the moment of creation, it is a calculation &mdash; nothing more.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Life Two: The Bid</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        An estimate becomes a bid when it is combined with the intention to win and perform the job. Intent is the dividing line. It is what separates a number on a page from a commitment backed by a contractor&apos;s willingness to actually do the work.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This distinction is critical, and it is the one most frequently collapsed in insurance claims disputes.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">When an Estimate Is a Bid From Day One</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        A retail contractor &mdash; a roofing company, a general contractor, a restoration firm &mdash; inspects a damaged property and prepares an Xactimate document. The contractor wants the job. The contractor is willing to perform the work at the price stated. The contractor hands the document to the homeowner and says, in effect: &quot;This is what I will do the work for.&quot;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        That Xactimate document is both an estimate (a calculation of cost) and a bid (a commitment to perform). It functions as an offer in the contractual sense &mdash; a manifestation of willingness to enter into a bargain. If the homeowner accepts, a contract can be formed.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        A bid carries an implicit promise. The contractor who submits a bid is saying: I have evaluated this project, I have assessed the scope, I have calculated the costs, I have accounted for my overhead and profit, and I am willing to commit my company&apos;s resources to performing this work at this price. That promise has economic value. It represents the contractor&apos;s professional judgment, backed by the contractor&apos;s reputation, license, bond, and insurance.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Under the UCC and common law, a bid from a contractor functioning as a merchant in goods and services represents something substantively different from a mere price quotation. UCC &sect;2-205 provides that a merchant&apos;s signed, written offer to buy or sell goods is irrevocable for up to three months even without consideration &mdash; the &quot;firm offer&quot; rule. While construction contracts are not directly governed by the UCC (which applies to the sale of goods), the principle illuminates a broader legal truth: the law treats commitments differently from estimates precisely because commitments carry obligations that estimates do not.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">When an Estimate Is Not a Bid</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Now consider a different scenario &mdash; one that plays out on property claims every day across the country.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        An insured homeowner has already signed a contract with a general contractor. The contractor has begun the permitting process, ordered materials, and scheduled subcontractors. The insurance company sends its preferred vendor to the property to &quot;inspect&quot; and &quot;prepare an estimate.&quot;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The preferred vendor knows another contractor has already been engaged. The preferred vendor is not competing for this job. The preferred vendor has no intention of performing the work. The preferred vendor&apos;s sole purpose is to produce an Xactimate document that the carrier can use to justify a lower payment.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The document that preferred vendor produces is an estimate. It is not a bid. It cannot be a bid, because the essential element of a bid &mdash; the intent to win and perform the job &mdash; is absent. The preferred vendor has no intention of doing the work. The preferred vendor has not committed company resources to the project. The preferred vendor has not ordered materials, scheduled subcontractors, or obtained permits. The preferred vendor is not willing to be held to the price stated in the document.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This is not a technicality. The distinction between an estimate and a bid maps directly onto fundamental concepts in contract law. An invitation to deal &mdash; sometimes called an invitation to treat or an invitation to negotiate &mdash; is a communication that, while it may reference prices, does not constitute an offer because it lacks the necessary element of commitment. A store&apos;s advertisement showing a price is typically an invitation to deal, not an offer. A real estate listing is an invitation to deal, not an offer. And a preferred vendor&apos;s Xactimate document, prepared at the carrier&apos;s direction with no intent to perform the work, is an invitation to deal at best &mdash; and a litigation tool at worst.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Tortious Interference Problem</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The preferred vendor scenario raises a question that deserves more attention than it typically receives: what happens if the preferred vendor does not merely estimate, but actively attempts to convince the homeowner to switch contractors?
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        California law recognizes the tort of intentional interference with contractual relations. Under <a href="https://www.justia.com/trials-litigation/docs/caci/2200/2201/" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">CACI 2201</a> (California Civil Jury Instructions), the elements are: (1) a valid contract between the plaintiff and a third party; (2) the defendant&apos;s knowledge of this contract; (3) the defendant&apos;s intentional acts designed to induce a breach or disruption of the contractual relationship; (4) actual breach or disruption of the contractual relationship; and (5) resulting damage.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        When a homeowner has signed a contract with a general contractor, a preferred vendor who knows about that contract and attempts to persuade the homeowner to terminate it and hire the preferred vendor instead is engaging in conduct that falls squarely within the elements of this tort. The preferred vendor knows a contract exists &mdash; they were told as much when sent to the property. If they actively solicit the homeowner&apos;s business, they are intentionally acting to disrupt that contract. If the homeowner terminates the existing contract as a result, the original contractor has been damaged.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Importantly, California courts have held that a cause of action for intentional interference with contractual relations does not require that the defendant&apos;s conduct be independently wrongful &mdash; unlike the related tort of interference with prospective economic advantage. The interference itself, if intentional and causing disruption, can be actionable. <em>See Quelimane Co. v. Stewart Title Guaranty Co.</em> (1998) 19 Cal.4th 26, 55-56.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This has practical implications for the claims process. A preferred vendor who stays in their lane &mdash; inspecting the property and preparing an estimate for the carrier&apos;s internal use &mdash; is performing a legitimate function. A preferred vendor who begins marketing to the homeowner, criticizing the existing contractor&apos;s pricing, or suggesting that the homeowner could save money by switching is engaged in conduct that may expose both the vendor and the carrier to liability.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The subtle point is this: if a preferred vendor cannot ethically or legally try to win the job, the document they produce cannot honestly be characterized as a competing bid. A bid implies competition. Competition implies intent to win. If the vendor has no intent to win &mdash; and would face legal exposure if they tried &mdash; then the document is not a bid, regardless of what it looks like on the page.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">When an Estimate Becomes a Bid Later</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The character of an Xactimate document is not necessarily fixed at the moment of creation. An estimate can become a bid when the estimator&apos;s intent changes.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        A contractor who prepares an estimate as a courtesy &mdash; perhaps a friend evaluating damage for informational purposes &mdash; might later decide they want the work. At that point, the same document takes on a different character. It is no longer merely a calculation; it is backed by the contractor&apos;s willingness to perform. The document has not changed. The intent behind it has.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This fluidity cuts both ways. A contractor who submits a bid might later withdraw it, reverting the document to a mere estimate (or rendering it void entirely). The point is that the Xactimate document itself is neutral. Its legal and practical significance depends on the context in which it exists and the intent of the person who produced it.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Life Three: The Invoice</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        An Xactimate document can also serve as an invoice &mdash; or more precisely, as the supporting documentation for an invoice.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This transition occurs when the insured enters into a contract with the contractor, and the contractor completes the work in accordance with the contract terms. At that point, the Xactimate document that began as an estimate, became a bid, and supported a contract now serves as the basis for the contractor&apos;s request for payment. It documents what was done, in what quantities, at what prices.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This is the final form of the Xactimate document&apos;s lifecycle, and it is the one most directly tied to the actual cost of repairs. An invoice is a demand for payment for work performed. It represents an economic reality &mdash; labor was expended, materials were consumed, the property was restored. The price on the invoice is not theoretical. It is what the work cost.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The distinction matters because insurance policies are contracts of indemnity. The insurer&apos;s obligation is to indemnify the insured &mdash; to make the insured whole for the loss sustained. Under a replacement cost policy, this means paying what it actually costs to repair or replace the damaged property to its pre-loss condition.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        California&apos;s Fair Claims Settlement Practices Regulations reinforce this obligation. <a href="https://www.law.cornell.edu/regulations/california/10-CCR-2695.9" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">10 CCR &sect;2695.9(b)</a> requires that estimates prepared by or for the insurer be &quot;in accordance with applicable policy provisions, of an amount which will restore the damaged property to no less than its condition prior to the loss and which will allow for repairs to be made in a manner which meets accepted trade standards for good and workmanlike construction.&quot; <a href="https://www.law.cornell.edu/regulations/california/10-CCR-2695.9" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">Section 2695.9(d)</a> further requires that &quot;the insurer shall take reasonable steps to verify that the repair or rebuilding costs utilized by the insurer or its claims agents are accurate and representative of costs in the local market area.&quot;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        When the insured presents an invoice &mdash; or an Xactimate bid that has been fulfilled by the contractor &mdash; the carrier is confronted with evidence of actual cost. The insured is not asking what the work should theoretically cost. The insured is telling the carrier what the work did cost, and requesting indemnification.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">The Critical Insight: Apples and Oranges</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        Here is where the three lives of an Xactimate document converge into a problem that affects thousands of claims every year.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        A homeowner&apos;s contractor inspects the property, prepares an Xactimate document, and submits a bid of $287,000. The contractor is willing to perform the work at that price. The homeowner signs a contract. The bid reflects the contractor&apos;s actual costs: the labor rates they pay their crews, the material prices from their suppliers, their overhead for running a construction business, and a reasonable profit margin. The price is real. It represents what it will actually cost to get the work done.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The carrier&apos;s preferred vendor inspects the same property, prepares a separate Xactimate document, and produces an estimate of $194,000. The preferred vendor has no intention of doing the work. The preferred vendor will not be held to that price. The preferred vendor has made no commitment of resources, scheduled no subcontractors, and ordered no materials. The preferred vendor has no contractual exposure if the estimate turns out to be inadequate.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The carrier then treats these two documents as equivalent &mdash; as though they are competing bids from two contractors vying for the same job. The carrier pays $194,000 and tells the homeowner that the difference of $93,000 is the homeowner&apos;s problem.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        But these documents are not equivalent. One is a bid. The other is an estimate. And the difference between a bid and an estimate is not formatting or software version or the number of line items. The difference is commitment.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        A bid is backed by a promise. The contractor who submits a bid is telling the homeowner: I will do this work for this amount. If I underbid the job, I absorb the loss. If materials cost more than I projected, I bear that risk. If my labor costs run over, I pay the difference. The bid price represents the contractor&apos;s professional assessment of the actual cost of the project, adjusted for real-world conditions, and backed by the contractor&apos;s willingness to be bound by that number.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        An estimate backed by no intent to perform carries none of these commitments. The preferred vendor who produces a $194,000 estimate will never have to buy a single sheet of drywall at that price. They will never have to hire a subcontractor at the labor rates reflected in that document. They will never have to explain to a homeowner why the work is taking longer than expected or costing more than projected. The estimate is cost-free for the person who produced it. It is, in the most literal sense, a hypothetical.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        When the carrier treats an uncommitted estimate as equivalent to a committed bid, it is comparing two fundamentally different categories of information. It is treating a theoretical exercise as though it were a market price. It is using a document that its own creator &mdash; Verisk, through the EULA &mdash; says should not be relied upon as accurate pricing, and presenting it as the measure of the insured&apos;s loss.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Why This Should Concern Every Policyholder</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        The estimate-versus-bid distinction has consequences that extend far beyond individual claims. It touches the core of the insurance contract and the carrier&apos;s obligation to act in good faith.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Market Price Problem</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        A competitive bid is a market price indicator. It represents what a willing contractor will charge a willing property owner for specific work in a specific market at a specific time. Market prices are determined by competition &mdash; multiple contractors evaluating the same job and submitting prices at which they are willing to perform.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        A preferred vendor&apos;s estimate is not a market price indicator. It is a software output generated by someone who is not competing for the job and has no intention of performing it. The preferred vendor&apos;s &quot;price&quot; was never tested against the market. No competing contractor reviewed the scope and said, &quot;Yes, I will also do it for that amount.&quot; No subcontractor confirmed they would work at those labor rates. No supplier confirmed those material costs.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The economic concept underlying a market price is the existence of a willing buyer and a willing seller engaging in an arm&apos;s-length transaction. A preferred vendor producing an estimate at the carrier&apos;s direction &mdash; with no intention of performing the work &mdash; does not satisfy either condition. The vendor is not a willing seller. There is no arm&apos;s-length transaction. The resulting number is not a market price. It is an internal carrier document dressed up as one.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Regulatory Framework</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        California&apos;s regulatory scheme is built on the premise that carriers must pay what it actually costs to restore damaged property &mdash; not what a software program says it should cost.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <a href="https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=790.03.&lawCode=INS" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">California Insurance Code &sect;790.03(h)</a> defines unfair claims settlement practices, including:
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>Not attempting in good faith to effectuate prompt, fair, and equitable settlements of claims in which liability has become reasonably clear.</li>
        <li>Compelling insureds to institute litigation to recover amounts due under an insurance policy by offering substantially less than the amounts ultimately recovered.</li>
        <li>Failing to promptly provide a reasonable explanation of the basis relied on in the insurance policy, in relation to the facts or applicable law, for the denial of a claim or for the offer of a compromise settlement.</li>
      </ul>

      <p className="text-gray-700 leading-relaxed mb-4">
        <a href="https://www.law.cornell.edu/regulations/california/10-CCR-2695.7" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">10 CCR &sect;2695.7(g)</a> provides that no insurer shall attempt to settle a claim by making a settlement offer that is unreasonably low. The standard is not whether the offer matches the output of a particular software program. The standard is whether the offer is reasonable in light of the actual cost of repairs.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <a href="https://www.law.cornell.edu/regulations/california/10-CCR-2695.9" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">Section 2695.9(d)</a> requires that repair and rebuilding costs be &quot;accurate and representative of costs in the local market area.&quot; A preferred vendor&apos;s estimate, produced by someone with no intent to perform the work and no exposure to the actual costs of performing it, may not satisfy this standard &mdash; particularly when the insured has presented a contractor&apos;s bid that reflects actual market conditions.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The implied covenant of good faith and fair dealing, recognized in every California insurance contract since <em>Gruenberg v. Aetna Insurance Co.</em> (1973) 9 Cal.3d 566 and reinforced in <em>Egan v. Mutual of Omaha Insurance Co.</em> (1979) 24 Cal.3d 809, imposes on insurers a duty to investigate claims thoroughly, evaluate them fairly, and pay what is owed. Using a non-bid estimate to justify underpaying a claim when the insured has presented a legitimate contractor&apos;s bid raises questions about whether that duty has been met.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Xactimate-as-Gospel Problem</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        A pattern has emerged across the property insurance industry. Carriers treat Xactimate output as though it were an objective, unchallengeable measure of repair costs. Adjusters are trained to write estimates in Xactimate. Claims are evaluated against Xactimate benchmarks. Supplements are approved or denied based on whether they conform to Xactimate pricing.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        But Xactimate&apos;s own creator says the pricing is not guaranteed to be accurate. The EULA disclaims warranty on pricing. The methodology acknowledges wide variation. The price lists are historical, not current. And the software is a tool &mdash; no different in kind from a tape measure or a moisture meter. A tape measure is useful for determining the dimensions of a room, but no one would argue that the tape measure determines how much the repair should cost. Xactimate is useful for organizing and pricing a scope of work, but it does not determine what the work will actually cost in the real world.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        When the insured&apos;s contractor submits an Xactimate bid &mdash; prepared using the same software, the same database, the same line items &mdash; and the carrier rejects it in favor of the carrier&apos;s own Xactimate estimate, the carrier is not making a software-based determination. The carrier is making a choice. And that choice is to prefer the number generated by its own vendor over the number generated by the insured&apos;s contractor, even though only one of those numbers is backed by an actual commitment to perform.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">What the Insured Can Do</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        Understanding the three lives of an Xactimate document is not merely an academic exercise. It provides policyholders and their representatives with a framework for challenging carrier underpayments.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Demand the Carrier Identify the Nature of Its Document</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        When a carrier presents a preferred vendor&apos;s Xactimate document as the basis for its payment, the insured should ask a simple question: <strong>Is this a bid?</strong>
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        If the answer is yes, then the carrier should be able to identify the contractor who is willing to perform the work at that price, the terms under which the contractor will perform, and the contractor&apos;s commitment to honor the price. If the carrier cannot produce a contractor who will actually do the work for the amount stated, the document is not a bid. It is an estimate. And an estimate without a commitment to perform is not evidence of what the work will cost &mdash; it is evidence of what a software program calculated.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Document the Contractor&apos;s Commitment</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The insured&apos;s contractor should make the nature of their document clear. The Xactimate bid should be accompanied by &mdash; or reference &mdash; a written contract in which the contractor commits to performing the work at the stated price. This transforms the document from an estimate into a bid, and eventually into an invoice. The carrier may still dispute the amount, but it cannot credibly claim that the insured&apos;s contractor&apos;s price is merely a theoretical calculation when it is backed by a binding contract.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Invoke the Regulatory Framework</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        California policyholders have a regulatory infrastructure designed to prevent exactly this kind of conduct. The Fair Claims Settlement Practices Regulations require that carrier estimates be &quot;accurate and representative of costs in the local market area.&quot; <a href="https://www.law.cornell.edu/regulations/california/10-CCR-2695.9" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">10 CCR &sect;2695.9(d)</a>. An estimate produced by a preferred vendor with no intent to perform &mdash; and no exposure to actual market costs &mdash; may not meet this standard.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        When the carrier&apos;s estimate is significantly lower than the insured&apos;s contractor&apos;s bid, the insured or the insured&apos;s representative should request a written explanation of the basis for the carrier&apos;s lower figure, as required by <a href="https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=790.03.&lawCode=INS" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">Insurance Code &sect;790.03(h)(13)</a>. The carrier must provide &quot;a reasonable explanation of the basis relied on in the insurance policy, in relation to the facts or applicable law, for the denial of a claim or for the offer of a compromise settlement.&quot; A response that amounts to &quot;our Xactimate estimate is lower&quot; does not satisfy this requirement. The carrier must explain why its estimate is more reliable than the insured&apos;s contractor&apos;s bid &mdash; and it must do so in a way that accounts for the fundamental difference between an estimate and a bid.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Preserve the Record for Appraisal or Litigation</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        If the claim proceeds to appraisal or litigation, the distinction between an estimate and a bid becomes evidence. The insured&apos;s appraiser or attorney can depose the preferred vendor and establish that:
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>The vendor had no intention of performing the work.</li>
        <li>The vendor was not competing for the job.</li>
        <li>The vendor&apos;s price was not a bid.</li>
        <li>The vendor would not have been bound by the price stated in the document.</li>
        <li>The vendor was aware that another contractor had already been engaged.</li>
      </ul>

      <p className="text-gray-700 leading-relaxed mb-4">
        Each of these facts undermines the carrier&apos;s attempt to treat the preferred vendor&apos;s estimate as a competitive bid. The carrier is left defending a payment based not on what the work will actually cost, but on what a non-competing, non-committed, non-performing vendor calculated using software whose own creator disclaims the accuracy of its pricing data.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">The Broader Principle</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        Insurance is supposed to be simple in concept, even when it is complex in practice. The policyholder suffers a covered loss. The carrier pays what it costs to make the policyholder whole. The policy is a contract of indemnity, and indemnity means restoring the insured to the position they occupied before the loss.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        When a carrier substitutes a preferred vendor&apos;s uncommitted estimate for a contractor&apos;s committed bid, it is not indemnifying the insured. It is paying what the carrier wishes the repair would cost, rather than what the repair will actually cost. The preferred vendor&apos;s estimate is not wrong because the numbers are necessarily inaccurate &mdash; though they may be. It is insufficient because the numbers are not backed by anyone&apos;s willingness to do the work at that price.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        A number without a commitment is just a number. A bid is a promise. And the distance between the two &mdash; the gap between what a software program calculates and what a contractor will actually charge to restore a family&apos;s home &mdash; is where claims go to die.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The next time an adjuster presents a preferred vendor&apos;s Xactimate document and calls it a &quot;competitive estimate,&quot; ask the question that reframes the entire conversation: <strong>Who is competing?</strong>
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <em>Leland Coontz is a California Licensed Public Adjuster who represents policyholders in property insurance claims. This article is for informational purposes and does not constitute legal advice. Policyholders facing claim disputes should consult with a qualified attorney in their jurisdiction.</em>
      </p>
    </>
  )
}
