import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: "Your Right to the Xactimate ESX File: Why the PDF Is Not Enough",
  description: "A guide for policyholders, public adjusters, and attorneys on why you should demand the native Xactimate ESX file — not just the PDF printout — and what critical estimate data the ESX file reveals that the PDF conceals.",
  summary:
    'Demand the native Xactimate ESX file, not just the PDF. The ESX reveals pricing settings, depreciation, and hidden adjustments the printout conceals, which is essential for spotting how the carrier built, and shaved, the estimate.',
}

export default function Content() {
  return (
    <>
      <CalloutBox variant="legal" title="This Article Is Not Legal Advice">
        <p>
          This article is educational commentary by a Licensed California Public
          Adjuster. It is not legal advice. For legal questions about your specific
          situation, consult a licensed California attorney.
        </p>
      </CalloutBox>

      <p className="text-gray-700 leading-relaxed mb-4">
        <em>A guide for policyholders, public adjusters, and attorneys on why the native Xactimate ESX file &mdash; not the PDF printout &mdash; is the document that matters, what it reveals that the PDF conceals, and how to obtain it.</em>
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Your insurance company just sent you a forty-page estimate for damage to your home. It arrived as a PDF &mdash; a neatly formatted document full of codes, quantities, measurements, and dollar amounts. It looks thorough. It looks official. And it is almost certainly incomplete.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        That PDF was not created in a vacuum. It was generated by a software platform called <Link href="/resources/xactimate" className="text-[#2E74B5] underline">Xactimate</Link>, the dominant estimating tool used by property insurance carriers across the United States. Xactimate does not produce PDFs natively. It produces ESX files &mdash; electronic data files that contain every parameter, every setting, every choice, and every calculation behind the estimate. The PDF is a printout of that file. It is a snapshot. And like any snapshot, it shows you what someone wanted you to see, not necessarily the full picture.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The difference between the ESX file and the PDF is the difference between seeing a photograph of a building and walking through every room. One gives you an impression. The other gives you the facts. And in insurance claims, the facts are where underpayments are found.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This article explains what the ESX file is, what it contains that the PDF does not show, why you have the right to receive it, how to request it, and what to look for once you have it in hand.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">What an ESX File Is</h2>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Native Xactimate File Format</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        An ESX file is the native electronic file format produced by <Link href="/resources/xactimate" className="text-[#2E74B5] underline">Xactimate</Link>. When an insurance company adjuster or an independent adjuster opens Xactimate, creates a new estimate, enters line items, draws sketches, selects settings, and calculates totals, the result is saved as an ESX file. That file is the estimate. Everything else &mdash; the PDF printout, the summary page, the scope of loss letter &mdash; is derived from it.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The ESX file is a structured data container. It does not simply store a list of line items and prices the way a spreadsheet might. It stores the complete architecture of the estimate, including:
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>Every individual line item</strong> &mdash; the Xactimate code, description, quantity, unit of measure, unit price, total price, trade category, and whether the item was user-modified or system-generated.</li>
        <li><strong>The price list</strong> &mdash; the specific <Link href="/resources/xactimate-price-list-dates" className="text-[#2E74B5] underline">Xactimate price list</Link> version and date used to generate all pricing, including the geographic region and zip code.</li>
        <li><strong>Labor efficiency settings</strong> &mdash; the <Link href="/resources/xactimate-labor-efficiency-settings" className="text-[#2E74B5] underline">labor productivity factor</Link> applied globally to every labor line item, which determines whether the estimate is priced for restoration, rebuild, or new construction conditions.</li>
        <li><strong>Overhead and profit calculations</strong> &mdash; whether <Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">overhead and profit</Link> was included, excluded, or partially applied, and at what percentages.</li>
        <li><strong>Depreciation parameters</strong> &mdash; the depreciation methodology, useful life assumptions, condition ratings, and calculations that produced the actual cash value figures.</li>
        <li><strong>Sketches and dimensions</strong> &mdash; the digital floor plans, room measurements, wall heights, and area calculations that drive quantity takeoffs throughout the estimate.</li>
        <li><strong>Category settings</strong> &mdash; how line items are grouped, which trades are included, and the structure of the estimate&apos;s organizational hierarchy.</li>
        <li><strong>Notes and audit trail</strong> &mdash; adjuster notes, system-generated entries, timestamps, modification history, and comments that document the estimating process.</li>
        <li><strong>Coverage and deductible information</strong> &mdash; policy limits, deductible amounts, and coverage categorizations applied within the estimate.</li>
        <li><strong>User-modified pricing</strong> &mdash; any line items where the adjuster manually overrode the Xactimate database price, either up or down, along with the original database price for comparison.</li>
      </ul>

      <p className="text-gray-700 leading-relaxed mb-4">
        In short, the ESX file is the complete record of every decision the estimator made. It is not a summary. It is the source.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Relationship Between the ESX File and the PDF</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        When an adjuster finishes an estimate in Xactimate, one of the last steps is exporting the estimate to a PDF for delivery to the policyholder. The PDF export function allows the estimator to select which sections to include and which to exclude. The estimator can choose which reports to print, which summaries to show, and &mdash; critically &mdash; which detail views to omit.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The PDF is to the ESX file what a report card is to a student&apos;s full academic record. The report card shows grades. The full record shows attendance, individual assignment scores, teacher notes, behavioral observations, test-by-test performance, and the grading scale used. Both are accurate in what they present. But only one tells you the complete story.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Every experienced public adjuster and every insurance litigation attorney who handles property claims understands this distinction. The PDF is useful for a quick overview of what the carrier is proposing. The ESX file is essential for determining whether the carrier&apos;s proposal is fair, accurate, and consistent with the actual conditions of the loss.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Why the PDF Is Not Enough</h2>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">What the PDF Shows</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        A typical Xactimate PDF export will include a summary page showing the total estimate broken down by coverage category, a detailed line-item listing showing each item&apos;s code, description, quantity, and price, and possibly a sketch or floor plan. Some PDFs also include a depreciation summary showing the amounts withheld for recoverable depreciation.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        On its face, this appears comprehensive. But appearances are misleading. The PDF presents results without context. It shows the final numbers without revealing the inputs and assumptions that produced them. And in Xactimate, the inputs and assumptions are where the most consequential decisions live.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">What the PDF Hides</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The following critical pieces of information are either not shown or not clearly identified in a standard Xactimate PDF export:
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Labor Efficiency Settings.</strong> The PDF does not prominently display which <Link href="/resources/xactimate-labor-efficiency-settings" className="text-[#2E74B5] underline">labor efficiency category</Link> was selected for the estimate. This is arguably the single most consequential global setting in the software. It determines whether every labor line item is priced at restoration productivity rates, rebuild productivity rates, or new construction productivity rates. The difference between restoration and rebuild settings can reduce an estimate by fifteen to thirty percent across every labor-intensive line item. A policyholder reading the PDF has no practical way to identify which setting was used without access to the ESX file.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Price List Version and Date.</strong> Every Xactimate estimate is built on a <Link href="/resources/xactimate-price-list-dates" className="text-[#2E74B5] underline">price list</Link> &mdash; a database of material and labor costs that Verisk updates monthly for each geographic region. The price list date determines the baseline pricing for every line item in the estimate. If an adjuster uses a price list from six months before the date of loss, every material and labor price in the estimate may be lower than the costs the contractor will actually face when performing the work. The PDF may show a price list date somewhere in its header, but it does not make it easy to compare that date against the date of loss or the date repairs will actually begin. The ESX file stores this data in a structured, queryable format.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Overhead and Profit Inclusion or Exclusion.</strong> The PDF will show line items and their prices, but it may not clearly indicate whether <Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">overhead and profit</Link> has been included in the estimate or excluded from it. In the ESX file, the O&amp;P setting is a discrete, identifiable parameter. You can see exactly whether O&amp;P was applied, at what percentage, and to which line items or categories. In the PDF, this information may be buried in a subtotal line that a non-professional reader could easily overlook or misinterpret.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Depreciation Parameters and Methodology.</strong> For actual cash value payments, the carrier withholds depreciation &mdash; the estimated reduction in value of damaged items based on their age and condition. The PDF typically shows a depreciation amount but does not always reveal the useful life assumption used, the depreciation rate applied, or the condition factor assigned. The ESX file contains these parameters for every depreciable line item. Without the ESX file, a policyholder or their representative cannot verify whether the depreciation calculations are reasonable, consistent with the actual condition of the property, or even mathematically correct.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>User-Modified Prices.</strong> Xactimate allows the estimator to override any line item&apos;s database price. When an adjuster manually reduces a price from the Xactimate database amount to a lower figure, the ESX file records both the original database price and the modified price. The PDF shows only the final price. Without the ESX file, there is no way to know whether the prices in the estimate reflect the Xactimate database or the adjuster&apos;s manual intervention.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Line Item Codes and Categories.</strong> While the PDF does show line item codes, the ESX file provides the full code structure, including the category, subcategory, and selector information that determines exactly which version of a line item was used. This matters because Xactimate often has multiple codes for similar work, and the code selection can significantly affect the price. For example, the code for removing and replacing drywall on walls differs from the code for drywall on ceilings, and the code for textured drywall differs from the code for smooth-finish drywall. The ESX file makes it possible to systematically verify that the correct codes were selected for the actual conditions of the loss.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Notes and Internal Comments.</strong> Adjusters frequently add notes to the ESX file during the estimating process. These notes may include observations about the property, explanations for why certain items were included or excluded, references to coverage decisions, or instructions to the carrier&apos;s desk reviewer. Some of these notes appear in the PDF. Many do not. The ESX file contains the complete note history.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Cumulative Effect</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Each of these hidden parameters, considered individually, might seem like a technical detail. Considered together, they represent the complete set of decisions that determined the dollar amount of your claim payment. A labor efficiency setting that reduces labor costs by twenty percent, combined with an outdated price list that understates material costs by five percent, combined with the exclusion of overhead and profit at ten percent each, combined with aggressive depreciation assumptions, can produce an estimate that is forty to fifty percent below the actual cost of repairs.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The policyholder looking at the PDF sees a final number. The policyholder looking at the ESX file sees how that number was constructed.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Why Carriers Prefer to Provide Only the PDF</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        It is worth considering why, when a policyholder submits a claim and receives an estimate, the default delivery format is a PDF and not the ESX file. The PDF presents a finished product. The ESX file reveals the process. And the process is where questions arise.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        When a carrier provides only the PDF, the policyholder is in the position of a consumer reading a price tag without seeing the cost structure behind it. The information is curated. The presentation is controlled. The context is limited to what the presenter chose to include. The policyholder can agree with the total, disagree with the total, or hire someone to write a competing estimate &mdash; but they cannot look under the hood of the estimate they were given.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        When a carrier provides the ESX file, every assumption is exposed. If the adjuster selected a rebuild labor efficiency setting on a restoration project, that choice is visible. If the adjuster used a price list from eight months before the date of loss, that decision is on the record. If the adjuster manually reduced the database price for fifty line items, every override is documented. If overhead and profit were excluded despite the involvement of multiple trades, the exclusion is a data point, not a footnote.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The ESX file, in other words, is the evidence. The PDF is the presentation. Policyholders, public adjusters, and plaintiff attorneys are better served by the evidence.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        A carrier whose estimate was prepared honestly, using the correct settings and a comprehensive scope, has nothing to fear from producing the ESX file. A well-built estimate stands up to scrutiny. The carriers that resist producing the file are, by that resistance, telling you something about the choices they made inside it.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Your Right to the ESX File</h2>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">California Insurance Code &sect;2071 &mdash; Claim-Related Documents</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        California Insurance Code Section 2071 requires insurers to notify every claimant that they may obtain, upon request, copies of claim-related documents. The statute defines &quot;claim-related documents&quot; broadly to include all documents that relate to the evaluation of damages, including repair and replacement estimates, appraisals, scopes of loss, drawings, plans, reports, third-party findings on the amount of loss, and all other valuation, measurement, and loss adjustment calculations.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The ESX file is, by any reasonable interpretation, a claim-related document. It is the repair estimate itself &mdash; the PDF is merely a printout of it. Under &sect;2071, the insurer must provide copies of claim-related documents within fifteen calendar days of the policyholder&apos;s request.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">10 CCR &sect;2695.7(d) &mdash; Duty to Provide Documentation</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        California&apos;s Fair Claims Settlement Practices Regulations, codified at Title 10, California Code of Regulations, Section 2695.7(d), impose additional obligations on insurers. These regulations require that every insurer that issues a written denial of a claim or part of a claim must provide the policyholder with the factual and legal bases for the denial. More broadly, the fair claims settlement framework requires insurers to conduct thorough and fair investigations, to provide policyholders with the documentation necessary to understand how the claim was evaluated, and to act in good faith throughout the process.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Section 2695.7(b) further requires that every insurer disclose to the claimant all benefits, coverage, time limits, or other provisions of any insurance policy that may apply. When the basis of the insurer&apos;s valuation is embedded in a file it refuses to share, the insurer is effectively concealing the methodology behind its payment &mdash; which is inconsistent with these regulatory requirements.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The ESX File Is Part of the Claim File</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        There is a fundamental principle that underlies the policyholder&apos;s right to the ESX file: the estimate was created to document and evaluate a specific loss to the policyholder&apos;s specific property under a specific insurance policy. The ESX file was created by the carrier&apos;s adjuster or by an independent adjuster working on the carrier&apos;s behalf, using the carrier&apos;s software license, for the express purpose of evaluating the policyholder&apos;s claim. It was created using measurements, photographs, and observations of the policyholder&apos;s property. And it forms the basis for the carrier&apos;s coverage determination and payment calculation.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        A carrier that provides a PDF printout but refuses to provide the ESX file is providing a derivative document while withholding the source document. This is analogous to providing a summary of medical records while refusing to provide the actual medical records, or providing a financial statement while refusing to provide the underlying ledger entries. The summary may be accurate, but it is not the record &mdash; and the record is what the policyholder needs to evaluate the fairness of the carrier&apos;s determination.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Fair Claims Settlement Practices Require Transparency</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The National Association of Insurance Commissioners (NAIC) Unfair Claims Settlement Practices Act, which has been adopted in some form by nearly every state, prohibits insurers from failing to promptly provide a reasonable explanation of the basis in the insurance policy for the denial of a claim or for the offer of a compromise settlement. Many states, including California, have adopted regulations that go further, requiring insurers to provide policyholders with the documentation underlying the claims handling process upon request.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        An Xactimate estimate is not a take-it-or-leave-it number handed down from on high. It is a calculation based on inputs, settings, and assumptions. The policyholder has the right to review those inputs, settings, and assumptions. The ESX file is the document that contains them. Providing only the PDF while withholding the ESX file is inconsistent with the transparency obligations that the fair claims settlement framework imposes.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">In Litigation: The ESX File as Discovery</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        For attorneys handling insurance bad faith or breach of contract cases, the ESX file is a discovery item of the highest priority. When cases proceed to litigation, the ESX file is routinely requested in the first set of document demands, and courts have consistently ordered its production.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The ESX file is not privileged. It is not attorney work product. It is not a proprietary trade secret. It is a claim file document that records the carrier&apos;s factual evaluation of the loss. Carriers that resist producing ESX files in discovery generally find themselves on the wrong side of a motion to compel.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The point, for policyholders and their representatives, is that you should not have to wait until litigation to obtain this file. It should be provided as part of the normal claims process. And if it is not, that resistance itself becomes a data point in the story of how the claim was handled.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">How to Request the ESX File</h2>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Initial Request</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The most effective approach is to request the ESX file in writing as soon as you receive the carrier&apos;s estimate. The request should be specific, professional, and unambiguous. Here is sample language that can be adapted to your situation:
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <em>&quot;Dear [Adjuster Name], Thank you for providing the Xactimate estimate for Claim No. [number]. To fully evaluate the estimate and compare it against the actual scope of repairs, I am requesting the native Xactimate ESX file for this estimate. Please provide the ESX file in its original .esx format, not as a PDF or any other derivative format. This request includes all versions of the estimate, including any supplements, revisions, or internal working copies. Pursuant to California Insurance Code Section 2071 and 10 CCR Section 2695.7, please provide this file within fifteen calendar days of this request. Thank you for your prompt attention to this matter.&quot;</em>
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Send this request via email so that you have a timestamped record of the request and any response. If you are working with a public adjuster, they will typically make this request on your behalf as part of their standard claims handling process.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">When the Request Is Ignored or Refused</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        If the adjuster does not respond within the requested timeframe, send a follow-up communication referencing the original request and noting the lack of response. Document the date and method of each communication.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        If the carrier affirmatively refuses to provide the ESX file, ask for the refusal in writing and request that the carrier identify the specific legal or contractual basis for the refusal. Common carrier responses include:
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>&quot;The PDF contains all the information in the estimate.&quot;</strong> &mdash; This is inaccurate. The PDF is a partial representation of the data contained in the ESX file. The appropriate response is to identify specific data elements &mdash; labor efficiency settings, price list dates, user-modified prices &mdash; that are contained in the ESX file but not clearly shown in the PDF.</li>
        <li><strong>&quot;The ESX file is proprietary.&quot;</strong> &mdash; The Xactimate software is proprietary. The estimate data is not. The carrier does not own the data about your property any more than a doctor owns your medical records. The data was generated in the performance of the carrier&apos;s contractual obligations to you.</li>
        <li><strong>&quot;We are not required to provide the file in that format.&quot;</strong> &mdash; Whether the carrier is &quot;required&quot; to provide a specific file format is a separate question from whether the carrier is required to provide transparency regarding its claim evaluation. Fair claims settlement practices require that the carrier provide the policyholder with the information necessary to evaluate the claim determination. If the ESX file contains information that the PDF does not, then the PDF alone does not satisfy that obligation.</li>
        <li><strong>&quot;Our system does not allow us to export ESX files.&quot;</strong> &mdash; This is technically false. Xactimate has always supported ESX file export. If the carrier&apos;s internal claims management system does not permit easy ESX export, that is a limitation the carrier chose to implement. The limitation does not extinguish the policyholder&apos;s right to the data.</li>
        <li><strong>&quot;You don&apos;t have Xactimate, so the file would be useless to you.&quot;</strong> &mdash; Whether the policyholder personally owns Xactimate is irrelevant. The policyholder may have retained a public adjuster, an attorney, or a contractor who does have Xactimate. The insurer does not get to decide what the policyholder is or is not capable of doing with the documents to which they are legally entitled.</li>
      </ul>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Escalation Options</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        If the carrier continues to refuse after you have made a written request and documented the refusal, you have several escalation options:
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>File a complaint with your state&apos;s Department of Insurance.</strong> The complaint should describe the request, the refusal, and the specific regulatory provisions you believe the refusal violates. In California, complaints can be filed with the California Department of Insurance. Reference Insurance Code &sect;2071 and 10 CCR &sect;2695.7.</li>
        <li><strong>Engage a public adjuster.</strong> Public adjusters are licensed professionals who represent policyholders in the claims process. They work with Xactimate daily and know how to obtain and interpret ESX files. Their involvement often changes the dynamic of the carrier&apos;s response to documentation requests.</li>
        <li><strong>Consult an attorney.</strong> An attorney experienced in insurance coverage disputes can send a demand letter that carries legal weight. If the matter proceeds to litigation, the ESX file will be obtained through formal discovery.</li>
        <li><strong>Request through your state&apos;s appraisal process.</strong> If your policy contains an appraisal clause, invoking appraisal creates a framework in which both parties exchange estimating documentation. The ESX file is a standard document exchanged in appraisal proceedings.</li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">What to Look for Once You Have the ESX File</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        Obtaining the ESX file is only the first step. The file is a data container, and you need to know what to look for inside it. The following are the most important parameters to review. If you are not comfortable working with Xactimate directly, a public adjuster or an estimating consultant who has a current Xactimate license can perform this analysis for you.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Price List Date and Version</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Open the ESX file in Xactimate and check the <Link href="/resources/xactimate-price-list-dates" className="text-[#2E74B5] underline">price list date</Link>. This is the date of the pricing database that was used to generate every line item in the estimate. Compare the price list date to the date of loss and to the date when repairs are expected to begin.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate price lists are updated monthly. Material and labor costs fluctuate based on market conditions, supply chain dynamics, and regional labor availability. An estimate created using a price list from six or twelve months before the date of loss may understate current costs by a significant margin &mdash; particularly in periods of rising construction costs or after regional catastrophic events when demand for labor and materials spikes.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Also verify that the price list region matches the actual location of the property. Xactimate prices vary by zip code, and an estimate generated using the wrong geographic region will have incorrect pricing for every line item.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Labor Efficiency Settings</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Check the <Link href="/resources/xactimate-labor-efficiency-settings" className="text-[#2E74B5] underline">labor efficiency setting</Link> applied to the estimate. For the overwhelming majority of insurance repair work &mdash; claims involving partial losses to occupied or previously occupied structures &mdash; the appropriate setting is Restoration/Service/Remodel. This setting accounts for the real-world inefficiencies of working in an existing structure: protecting adjacent finishes, working around furniture and occupants, accessing work areas through finished spaces, and managing the stop-start workflow that characterizes restoration work.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        If the estimate uses a Rebuild or New Construction labor efficiency setting on a partial-loss claim, every labor line item in the estimate has been priced below the actual cost of performing the work. This is not a small difference. The labor efficiency setting can affect the estimate by fifteen to thirty percent or more, depending on the scope and trade mix of the work.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This is one of the single most important things you can check, and it is one of the things the PDF makes nearly impossible to verify.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Overhead and Profit</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Examine whether <Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">overhead and profit (O&amp;P)</Link> has been included in the estimate. O&amp;P is the general contractor&apos;s compensation for managing, coordinating, and bearing financial responsibility for the project. It is standard in the construction industry and is owed whenever the complexity of the project reasonably requires a general contractor.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        In the ESX file, you can see exactly whether O&amp;P was applied, the percentage used (the industry standard is ten percent overhead and ten percent profit), and whether it was applied to all line items or selectively excluded from certain categories. Some carriers apply O&amp;P only to certain trades or only above a certain threshold. The ESX file reveals these decisions; the PDF often obscures them.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Line Item Codes and Selections</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Review the specific Xactimate line item codes used in the estimate and compare them against the actual conditions of the loss. This requires knowledge of the Xactimate database, which contains thousands of line items organized by trade and activity. A public adjuster or experienced estimator can review the codes and identify situations where a lower-priced code was selected when a higher-priced code was appropriate, or where necessary work items were omitted entirely.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        For a detailed discussion of how line items work and what to look for, see our article on <Link href="/resources/how-to-challenge-xactimate-estimate" className="text-[#2E74B5] underline">how to challenge a Xactimate estimate</Link>.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">User-Modified Prices</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        One of the most revealing features of the ESX file is its ability to show user-modified prices. When an adjuster manually changes a line item price from the Xactimate database amount to a different figure, the ESX file records the modification. In some versions of Xactimate, modified items are flagged with an indicator, and the original database price remains accessible for comparison.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This is significant because Xactimate&apos;s pricing database is built from surveys of actual contractor costs in each geographic market. When an adjuster overrides the database price downward, they are substituting their judgment for the market data that Verisk collected. While there may be legitimate reasons for individual price adjustments, a pattern of systematic downward modifications across many line items raises questions about whether the estimate reflects actual repair costs or a predetermined outcome.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Depreciation Calculations</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        For claims paid on an actual cash value basis, the ESX file contains the depreciation parameters for every depreciable line item. Review the useful life assumptions, condition factors, and depreciation rates. Compare them against the actual age and condition of the damaged items.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Common issues include applying the same depreciation rate to all items regardless of their actual condition, using unreasonably short useful life assumptions, depreciating labor (which is prohibited in many jurisdictions, including California under applicable case law), and applying depreciation to items that were relatively new at the time of loss.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Sketch Accuracy</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The ESX file contains the digital sketches and dimensions that drive the quantity calculations throughout the estimate. If the sketch shows a room as ten by twelve feet but the room actually measures twelve by fourteen feet, every line item tied to that room &mdash; flooring, drywall, painting, baseboard &mdash; will be understated. The ESX file allows you to review the sketch dimensions systematically and compare them against field measurements.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Notes and Audit Trail</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Do not overlook the notes and internal comments contained in the ESX file. Adjusters sometimes record observations, instructions, or explanations within the file that never appear in the PDF. These notes may reveal the adjuster&apos;s reasoning for excluding items, instructions received from supervisors or desk reviewers, acknowledgments of damage that were not reflected in the final line items, or references to internal guidelines that dictated how the estimate was prepared. In litigation, these notes can be powerful evidence of how the claim was evaluated.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">How Public Adjusters and Attorneys Use ESX Files to Challenge Estimates</h2>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Public Adjuster&apos;s Workflow</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        For a public adjuster, the carrier&apos;s ESX file is the starting point of every claim analysis. When a policyholder hires a public adjuster after receiving an estimate they believe is too low, the first thing the public adjuster does is request the ESX file.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        With the ESX file in hand, the public adjuster can import it into their own copy of Xactimate and perform a line-by-line comparison. They can identify every setting that was used, every line item that was included or omitted, every price that was modified, and every assumption that affected the total. They can then create their own estimate using the same software, the correct settings, the current price list, and the full scope of repairs &mdash; and present a side-by-side comparison that quantifies the exact dollar impact of every discrepancy.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This is far more effective than simply submitting a competing estimate and arguing over the bottom line. When a public adjuster can point to the specific settings and decisions that caused the underpayment &mdash; &quot;Your adjuster used rebuild labor efficiency on a restoration project, which reduced every labor line item by approximately twenty percent&quot; &mdash; the carrier&apos;s adjuster is no longer defending a number. They are defending a choice. And when the choice is indefensible, the negotiation moves in the policyholder&apos;s favor.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        For a broader discussion of the differences between <Link href="/resources/estimate-bid-invoice-xactimate" className="text-[#2E74B5] underline">estimates, bids, and invoices in Xactimate</Link>, and how each functions in the claims process, see our dedicated article on that topic.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The Attorney&apos;s Use of ESX Files in Litigation</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        In insurance litigation, the ESX file is a powerful evidentiary tool. Attorneys use ESX files to:
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>Demonstrate systematic underpayment.</strong> By analyzing the ESX files across multiple claims, attorneys can establish patterns of conduct &mdash; such as the consistent use of inappropriate labor efficiency settings or the systematic exclusion of O&amp;P &mdash; that support claims of bad faith or unfair claims practices.</li>
        <li><strong>Impeach adjuster testimony.</strong> When a carrier&apos;s adjuster testifies that they conducted a thorough investigation and prepared a fair estimate, the ESX file provides the cross-examination material. If the adjuster claims the estimate was comprehensive but the ESX file shows fifty line items were user-modified downward, the file speaks for itself.</li>
        <li><strong>Calculate damages.</strong> The ESX file allows an expert witness to quantify the exact dollar impact of each improper setting or decision. This is far more persuasive than a competing estimate, because it uses the carrier&apos;s own data as the starting point.</li>
        <li><strong>Support expert opinions.</strong> Estimating experts retained by plaintiff attorneys rely on ESX files to form opinions about the reasonableness of the carrier&apos;s estimate. The ESX file provides the objective, verifiable data that supports or contradicts the carrier&apos;s position.</li>
        <li><strong>Establish the standard of care.</strong> By comparing the carrier&apos;s ESX file settings against <Link href="/resources/how-to-read-verisk-white-paper" className="text-[#2E74B5] underline">Verisk&apos;s own documentation</Link> about how those settings should be used, attorneys can demonstrate that the carrier departed from the software manufacturer&apos;s intended use &mdash; a powerful argument in any dispute about estimating methodology.</li>
      </ul>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Class Action and Pattern Evidence</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        ESX files have become central to class action lawsuits alleging systematic underpayment by major carriers. Because the ESX file records every global setting, a plaintiff&apos;s attorney who obtains ESX files from hundreds or thousands of claims can analyze them for patterns. Did the carrier use the wrong labor efficiency setting on a significant percentage of its partial-loss claims? Did the carrier systematically exclude O&amp;P on claims involving multiple trades? Did the carrier use outdated price lists on claims that were delayed for months?
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        These patterns are difficult to establish from PDFs alone because the PDFs do not consistently display the settings information. The ESX file makes pattern analysis possible, and pattern analysis is what transforms an individual claim dispute into a systemic practice allegation.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">The Xactimate EULA and What It Says About Sharing Files</h2>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">The EULA Argument</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Carriers occasionally cite the Xactimate End User License Agreement (EULA) as a basis for refusing to share ESX files. The argument generally takes the form: &quot;The EULA restricts how we can share files produced by the software, so we cannot provide the ESX file.&quot;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This argument has significant limitations and should not be accepted at face value.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Software vs. Data</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The Xactimate EULA governs the use of the software &mdash; the application itself, its code, and its proprietary database. It does not give the carrier ownership of the data that is entered into the software by the carrier&apos;s own adjusters using information from the policyholder&apos;s own property. The ESX file contains data about the policyholder&apos;s property, the policyholder&apos;s claim, and the carrier&apos;s evaluation of that claim. That data is not a trade secret of Verisk, and the EULA does not override the carrier&apos;s regulatory and contractual obligations to the policyholder.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Consider the analogy: Microsoft Word has a EULA. But no one argues that a letter written in Microsoft Word cannot be shared because of Microsoft&apos;s license agreement. The EULA governs your right to use the software. It does not give Microsoft ownership of every document you create with it. The same principle applies to Xactimate and ESX files.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Xactimate Was Designed for File Sharing</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Verisk has not taken the position that ESX files cannot be shared with policyholders or their representatives. To the contrary, Xactimate is designed to facilitate the exchange of estimating data between parties. The ability to import and export ESX files is a core feature of the software, not an afterthought. The platform was built with the expectation that estimates would be shared, reviewed, and compared by multiple parties &mdash; carriers, independent adjusters, public adjusters, contractors, and appraisers all exchange ESX files as a routine part of the claims process.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The entire XactAnalysis ecosystem is built around the premise that estimates flow between parties. Carriers assign estimates to field adjusters, field adjusters submit estimates to desk reviewers, desk reviewers send estimates to managers, and at every step the file is being shared. The EULA does not prohibit any of this. The notion that the same EULA prohibits sharing the file with the person whose property the estimate is about strains credibility.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">EULA vs. Regulatory Obligation</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Even if the EULA contained an explicit prohibition on sharing ESX files with policyholders &mdash; which it does not, in any version publicly discussed in the industry &mdash; a private software license agreement cannot override state insurance regulations. The carrier&apos;s obligations under the insurance code and fair claims settlement regulations are matters of public law. A carrier cannot contract its way out of its regulatory duties by agreeing to a software vendor&apos;s terms of service.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        If a carrier argues that its EULA prevents it from sharing the ESX file, the appropriate response is: &quot;Please provide the specific EULA provision you are relying on, and explain how a private licensing agreement supersedes your obligations under the California Insurance Code to provide claim-related documents to the policyholder upon request.&quot;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        In practice, when carriers are pressed on this point, the EULA argument tends to evaporate. It is an excuse, not a legal position.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">Practical Considerations</h2>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">You Need Xactimate to Open the File</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        An ESX file can only be fully analyzed in Xactimate. The software is available through subscription from Verisk, and it is not inexpensive. Most individual policyholders do not have Xactimate and should not need to purchase it for a single claim. This is one of the primary reasons to work with a public adjuster or an estimating consultant who has a current Xactimate license and the expertise to analyze the file.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Attorneys handling insurance litigation typically retain estimating experts who have Xactimate licenses and can analyze ESX files, prepare competing estimates, and testify about their findings. The cost of retaining an expert to analyze an ESX file is modest relative to the potential recovery on an underpaid claim.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Note that because the ESX file is technically a ZIP-compressed archive, a technically proficient person can rename the file extension and extract its contents to view the raw data in XML format. This approach can reveal certain settings &mdash; such as the price list version or labor efficiency selection &mdash; without a full Xactimate license. However, for a comprehensive analysis that includes line-by-line review, scope comparison, and estimate correction, access to Xactimate itself is necessary.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Version Compatibility</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate has gone through multiple major versions over the years, including desktop versions (Xactimate 27, 28) and the current cloud-based version (Xactimate online, sometimes called XactAnalysis). ESX files created in one version may not open correctly in another version without conversion. When requesting the ESX file, it is helpful to specify that you need the file in a format compatible with the current version of Xactimate. If the carrier created the estimate in an older version, ask them to provide the file in both the original format and a converted format.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">Multiple Versions of the Estimate</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Claims frequently involve multiple versions of the estimate &mdash; the original estimate, one or more supplements, and sometimes a revised estimate after reinspection. Each version exists as a separate ESX file or as a revision within the claims management system. When requesting the ESX file, request all versions, including any supplements, revisions, or internal working copies. Comparing the versions can reveal what changed between iterations and why &mdash; information that is invaluable when evaluating the fairness of the final estimate.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">What to Do Right Now</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        If you have received a Xactimate estimate from your insurance carrier and have not received the ESX file, take the following steps:
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>Request the ESX file in writing immediately.</strong> Use the sample language provided above. Be specific about what you are requesting. Send the request by email and keep a copy of everything.</li>
        <li><strong>Do not accept the estimate at face value.</strong> A PDF estimate is a starting point for evaluation, not a final determination. Until you or your representative have reviewed the ESX file and verified the settings, the estimate has not been fully evaluated.</li>
        <li><strong>Engage a professional.</strong> If you believe the estimate is too low, consult a public adjuster or an attorney experienced in insurance claims. They have the tools, the expertise, and the leverage to obtain and analyze the ESX file and to <Link href="/resources/how-to-challenge-xactimate-estimate" className="text-[#2E74B5] underline">challenge the estimate</Link> based on what they find.</li>
        <li><strong>Document everything.</strong> Keep records of every communication with the carrier. If the carrier delays or refuses your request for the ESX file, those records become evidence of how the claim was handled.</li>
        <li><strong>Know your rights.</strong> You are not asking for a favor. You are asking for a document that was created using your property information, under your insurance policy, to evaluate your claim. The carrier has an obligation to provide the documentation necessary for you to evaluate the fairness of its determination.</li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">The Bigger Picture</h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        The question of ESX file access is ultimately a question about information and accountability. When one party to a transaction controls all the information and the other party receives only a summary, the informed party controls the outcome. This dynamic is not unique to insurance &mdash; it exists in medicine, in law, in finance, and in every field where professionals use specialized tools to generate the numbers that determine outcomes for the people they serve.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        But in insurance, the stakes are unusually high. A homeowner whose property has been damaged by fire, water, or storm is not shopping for a product. They are exercising a contractual right they have been paying for, sometimes for decades. The estimate that determines their payment is not a casual offer. It is a representation of what the carrier believes it owes under the policy. And the policyholder has every right to examine the basis for that representation &mdash; not the summary, not the printout, but the actual data.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        A carrier that uses the correct settings, the current price list, and a comprehensive scope has nothing to fear from providing the ESX file. The estimate will stand on its own merits. The carriers that resist are the carriers whose estimates do not withstand scrutiny when the underlying data is exposed.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The ESX file is that data. Ask for it. Insist on it. And when you get it, have it reviewed by someone who knows what to look for.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        For more information on understanding and challenging Xactimate estimates, explore our articles on <Link href="/resources/xactimate" className="text-[#2E74B5] underline">Xactimate overview</Link>, <Link href="/resources/xactimate-labor-efficiency-settings" className="text-[#2E74B5] underline">labor efficiency settings</Link>, <Link href="/resources/xactimate-price-list-dates" className="text-[#2E74B5] underline">price list dates</Link>, <Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">overhead and profit</Link>, <Link href="/resources/how-to-challenge-xactimate-estimate" className="text-[#2E74B5] underline">how to challenge a Xactimate estimate</Link>, and <Link href="/resources/how-to-read-verisk-white-paper" className="text-[#2E74B5] underline">how to read Verisk&apos;s documentation</Link>.
      </p>
      <hr className="my-8 border-gray-300" />
      <p className="text-sm text-gray-500 italic">
        This article is for informational purposes only and does not constitute legal advice.
        Insurance policies and applicable law vary by state and by policy form. Consult with a
        licensed professional regarding your specific situation.
      </p>
      <p className="text-sm text-gray-500 mt-4 italic">
        Written by Leland Coontz III, Licensed Public Adjuster, CA License #2B53445.
      </p>
    </>
  )
}
