import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: "Games Insurers Play: When the Claims Process Meets the Worst Day of Your Life",
  description:
    "How the insurance claims machine produces outcomes that compound trauma — not through malice, but through a system that wasn't designed for grief. What happens when a routine claims process meets a family in crisis.",
}

export default function Content() {
  return (
    <>
      <p className="text-gray-700 leading-relaxed mb-4">
        There is a moment &mdash; and every family who has lived through it knows exactly the one I
        mean &mdash; when the last official vehicle pulls away from the house. The police have
        finished their report. The medical examiner has done what they came to do. The chaplain, if
        one was offered, has said their piece. And then there is silence.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The family stands in the driveway, or the hallway, or the kitchen, and realizes that
        everything that happens next is on them. The scene inside the home has not been cleaned. The
        physical aftermath of what happened &mdash; the biological contamination, the staining, the
        odor &mdash; remains exactly as it was. And there is no public agency, no government program,
        no automatic dispatch that handles what comes next.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        What comes next is an insurance claim.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This article is about what happens when that claim enters the system &mdash; the same system
        that processes kitchen fires and burst pipes and hail damage to roofs. The same forms. The
        same timelines. The same letters. The same adjuster who handled fourteen other claims that
        week. The claims process was not designed for this. And because it was not designed for this,
        it produces outcomes that compound the very trauma that created the claim in the first place.
      </p>

      {/* ── The Gap Nobody Talks About ──────────────────────────────── */}

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4 mt-10">
        The Gap Nobody Talks About
      </h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        Our emergency response system is remarkably well-coordinated &mdash; up to a point. Police
        secure the scene. EMTs transport the injured or confirm the deceased. The medical examiner
        collects evidence. Detectives investigate. Victim advocates may be dispatched. The system
        works the way it was designed to work.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Then everyone leaves.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        No public agency handles the physical aftermath of a violent death, a suicide, or an
        unattended death in a residence. There is no government-funded cleanup crew. There is no
        automatic referral to a{' '}
        <Link href="/resources/biohazard-hazmat-trauma-cleanup" className="text-[#2E74B5] hover:underline">
          certified biohazard remediation company
        </Link>. The family is expected to figure that out themselves &mdash; while simultaneously
        planning a funeral, notifying relatives, dealing with law enforcement follow-ups, and
        beginning to process what is often the most devastating event of their lives.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        And somewhere in those first 24 to 72 hours, they also need to call their insurance company.
        Because the home has sustained damage. Because the contamination is spreading. Because every
        hour that passes makes the remediation more extensive and more expensive. Because the policy
        has reporting requirements.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        So a person who just lost someone they love &mdash; who may have been the one to discover
        the body, who may still be unable to enter certain rooms of their own home &mdash; picks up
        the phone and calls a 1-800 number.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        And the machine turns on.
      </p>

      {/* ── The Machine Doesn't Modulate ────────────────────────────── */}

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4 mt-10">
        The Machine Doesn&rsquo;t Modulate
      </h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        Here is the thing about the claims process that nobody explains to families in crisis: it
        runs the same way for every claim. The same intake questions. The same contact timelines.
        The same documentation requirements. The same form letters generated by the same software.
        Whether the claim involves a grease fire in a kitchen or a father who took his own life in
        the master bedroom, the process does not modulate.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        This is not because the people inside the system are heartless. Most adjusters are ordinary
        people doing a difficult job. But they handle hundreds of claims per year. Professional
        distance isn&rsquo;t cruelty &mdash; it&rsquo;s a survival mechanism. After enough years,
        every claim begins to look like every other claim. The emotional register flattens.
        The process becomes routine because routine is the only way to get through the volume.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        So the adjuster who sends a reservation of rights letter three days after a family
        discovers their father&rsquo;s body in the garage is not being deliberately cruel. They are
        following a procedure. The system told them to send the letter. The system does not have a
        setting for &ldquo;the insured is currently unable to function.&rdquo; The system does not
        have a checkbox for &ldquo;delay standard correspondence because the policyholder&rsquo;s
        children found the body.&rdquo;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The system doesn&rsquo;t modulate for human suffering. It wasn&rsquo;t built to. And because
        it wasn&rsquo;t built to, it produces outcomes that look &mdash; from the family&rsquo;s
        perspective &mdash; indistinguishable from cruelty.
      </p>

      <CalloutBox variant="important" title="The Core Problem">
        <p>
          The insurance claims process applies the same procedures, timelines, and documentation
          demands to a trauma-related loss as it does to a routine property claim. There is no
          grief protocol. There is no modified timeline. There is no human override. The system
          runs the same way regardless of what the family is going through.
        </p>
      </CalloutBox>

      {/* ── What the Process Looks Like for a Grieving Family ───────── */}

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4 mt-10">
        What the Process Looks Like for a Grieving Family
      </h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        Let me walk you through what actually happens. Not in theory. Not in a training manual. What
        the process feels like from the family&rsquo;s side.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3 mt-6">Days 1 Through 3</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The death happens. Law enforcement arrives. The medical examiner does their work. The family
        is told the scene will be released to them &mdash; meaning the home, with whatever
        biological contamination remains, is now their responsibility. They need to find a{' '}
        <Link href="/resources/biohazard-hazmat-trauma-cleanup" className="text-[#2E74B5] hover:underline">
          trauma cleanup company
        </Link>{' '}
        while they are still in shock. They need to figure out whether their homeowner&rsquo;s
        insurance covers any of this. They need to call the insurance company, which means
        explaining what happened to a stranger over the phone.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        While they are doing this, they are also making funeral arrangements. Calling family
        members. Possibly talking to detectives. Possibly dealing with media if the death was
        violent. The children may be staying elsewhere because the home is not habitable. Nobody is
        sleeping. Nobody is eating. Nobody is thinking clearly.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The insurance company&rsquo;s clock is already running.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3 mt-6">The Recorded Statement</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Within days &mdash; sometimes the very next day &mdash; the adjuster calls to schedule a{' '}
        <Link href="/resources/recorded-statements-siu" className="text-[#2E74B5] hover:underline">
          recorded statement
        </Link>. This is standard procedure for any claim. The adjuster needs to understand what
        happened. But &ldquo;what happened&rdquo; in this context means asking a widow to describe,
        on the record, the circumstances of her husband&rsquo;s death. It means asking a son to
        recount finding his father. It means clinical questions &mdash; &ldquo;Was the death sudden
        and accidental?&rdquo; &ldquo;Can you describe the condition of the room?&rdquo; &mdash;
        asked by someone who needs the information for a file, not for comfort.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The request arrives while the family is writing a eulogy.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3 mt-6">The Documentation Demands</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Then come the letters. Please provide a complete inventory of contaminated personal property
        with replacement values. Please document all affected areas with photographs. Please obtain
        estimates from licensed contractors. Please provide receipts for emergency cleanup
        expenditures.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The same{' '}
        <Link href="/resources/contents-claims" className="text-[#2E74B5] hover:underline">
          personal property inventory
        </Link>{' '}
        process that applies to a house fire applies here. Except instead of listing smoke-damaged
        furniture, the family is being asked to catalog their dead parent&rsquo;s contaminated
        belongings. The mattress. The bedding. The carpet. The personal items in the room where it
        happened. Each one with a description and a dollar value.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Think about what that means for a moment. Think about sitting at a kitchen table with a
        spreadsheet, trying to assign a replacement cost to items that are now associated with the
        worst moment of your life.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3 mt-6">The Coverage Letter</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The reservation of rights letter arrives. It is written in legalese. It references policy
        provisions, exclusions, and conditions. It may reference the{' '}
        <Link href="/resources/pollution-exclusion-claims" className="text-[#2E74B5] hover:underline">
          pollution exclusion
        </Link>{' '}
        &mdash; the provision that some carriers have used to classify biological contamination
        from a human death as a &ldquo;pollutant.&rdquo; It may question whether the loss
        constitutes a &ldquo;covered peril.&rdquo; It may invoke mold sub-limits if secondary
        contamination is present.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The family reads the letter. Or tries to. Most of it is incomprehensible to anyone who
        isn&rsquo;t an insurance professional or an attorney. But certain phrases land with
        devastating clarity: &ldquo;We are investigating whether coverage applies to your
        claim.&rdquo; &ldquo;This letter does not constitute a denial.&rdquo; &ldquo;We reserve
        all rights under the policy.&rdquo;
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The family is now grieving, planning a funeral, living in temporary housing, and wondering
        whether their insurance company is going to pay for any of this.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3 mt-6">The Coverage Denial</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        In some cases, the denial arrives. The carrier takes the position that biological
        contamination from a death is not a covered peril, or that the{' '}
        <Link href="/resources/pollution-exclusion-claims" className="text-[#2E74B5] hover:underline">
          pollution exclusion
        </Link>{' '}
        applies, or that the loss does not meet the policy&rsquo;s definition of &ldquo;sudden and
        accidental.&rdquo; A family that has just lost someone receives a letter telling them that
        their loved one&rsquo;s bodily fluids are classified as &ldquo;pollutants&rdquo; under
        the terms of their homeowner&rsquo;s policy.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Read that sentence again. That is what the process produces.
      </p>

      {/* ── The Patterns ────────────────────────────────────────────── */}

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4 mt-10">
        The Patterns
      </h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        Across these claims, certain patterns emerge. They are not unique to trauma claims &mdash;
        they show up in every type of property loss. But in the context of a grieving family, their
        effects are magnified beyond anything the system was calibrated for.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3 mt-6">Speed</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        Settlement offers arrive before the family has had time to understand the scope of the
        claim. A{' '}
        <Link href="/resources/first-offer-lowball" className="text-[#2E74B5] hover:underline">
          first offer
        </Link>{' '}
        may land within weeks &mdash; not because the carrier is rushing to take advantage of a
        vulnerable family, but because the process has standard timelines. The adjuster has a
        caseload. The file needs to move. The offer reflects whatever limited information was
        available at the time, which in a trauma claim is almost always incomplete.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        But a family in crisis does not have the bandwidth to evaluate whether an offer is
        reasonable. They see a number. They want the nightmare to be over. And so they accept.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3 mt-6">The Documentation Burden</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The same inventory requirements apply whether you are documenting a remodeled kitchen or
        a dead parent&rsquo;s contaminated belongings. The system requires itemized lists.
        Photographs. Replacement values. Proof of ownership. The process doesn&rsquo;t know the
        difference between a sofa ruined by smoke and a sofa ruined by decomposition. It needs
        the same form filled out either way.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Families abandon portions of their{' '}
        <Link href="/resources/contents-claims" className="text-[#2E74B5] hover:underline">
          contents claims
        </Link>{' '}
        because the process of inventorying a deceased person&rsquo;s belongings &mdash; one item
        at a time, with dollar values &mdash; is more than they can bear.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3 mt-6">Coverage Arguments</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The{' '}
        <Link href="/resources/pollution-exclusion-claims" className="text-[#2E74B5] hover:underline">
          pollution exclusion
        </Link>. The &ldquo;not a covered peril&rdquo; argument. The mold sub-limit applied to
        secondary biological growth. These are standard coverage positions that adjusters and
        coverage counsel apply across all claim types. In a kitchen fire, they are frustrating.
        In an{' '}
        <Link href="/resources/unattended-death-claims" className="text-[#2E74B5] hover:underline">
          unattended death claim
        </Link>, they are devastating &mdash; because the &ldquo;pollutant&rdquo; being excluded is
        a family member.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        The coverage arguments are applied mechanically, without consideration for context, because
        the system does not have a mechanism for considering context. The same exclusionary language
        is cited. The same form letters are sent. The same standard applies.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3 mt-6">The Initial Offer</h3>

      <p className="text-gray-700 leading-relaxed mb-4">
        The{' '}
        <Link href="/resources/first-offer-lowball" className="text-[#2E74B5] hover:underline">
          first offer
        </Link>{' '}
        reflects the adjuster&rsquo;s limited scope, not the full cost of remediation and
        restoration. It may not account for the full extent of structural remediation. It
        may not include{' '}
        <Link href="/resources/ale-frv" className="text-[#2E74B5] hover:underline">
          additional living expenses
        </Link>{' '}
        for the months the home will be uninhabitable. It almost certainly undervalues the
        personal property loss because the family hasn&rsquo;t had the capacity to produce a
        complete inventory.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        In a routine claim, this is the starting point for negotiation. In a trauma claim, it is
        often the ending point &mdash; because the family does not have the emotional resources
        to fight.
      </p>

      {/* ── Why This Matters for the Claim Outcome ──────────────────── */}

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4 mt-10">
        Why This Matters for the Claim Outcome
      </h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        The collision between grief and the claims process produces predictable, measurable harm
        to the claim itself. This is not speculation. These are the patterns I see in every
        trauma-related property claim that comes to me after the family has tried to handle it
        alone:
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>Lower settlements.</strong> Families in crisis accept the first offer because they
          lack the bandwidth to evaluate it, negotiate, or dispute it. They want the process to end.
        </li>
        <li>
          <strong>Incomplete documentation.</strong> The personal property inventory is partial
          because the family couldn&rsquo;t bring themselves to catalog every contaminated item.
          The photographs are insufficient because nobody wanted to spend more time in those rooms
          than necessary.
        </li>
        <li>
          <strong>Unclaimed benefits.</strong>{' '}
          <Link href="/resources/ale-frv" className="text-[#2E74B5] hover:underline">
            Additional living expenses
          </Link>{' '}
          go unclaimed because nobody told the family they were entitled to them, or because the
          family didn&rsquo;t have the capacity to track receipts and submit the required
          documentation.
        </li>
        <li>
          <strong>Statute of limitations exposure.</strong> The{' '}
          <Link href="/resources/california-claim-deadlines" className="text-[#2E74B5] hover:underline">
            statute of limitations
          </Link>{' '}
          runs while the family is still processing their loss. Months pass. Sometimes years. By the
          time they realize the settlement was inadequate, it may be too late to do anything about it.
        </li>
        <li>
          <strong>Abandoned claims.</strong> Personal property claims are partially or entirely
          abandoned because inventorying a deceased person&rsquo;s contaminated belongings is simply
          too painful. The family writes off thousands of dollars in legitimate coverage because the
          process of claiming it requires reliving the trauma.
        </li>
      </ul>

      <p className="text-gray-700 leading-relaxed mb-4">
        Every one of these outcomes benefits the carrier&rsquo;s bottom line. I am not saying that
        is the intent. I am saying that is the result. And the system has no mechanism to correct
        for it.
      </p>

      {/* ── The Solution: Someone Else Handles the Machine ──────────── */}

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4 mt-10">
        The Solution: Someone Else Handles the Machine
      </h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        The answer is not that the carrier is evil and needs to be punished. The answer is that the
        process requires a level of engagement, attention, and technical knowledge that a person in
        crisis cannot reasonably provide. The solution is professional representation &mdash; not as
        a weapon, but as a buffer between the grieving family and a system that does not know how
        to account for grief.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Here is what professional representation looks like in a trauma claim:
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          A{' '}
          <Link href="/resources/public-adjuster" className="text-[#2E74B5] hover:underline">
            public adjuster
          </Link>{' '}
          reads the reservation of rights letters, responds to documentation demands, coordinates
          with the remediation company, and documents the full scope of the loss. The family does
          not have to read a single piece of insurance correspondence.
        </li>
        <li>
          An attorney evaluates the coverage position if the claim is denied or if the carrier
          invokes the{' '}
          <Link href="/resources/pollution-exclusion-claims" className="text-[#2E74B5] hover:underline">
            pollution exclusion
          </Link>{' '}
          or other exclusionary language. The attorney knows whether the denial is legally
          defensible. The family does not have to figure that out on their own.
        </li>
        <li>
          A certified industrial hygienist (CIH) documents the contamination &mdash; the extent,
          the affected materials, the required remediation protocol &mdash; so the family does not
          have to re-enter the affected areas to take photographs or measurements.
        </li>
        <li>
          A{' '}
          <Link href="/resources/biohazard-hazmat-trauma-cleanup" className="text-[#2E74B5] hover:underline">
            certified biohazard remediation company
          </Link>{' '}
          handles the physical cleanup according to OSHA and ANSI/IICRC standards, providing the
          documentation the claim requires as part of their standard protocol.
        </li>
      </ul>

      <p className="text-gray-700 leading-relaxed mb-4">
        The professionals handle the machine. The family handles their grief. These are two separate
        processes, and they should not be forced to happen simultaneously by the same people.
      </p>

      <CalloutBox variant="tip" title="What This Looks Like in Practice">
        <p>
          When a family retains a public adjuster on a trauma claim, the adjuster becomes the point
          of contact for the carrier. The adjuster receives the letters, responds to the deadlines,
          coordinates the experts, and builds the claim. The family&rsquo;s only role is to approve
          decisions and sign documents. Everything else &mdash; every phone call, every form, every
          coverage argument &mdash; is handled by someone who is not in crisis.
        </p>
      </CalloutBox>

      {/* ── What California Law Provides ────────────────────────────── */}

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4 mt-10">
        What California Law Provides
      </h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        California law does not have a &ldquo;grief exception&rdquo; to the claims process. But it
        does provide legal remedies when the carrier&rsquo;s handling of a claim falls below the
        standard of reasonable conduct &mdash; and those remedies are particularly powerful in the
        context of trauma claims.
      </p>

      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>
            <Link href="/resources/bad-faith" className="text-[#2E74B5] hover:underline">
              Bad faith remedies
            </Link>
          </strong>{' '}
          apply when the carrier fails to conduct a thorough investigation, unreasonably delays the
          claim, or denies coverage without a proper basis. In a trauma claim, the bar for what
          constitutes &ldquo;reasonable&rdquo; handling is arguably higher, because the consequences
          of unreasonable conduct are more severe.
        </li>
        <li>
          <strong>Emotional distress damages</strong> are available in bad faith actions &mdash; and
          in trauma claim contexts, those damages can be substantial. A jury evaluating a carrier&rsquo;s
          conduct toward a grieving family is evaluating that conduct against the backdrop of
          extraordinary vulnerability.
        </li>
        <li>
          <strong>
            <Link href="/resources/brandt-fees" className="text-[#2E74B5] hover:underline">
              Brandt fees
            </Link>
          </strong>{' '}
          allow recovery of attorney fees incurred to obtain the benefits that were owed under
          the policy. If the family had to hire an attorney to fight a wrongful denial on a trauma
          claim, those legal costs are recoverable.
        </li>
        <li>
          <strong>
            <Link href="/resources/california-fair-claims" className="text-[#2E74B5] hover:underline">
              Fair Claims Settlement Practices Regulations
            </Link>
          </strong>{' '}
          impose specific duties on the carrier: to thoroughly investigate, to respond within
          regulatory timeframes, to not unreasonably delay or deny, and to communicate clearly with
          the insured. These duties do not have an exception for claims that are emotionally
          complicated. The carrier must comply regardless.
        </li>
      </ul>

      <p className="text-gray-700 leading-relaxed mb-4">
        The practical significance is this: a carrier that sends a mechanical denial on a trauma
        claim, fails to investigate the coverage question thoroughly, or delays handling while a
        family is in crisis may be exposing itself to liability that far exceeds the cost of the
        claim itself. The law provides remedies precisely because the consequences of improper
        handling are not limited to the dollar value of the property loss.
      </p>

      {/* ── Closing ─────────────────────────────────────────────────── */}

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4 mt-10">
        The System Was Not Designed for This
      </h2>

      <p className="text-gray-700 leading-relaxed mb-4">
        I want to be clear about what this article is saying and what it is not. I am not saying
        that insurance companies set out to harm grieving families. I am not saying that individual
        adjusters are callous or malicious. Most of them are doing a job the best way they know how,
        inside a system that does not give them the tools or the authority to handle these situations
        differently.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        What I am saying is that the system produces harmful outcomes in these cases &mdash;
        consistently, predictably, and measurably. Lower settlements. Abandoned claims.
        Compounded trauma. These are not edge cases or exceptions. They are the natural result
        of applying a standardized process to a situation that is anything but standard.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        If you are a family going through this right now, the single most important thing you can
        do is get someone between you and the process. A{' '}
        <Link href="/resources/public-adjuster" className="text-[#2E74B5] hover:underline">
          public adjuster
        </Link>. An attorney. Someone who can read the letters, respond to the deadlines, and fight
        the coverage battles while you take care of your family. The process will not slow down
        for you. It will not soften its language. It will not wait until you are ready.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        But you do not have to face it alone. And you should not.
      </p>

      <CalloutBox variant="info" title="For Detailed Coverage Analysis">
        <p>
          This article describes the human experience of navigating a trauma claim. For the
          technical coverage analysis &mdash; including how the pollution exclusion applies,
          what California courts have said about coverage for biological contamination, and the
          specific documentation and remediation requirements &mdash; see our detailed guides on{' '}
          <Link href="/resources/unattended-death-claims" className="text-[#2E74B5] hover:underline">
            unattended death claims
          </Link>{' '}
          and{' '}
          <Link href="/resources/biohazard-hazmat-trauma-cleanup" className="text-[#2E74B5] hover:underline">
            biohazard and trauma cleanup coverage
          </Link>.
        </p>
      </CalloutBox>

      <p className="text-sm text-gray-500 italic mt-8">
        Leland Coontz is a California Licensed Public Adjuster and the founder of
        InsuranceClaimsInfo.com. He has decades of experience advocating for policyholders on both
        sides of the insurance claims process. The scenarios described in this article are composites
        based on real claims with identifying details changed. This article is for informational
        purposes and does not constitute legal advice. Policyholders facing claim disputes should
        consult with a qualified attorney in their jurisdiction.
      </p>
    </>
  )
}
