import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: 'How to Read Your Xactimate Estimate: A Consumer-Friendly Line-by-Line Guide',
  description:
    'Learn how to read and understand every section of your Xactimate insurance estimate, from the header and line items to the summary page, so you can spot missing items and underpayments.',
  summary:
    'An Xactimate estimate has a header, line items, and a summary page. Reading each section, the quantities, unit prices, depreciation, and totals, lets you spot missing items and underpayments the carrier hopes you overlook.',
}

export default function Content() {
  return (
    <>
      <CalloutBox variant="legal" title="This Article Is Not Legal Advice">
        <p>
          This article is educational commentary by a Licensed California Public
          Adjuster. It is not legal advice. For legal questions about your specific
          situation, consult a licensed California attorney.
        </p>
      </CalloutBox>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What You&apos;re Looking At
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        If you have filed a homeowners insurance claim, your insurance company will almost
        certainly send you a document that looks like a spreadsheet full of codes, abbreviations,
        and numbers. This document is an Xactimate estimate &mdash; and understanding it is one of
        the most important things you can do to protect yourself during the claims process.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        <Link href="/resources/xactimate" className="text-[#2E74B5] underline">Xactimate</Link> is
        a software program developed by Verisk Analytics that has become the insurance
        industry&apos;s standard tool for estimating the cost of property repairs. When your
        adjuster inspects your home and then sends you &quot;the estimate,&quot; what you receive
        is a PDF printout generated by this software. Every line on that document represents a
        specific repair task with specific pricing &mdash; a unit of work, a quantity, and a
        dollar amount.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The problem is that Xactimate estimates are designed to be read by insurance professionals,
        not homeowners. The abbreviations are cryptic. The structure is unfamiliar. And the sheer
        volume of line items can be overwhelming. Many policyholders glance at the bottom-line
        number, compare it to their deductible, and never look further. That is exactly what an
        underpaying carrier is counting on.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This guide will walk you through an Xactimate estimate section by section, explain what
        every column means, and show you what to look for so you can determine whether the
        estimate is fair or whether important items have been left out.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Header Section
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The top of your Xactimate estimate contains identifying information about your claim.
        While this may seem like routine paperwork, several of these fields have direct
        financial consequences that most policyholders overlook.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Insured Name and Property Address
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Your name and the address of the damaged property will appear at the top. Verify that
        these are correct. Errors in the property address can occasionally indicate that the
        adjuster confused your file with another claim &mdash; it happens more often than you
        might think, especially during catastrophe events when adjusters are handling dozens
        of claims simultaneously.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Claim Number and Date of Loss
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The claim number is your insurance company&apos;s internal tracking number. The date
        of loss is the date the damage occurred. Make sure the date of loss is correct, because
        it affects which policy provisions apply and can influence
        your{' '}
        <Link href="/resources/california-claim-deadlines" className="text-[#2E74B5] underline">
          claim deadlines
        </Link>.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Price List Date and Region
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        This is one of the most important &mdash; and most frequently manipulated &mdash; fields
        on the entire estimate. Xactimate maintains databases of labor and material prices that
        are updated monthly for each geographic region. The &quot;price list&quot; field tells you
        which month&apos;s prices and which geographic area the adjuster used when building
        your estimate.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Why does this matter? Because construction costs change over time, and they vary
        significantly by location. If your loss occurred in June 2025 in Los Angeles, but the
        adjuster used a price list from January 2024 in a less expensive neighboring region,
        every single line item on your estimate will be priced lower than it should be. The
        effect compounds across the entire estimate &mdash; a stale or mismatched price list
        can reduce a claim by thousands of dollars without changing a single line item.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        For a deeper dive into how{' '}
        <Link href="/resources/xactimate-price-list-dates" className="text-[#2E74B5] underline">
          price list dates affect your claim
        </Link>, see our dedicated article on the topic. The key takeaway: always check that the
        price list date is current and that the region matches your property&apos;s actual location.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Type of Estimate
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Some estimates will indicate whether they are an Actual Cash Value (ACV) or Replacement
        Cost Value (RCV) estimate. If the header says &quot;ACV,&quot; the insurer has already
        subtracted depreciation from the totals. If it says &quot;RCV,&quot; the totals reflect
        the full cost of repairs before depreciation. Understanding the difference between{' '}
        <Link href="/resources/acv-rcv" className="text-[#2E74B5] underline">
          ACV and RCV
        </Link>{' '}
        is essential to evaluating whether your payment is correct.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Room and Area Structure
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate estimates are organized by room or area. Each section of your home that has
        damage will have its own grouping of line items. You will see headers like
        &quot;Kitchen,&quot; &quot;Master Bedroom,&quot; &quot;Hall Bath,&quot;
        &quot;Exterior,&quot; &quot;Roof,&quot; &quot;Garage,&quot; or similar labels.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Within each room section, the estimate lists every repair task that the adjuster believes
        is necessary for that specific area. For example, the &quot;Kitchen&quot; section might
        include line items for removing and replacing drywall, painting, removing and resetting
        appliances, replacing flooring, and so on.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This room-by-room structure is important because it allows you to compare the estimate
        against your actual home. Walk through your property with the estimate in hand and ask
        yourself: is every damaged room listed? Are all the damaged components within each room
        accounted for? One of the most common shortcomings in carrier estimates is the
        complete omission of entire rooms or areas that sustained damage.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        You may also see sections labeled &quot;General&quot; or &quot;General Conditions.&quot;
        These sections contain items that apply to the project as a whole rather than to a
        specific room &mdash; things like dumpster rental, building permits, final cleaning,
        or general demolition. If these sections are missing from your estimate, that is worth
        investigating.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Anatomy of a Line Item
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Each line item in your Xactimate estimate represents a single repair task. Understanding
        how to read a line item is the key to understanding the entire estimate. Here is what
        each column means.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The Line Item Code
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Every repair task in Xactimate has a unique code &mdash; a short abbreviation that
        identifies the specific type of work. For example:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>DRY</strong> &mdash; Drywall-related items (hanging, finishing, texturing)
        </li>
        <li>
          <strong>RFC</strong> &mdash; Roofing-related items (shingles, underlayment, flashing)
        </li>
        <li>
          <strong>PNT</strong> &mdash; Painting items (prime, paint, seal)
        </li>
        <li>
          <strong>FLR</strong> &mdash; Flooring items (hardwood, carpet, tile, vinyl)
        </li>
        <li>
          <strong>PLM</strong> &mdash; Plumbing items
        </li>
        <li>
          <strong>ELC</strong> &mdash; Electrical items
        </li>
        <li>
          <strong>CLN</strong> &mdash; Cleaning items
        </li>
        <li>
          <strong>WDR</strong> &mdash; Water damage restoration items (drying equipment, moisture testing)
        </li>
        <li>
          <strong>DEM</strong> &mdash; Demolition items
        </li>
        <li>
          <strong>WND</strong> &mdash; Window items
        </li>
        <li>
          <strong>CAB</strong> &mdash; Cabinet items
        </li>
        <li>
          <strong>INS</strong> &mdash; Insulation items
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        These codes are followed by additional characters that specify the exact task. For
        instance, you might see &quot;DRY HNG&quot; for hanging drywall, &quot;DRY FIN&quot;
        for finishing (taping and mudding) drywall, or &quot;DRY TEX&quot; for applying texture.
        Each of these is a separate line item because each represents a distinct trade task
        with its own labor and material cost.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        You do not need to memorize these codes. What matters is that you understand each code
        represents a specific, defined task &mdash; and that missing codes mean missing work
        from your estimate.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The Description
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Next to the code, you will find a plain-English description of the work. This is the
        most readable column on the estimate. It will say things like &quot;Remove and replace
        drywall &mdash; 1/2 inch,&quot; &quot;Paint the ceiling &mdash; two coats,&quot;
        or &quot;Remove composition shingle roofing.&quot; Read these descriptions carefully.
        They tell you exactly what the insurer is (and is not) paying for.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Pay close attention to the difference between &quot;remove and replace&quot; (R&amp;R)
        and &quot;remove, reset, and reinstall&quot; (R&amp;I). &quot;Remove and replace&quot;
        means the existing item is being torn out and a brand-new item installed.
        &quot;Remove and reinstall&quot; means the existing item is being carefully taken out,
        set aside, and put back. These are different tasks with different costs. An insurer
        that codes an item as R&amp;I when the item was destroyed and needs full replacement
        is underpaying the claim.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Quantity and Unit of Measure
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Each line item includes a quantity and a unit of measure. The quantity tells you how
        much of the work is being estimated. The unit of measure tells you how that work is
        measured. Common units include:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>SF</strong> &mdash; Square feet. Used for drywall, painting, flooring, and
          other surface-area tasks.
        </li>
        <li>
          <strong>LF</strong> &mdash; Linear feet. Used for baseboards, crown molding, piping,
          and other linear items.
        </li>
        <li>
          <strong>SQ</strong> &mdash; A roofing &quot;square,&quot; which equals 100 square feet.
          Roofing materials and labor are measured in squares.
        </li>
        <li>
          <strong>EA</strong> &mdash; Each. Used for individual items like light fixtures, doors,
          windows, toilets, or appliances.
        </li>
        <li>
          <strong>HR</strong> &mdash; Hour. Used for labor-only tasks like cleaning, supervision,
          or specialized work billed by the hour.
        </li>
        <li>
          <strong>DA</strong> &mdash; Day. Used for equipment rental like drying fans or
          dehumidifiers.
        </li>
        <li>
          <strong>SY</strong> &mdash; Square yard. Occasionally used for carpet and some
          flooring types.
        </li>
        <li>
          <strong>BF</strong> &mdash; Board feet. Used for lumber measurements.
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        The quantities on your estimate should match the actual measurements of your home. If
        your kitchen has 200 square feet of ceiling and the estimate shows 150 SF of ceiling
        drywall, that is a 50-square-foot shortfall &mdash; and every downstream line item
        (texturing, priming, painting) that depends on that measurement will also be short.
        Measurement errors compound throughout the estimate.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This is why it is critical to have your property independently measured rather than
        relying solely on the adjuster&apos;s measurements. Even small discrepancies add up
        across an entire claim.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Unit Price
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The unit price column shows the Xactimate price for one unit of the line item. For
        example, if the line item is &quot;Paint the ceiling &mdash; two coats&quot; measured
        in SF, the unit price is the cost per square foot to perform that task, including
        both labor and material.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate prices are derived from Verisk&apos;s pricing database, which surveys
        contractors, suppliers, and labor markets in each geographic region. The prices are
        meant to reflect what a licensed, insured contractor would charge to perform that
        specific task in your area. However, the prices can be modified by the user. An
        adjuster (or the carrier&apos;s estimating guidelines) can override Xactimate&apos;s
        default prices &mdash; and some do. If you see unit prices that seem unusually low,
        you may be looking at manually reduced pricing. Our article on{' '}
        <Link href="/resources/xactimate-line-item-manipulation" className="text-[#2E74B5] underline">
          Xactimate line item manipulation
        </Link>{' '}
        covers this issue in detail.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Total
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The total column is simply the quantity multiplied by the unit price. If the line item
        is 200 SF of ceiling paint at $1.25 per SF, the total will show $250.00. This column
        is straightforward, but always worth a quick check to make sure the math is correct.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The O&amp;P Column
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        One of the most significant &mdash; and most frequently disputed &mdash; columns on
        a Xactimate estimate is the overhead and profit (O&amp;P) column. This column indicates
        whether a line item includes the general contractor&apos;s overhead (typically 10%)
        and profit (typically 10%), totaling 20% on top of the base cost of the work.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        You may see the following notations in this column:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>O&amp;P</strong> &mdash; Both overhead and profit are included on this
          line item.
        </li>
        <li>
          <strong>O</strong> &mdash; Only overhead is included; profit has been excluded.
        </li>
        <li>
          <strong>P</strong> &mdash; Only profit is included; overhead has been excluded.
        </li>
        <li>
          <strong>Blank</strong> &mdash; Neither overhead nor profit is included on this line
          item.
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        If your claim involves multiple trades (which most claims do), a general contractor
        will be needed to coordinate the work, and{' '}
        <Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">
          overhead and profit
        </Link>{' '}
        should be applied to the estimate. When you see line items marked with only &quot;O&quot;
        or only &quot;P&quot; &mdash; or no O&amp;P designation at all &mdash; that is worth
        questioning. Some carriers selectively apply O&amp;P to only certain line items as a
        way to reduce the total payout, even when the scope of work clearly requires general
        contractor coordination.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The Tax Column
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate estimates may include a column for sales tax. In most jurisdictions, sales
        tax applies to materials but not to labor. The estimate should reflect the applicable
        tax rate for your county or city. If the tax rate on the estimate does not match your
        local rate, the material costs will be understated.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Some estimates show tax as a separate line item at the end rather than in a column.
        Either way, make sure tax is being applied and that the rate is correct for your
        location.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The Depreciation Column
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        If your estimate is an Actual Cash Value (ACV) estimate &mdash; or if it shows
        depreciation being withheld from a Replacement Cost Value (RCV) estimate pending
        completion of repairs &mdash; you will see a depreciation column. This column shows
        the dollar amount being subtracted from each line item for age and wear.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Depreciation is typically calculated as a percentage of each line item&apos;s total,
        based on the estimated useful life of the component and its current age. For example,
        if a 30-year shingle roof is 10 years old, an insurer might depreciate it by 33%
        (10 years out of a 30-year life).
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        There are several things to watch for in the depreciation column:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>Depreciation applied to labor:</strong> In many states, including California,
          there are strong arguments that labor should not be depreciated because labor does not
          &quot;wear out&quot; over time &mdash; only materials age. If you see depreciation
          applied to the full line item (including the labor component), this may be inflating
          the depreciation deduction. See our article on{' '}
          <Link href="/resources/depreciation-schedules-useful-life" className="text-[#2E74B5] underline">
            depreciation schedules and useful life
          </Link>{' '}
          for more on this topic.
        </li>
        <li>
          <strong>Excessive depreciation percentages:</strong> A 5-year-old water heater being
          depreciated by 80% suggests the insurer is using an unrealistically short useful life.
          Compare the depreciation percentage against the actual condition and expected lifespan
          of the item.
        </li>
        <li>
          <strong>Depreciation on items that cannot be depreciated:</strong> Certain costs like
          demolition, debris removal, and general conditions do not age and should not be
          depreciated. If you see depreciation applied to a line item for &quot;tear out
          carpet&quot; or &quot;haul debris,&quot; that is worth questioning.
        </li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Understanding the Summary Page
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        At the end of the estimate, you will find a summary page that brings together all the
        numbers. This is the page most policyholders look at first &mdash; and sometimes the
        only page they look at. But the summary only makes sense once you understand the line
        items that feed into it.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Replacement Cost Value (RCV) Total
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The RCV total is the full estimated cost to repair or replace the damaged property
        using materials of like kind and quality, without any deduction for depreciation. This
        number represents what it should actually cost to restore your home to its pre-loss
        condition. It is the sum of all line item totals across all rooms, plus overhead and
        profit (if included) and applicable taxes.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Depreciation
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The summary will show the total depreciation being withheld. On an RCV policy, this
        amount is held back from your initial payment but is recoverable once you complete the
        repairs. On an ACV-only policy, the depreciation is a permanent deduction.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Actual Cash Value (ACV) Total
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The ACV total is the RCV total minus depreciation. This is the &quot;depreciated
        value&quot; of the loss &mdash; what the insurer calculates your damaged property
        was worth in its pre-loss condition, accounting for age and wear.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Deductible
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Your policy deductible is subtracted from the claim total. This is the amount you are
        responsible for paying out of pocket before insurance coverage kicks in. The deductible
        shown on the estimate should match the deductible listed on your{' '}
        <Link href="/resources/declarations-page" className="text-[#2E74B5] underline">
          declarations page
        </Link>.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Net Claim
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The net claim is the bottom line &mdash; the amount the insurance company intends to
        pay you. On an RCV policy, the initial payment is typically the ACV total minus the
        deductible. The withheld depreciation (sometimes called &quot;recoverable
        depreciation&quot;) is paid later, after you submit documentation showing the repairs
        have been completed.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Here is how the math works on a typical RCV claim:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>RCV Total: $50,000</li>
        <li>Depreciation: -$8,000</li>
        <li>ACV Total: $42,000</li>
        <li>Deductible: -$2,500</li>
        <li>Net Claim (initial payment): $39,500</li>
        <li>Recoverable depreciation (paid after repairs): $8,000</li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        If you are looking at these numbers and they do not add up, or if there are
        additional deductions you do not recognize, that warrants a closer look.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What to Look For: Common Red Flags
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Now that you know how to read the estimate, here is what to look for when evaluating
        whether it is fair and complete. These are the issues that experienced professionals
        check for on every claim, and they are the same issues you should be checking.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Missing Rooms or Areas
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Walk through your home and compare every damaged room against the estimate. Is the
        hallway that had water damage listed? What about the closets? The garage? The
        exterior? One of the most straightforward ways an estimate comes up short is by simply
        omitting entire areas of the home that sustained damage. This is a{' '}
        <Link href="/resources/scope-vs-price-disputes" className="text-[#2E74B5] underline">
          scope dispute
        </Link>{' '}
        &mdash; the adjuster and policyholder disagree on the extent of the damage, and the
        carrier&apos;s position is reflected by what is absent from the estimate rather than
        what is present.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Repair vs. Replace Decisions
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Look at each line item description and ask: does this match the actual condition of the
        damage? If the estimate says &quot;repair drywall&quot; but the drywall in question has
        extensive water damage, mold growth, or structural compromise, it should say
        &quot;remove and replace drywall.&quot; Repairing is cheaper than replacing, and an
        estimate that calls for repairs when replacement is necessary will significantly
        understate the true cost of restoration.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This is especially common with flooring, roofing, and cabinetry. An adjuster might
        include a line item to &quot;repair&quot; hardwood flooring when the planks are warped,
        cupped, or delaminated beyond what any repair can fix. The question is not just whether
        the item can be patched &mdash; it is whether the repair will restore the property to
        its pre-loss condition, which is the policy standard.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Incorrect Quantities
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Check the quantities against reality. If your master bedroom ceiling is 180 square feet
        and the estimate shows 120 SF of ceiling drywall, that is a 33% shortfall. If your
        roof is 25 squares and the estimate shows 20, that is five squares of roofing materials
        and labor that are missing from the claim. Measure your rooms and compare.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Quantity errors are particularly impactful because they cascade through the estimate.
        If the drywall quantity is wrong, then the texturing, priming, and painting quantities
        that depend on the same measurement will also be wrong. A single measurement error
        can propagate through four or five related line items.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        O&amp;P Issues
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Check whether overhead and profit is included. On claims that involve multiple trades
        &mdash; which is most claims of any size &mdash; a general contractor will be needed
        to coordinate the work, and the general contractor&apos;s overhead and profit is a
        legitimate cost of the repair. If the estimate excludes O&amp;P entirely, or applies
        it only to certain line items, that should be addressed.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Watch for estimates where some line items show &quot;O&quot; only or &quot;P&quot; only
        instead of the full &quot;O&amp;P&quot; designation. Splitting overhead from profit
        and applying them selectively is a technique that reduces the total payout while
        creating the appearance that O&amp;P has been addressed.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Missing Line Items: The Items Adjusters Commonly Leave Out
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        This is where the real money is. An estimate can have the right rooms, the right
        measurements, and the right prices &mdash; and still be thousands of dollars short
        because it is missing necessary line items. Here are the categories of items most
        commonly omitted from carrier estimates:
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Content manipulation and protection:</strong> When construction work is
        performed in a room, the contents of that room &mdash; furniture, electronics,
        clothing, personal items &mdash; need to be moved, protected, stored, and moved
        back. Xactimate has specific line items for content manipulation (moving contents
        out and back in) and floor/surface protection during construction. These are
        legitimate costs that contractors charge, and they are frequently missing from
        carrier estimates.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>R&amp;R vs. R&amp;I:</strong> When a fixture, appliance, or built-in component
        is in the way of the repair work, it needs to be removed. If the item itself is
        undamaged, it should be carefully removed and reinstalled (R&amp;I). If it is
        damaged, it needs to be removed and replaced (R&amp;R). Many estimates simply omit
        these tasks entirely. The toilet that needs to come out so the bathroom floor can be
        replaced. The vanity that must be removed for wall repairs. The light fixtures, outlet
        covers, towel bars, shelving &mdash; every one of these is a separate line item that
        represents real labor.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Cleaning:</strong> After construction work, the home needs to be cleaned.
        Xactimate has line items for detail cleaning (post-construction cleanup), rough
        cleaning (removing construction debris), and specialized cleaning (smoke, soot, or
        water damage). If the estimate involves any significant construction work but does not
        include cleaning line items, that is an omission.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Preparation and finishing work:</strong> Many repairs require preparation steps
        that are separate line items. Before painting, surfaces may need to be primed, sanded,
        or sealed. Before new flooring is installed, the subfloor may need to be prepared.
        Before new drywall is hung, old drywall needs to be torn out and the area cleaned.
        Each of these steps is a distinct line item with its own cost.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Matching:</strong> When you replace damaged materials, the new materials need
        to match the existing undamaged materials in the same area. This can mean matching
        paint colors, texture patterns, flooring styles, or exterior finishes. Matching
        often requires additional labor and materials beyond the basic replacement cost. If
        an exact match is unavailable, a larger area may need to be replaced to maintain
        a uniform appearance. Our article on{' '}
        <Link href="/resources/matching" className="text-[#2E74B5] underline">matching</Link>{' '}
        explains how this works in claims.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>Permits, dumpsters, and general conditions:</strong> Many repair projects
        require building permits, dumpster or debris hauling, portable toilets for workers,
        and other general condition items. These are legitimate project costs that belong in
        the estimate.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        For a comprehensive list of items that adjusters frequently omit, see our article on{' '}
        <Link href="/resources/commonly-missed-items" className="text-[#2E74B5] underline">
          commonly missed items in insurance estimates
        </Link>.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Unreasonable Depreciation
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Review the{' '}
        <Link href="/resources/depreciation-schedules-useful-life" className="text-[#2E74B5] underline">
          depreciation
        </Link>{' '}
        amounts on each line item. Depreciation should reflect the actual age and condition of
        the damaged item relative to its expected useful life. A 5-year-old roof with a 30-year
        rated shingle should not be depreciated by 50%. A 3-year-old HVAC system should not be
        depreciated as if it were at the end of its useful life.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Also look at whether depreciation is being applied to components that should not be
        depreciated at all. As mentioned above, labor costs, demolition, and debris removal
        do not &quot;age&quot; &mdash; these costs are the same regardless of how old the
        damaged item is. Depreciating these costs inflates the depreciation holdback and
        reduces your initial payment.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Labor Efficiency Settings
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        This is a less obvious but potentially significant issue. Xactimate has built-in
        settings called{' '}
        <Link href="/resources/xactimate-labor-efficiency-settings" className="text-[#2E74B5] underline">
          labor efficiency settings
        </Link>{' '}
        that can adjust the labor portion of line items up or down. These settings are meant
        to account for factors like job size (larger jobs can be more efficient per unit) or
        difficulty (confined spaces require more labor per unit). However, some carriers use
        these settings to systematically reduce labor costs across the board. Labor efficiency
        adjustments are not visible on the printed PDF &mdash; they are embedded in the
        underlying ESX file. If your unit prices seem lower than they should be, labor
        efficiency manipulation may be the reason.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What the Estimate Does NOT Tell You: The ESX File
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Here is something most policyholders never learn: the PDF estimate you receive is not
        the complete picture. Behind every Xactimate estimate is a digital file called an ESX
        file (or, in older versions, an ESX/ECX file). The ESX file is the actual Xactimate
        project file &mdash; the native format that contains all of the data, settings, and
        parameters the adjuster used to build the estimate.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The PDF printout shows you the results. The ESX file shows you the inputs. And there
        is a great deal of information in the ESX file that never appears on the printed
        estimate:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>Labor efficiency settings:</strong> As discussed above, these settings can
          reduce labor costs across the estimate without any visible indication on the PDF.
        </li>
        <li>
          <strong>Price list modifications:</strong> If the adjuster manually changed any
          prices from the Xactimate default, the ESX file shows exactly which items were
          modified and by how much.
        </li>
        <li>
          <strong>Excluded line items:</strong> The ESX file may contain line items that the
          adjuster considered but then excluded from the estimate. These excluded items can
          reveal scope that the adjuster acknowledged but chose not to include in the final
          numbers.
        </li>
        <li>
          <strong>Sketch data:</strong> The underlying room measurements, dimensions, and
          diagrams used to calculate quantities.
        </li>
        <li>
          <strong>Depreciation formulas:</strong> The specific useful life tables and
          depreciation calculations used for each item.
        </li>
        <li>
          <strong>Notes and audit trail:</strong> Internal notes the adjuster may have added
          during the estimating process.
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        You have the right to request the ESX file from your insurance company. For more
        information on why the ESX file matters and how to obtain it, see our article on{' '}
        <Link href="/resources/esx-file-rights-xactimate" className="text-[#2E74B5] underline">
          your right to the ESX file
        </Link>.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Common Abbreviations and Codes
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate estimates are full of abbreviations that can make the document feel like a
        foreign language. Here is a reference guide to the most common abbreviations you will
        encounter:
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Task Abbreviations
      </h3>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>R&amp;R</strong> &mdash; Remove and Replace. The damaged item is torn out and a new item is installed.</li>
        <li><strong>R&amp;I</strong> &mdash; Remove and Reinstall. The item is carefully removed, set aside, and put back after the underlying work is done.</li>
        <li><strong>DET</strong> &mdash; Detach and Reset. Similar to R&amp;I; the item is detached and reattached.</li>
        <li><strong>RPR</strong> &mdash; Repair. The item is fixed in place rather than replaced.</li>
        <li><strong>ADD</strong> &mdash; Additional. An add-on or supplemental task beyond the base line item.</li>
        <li><strong>MIN</strong> &mdash; Minimum charge. Some tasks have a minimum charge regardless of the quantity.</li>
        <li><strong>CONT</strong> &mdash; Contents. Refers to personal property rather than the building structure.</li>
      </ul>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Trade and Category Abbreviations
      </h3>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>DRY</strong> &mdash; Drywall</li>
        <li><strong>RFC</strong> &mdash; Roofing (composition/asphalt)</li>
        <li><strong>RFM</strong> &mdash; Roofing (metal)</li>
        <li><strong>RFT</strong> &mdash; Roofing (tile)</li>
        <li><strong>RFW</strong> &mdash; Roofing (wood shake/shingle)</li>
        <li><strong>PNT</strong> &mdash; Painting</li>
        <li><strong>FLR</strong> &mdash; Flooring</li>
        <li><strong>PLM</strong> &mdash; Plumbing</li>
        <li><strong>ELC</strong> &mdash; Electrical</li>
        <li><strong>HVC</strong> &mdash; HVAC (heating, ventilation, air conditioning)</li>
        <li><strong>CLN</strong> &mdash; Cleaning</li>
        <li><strong>WDR</strong> &mdash; Water damage restoration</li>
        <li><strong>DEM</strong> &mdash; Demolition</li>
        <li><strong>WND</strong> &mdash; Windows</li>
        <li><strong>SID</strong> &mdash; Siding</li>
        <li><strong>INS</strong> &mdash; Insulation</li>
        <li><strong>CAB</strong> &mdash; Cabinets</li>
        <li><strong>CTR</strong> &mdash; Countertops</li>
        <li><strong>MBL</strong> &mdash; Marble/stone</li>
        <li><strong>FEN</strong> &mdash; Fencing</li>
        <li><strong>FRM</strong> &mdash; Framing</li>
        <li><strong>APL</strong> &mdash; Appliances</li>
        <li><strong>TMP</strong> &mdash; Temporary repairs/protection</li>
      </ul>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Unit of Measure Abbreviations
      </h3>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>SF</strong> &mdash; Square foot</li>
        <li><strong>LF</strong> &mdash; Linear foot</li>
        <li><strong>SQ</strong> &mdash; Square (100 square feet, used for roofing)</li>
        <li><strong>EA</strong> &mdash; Each (individual unit)</li>
        <li><strong>HR</strong> &mdash; Hour</li>
        <li><strong>DA</strong> &mdash; Day</li>
        <li><strong>SY</strong> &mdash; Square yard</li>
        <li><strong>BF</strong> &mdash; Board foot</li>
        <li><strong>CF</strong> &mdash; Cubic foot</li>
        <li><strong>CY</strong> &mdash; Cubic yard</li>
        <li><strong>GL</strong> &mdash; Gallon</li>
        <li><strong>LS</strong> &mdash; Lump sum</li>
      </ul>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Other Common Abbreviations
      </h3>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>O&amp;P</strong> &mdash; Overhead and Profit</li>
        <li><strong>RCV</strong> &mdash; Replacement Cost Value</li>
        <li><strong>ACV</strong> &mdash; Actual Cash Value</li>
        <li><strong>GC</strong> &mdash; General Contractor</li>
        <li><strong>SUB</strong> &mdash; Subcontractor</li>
        <li><strong>DEPR</strong> &mdash; Depreciation</li>
        <li><strong>REPL</strong> &mdash; Replace</li>
        <li><strong>L&amp;M</strong> &mdash; Labor and Materials (the line item includes both)</li>
        <li><strong>L</strong> (alone) &mdash; Labor only (no materials included)</li>
        <li><strong>M</strong> (alone) &mdash; Materials only (no labor included)</li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Putting It All Together: A Sample Line Item Walkthrough
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Let&apos;s walk through what a real line item looks like and how to interpret it. Imagine
        you see the following in the &quot;Kitchen&quot; section of your estimate:
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>DRY R&amp;R &mdash; Remove &amp; replace drywall &mdash; 1/2&quot; &mdash;
        120 SF &mdash; $2.45/SF &mdash; $294.00 &mdash; O&amp;P &mdash; Depr: $29.40</strong>
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Here is what each element tells you:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>DRY R&amp;R:</strong> This is a drywall remove-and-replace line item. The
          damaged drywall will be torn out and new drywall installed.
        </li>
        <li>
          <strong>1/2&quot;:</strong> The drywall thickness is 1/2 inch. Make sure this matches
          what is actually in your home &mdash; if your home has 5/8&quot; drywall, the estimate
          should reflect that, as 5/8&quot; drywall costs more.
        </li>
        <li>
          <strong>120 SF:</strong> The adjuster measured 120 square feet of drywall to be
          replaced. Does this match the actual wall or ceiling area? Measure it yourself.
        </li>
        <li>
          <strong>$2.45/SF:</strong> The Xactimate price per square foot for this task. This
          includes both labor and materials at the price list rate for your region.
        </li>
        <li>
          <strong>$294.00:</strong> The total for this line item (120 SF x $2.45 = $294.00).
        </li>
        <li>
          <strong>O&amp;P:</strong> Overhead and profit will be applied to this line item, adding
          approximately 20% for general contractor coordination.
        </li>
        <li>
          <strong>Depr: $29.40:</strong> Depreciation of $29.40 is being withheld from this line
          item, which represents 10% depreciation. On an RCV policy, this amount is recoverable
          after repairs are completed.
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        Now ask yourself: after this drywall is hung, what else needs to happen? It needs to
        be taped, mudded, and finished. It probably needs texture applied to match the existing
        walls. It needs to be primed and painted. Each of those tasks should be its own line
        item. If the estimate shows drywall replacement but does not include finishing, texturing,
        priming, and painting, the estimate is incomplete.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What to Do If You Spot Problems
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        If you have reviewed your estimate and found issues &mdash; missing rooms, incorrect
        quantities, omitted line items, or other discrepancies &mdash; here are your options:
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Document Everything
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Before you contact anyone, document what you have found. Make a list of every
        discrepancy, with specific references to the estimate. For example:
        &quot;Kitchen section: estimate shows 120 SF of ceiling drywall, but actual ceiling
        measures 185 SF.&quot; Or: &quot;Master bedroom: estimate includes drywall replacement
        but does not include texture, prime, or paint for the new drywall.&quot; The more
        specific your documentation, the harder it is to dismiss your concerns.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Request the ESX File
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        As discussed above, the ESX file contains information that is not visible on the PDF.
        Requesting the{' '}
        <Link href="/resources/esx-file-rights-xactimate" className="text-[#2E74B5] underline">
          ESX file
        </Link>{' '}
        allows a qualified professional to open the estimate in Xactimate and see exactly what
        settings, modifications, and exclusions the adjuster used. This is one of the most
        powerful steps you can take in evaluating the fairness of your estimate.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Get an Independent Estimate
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Having your own Xactimate estimate prepared by an independent professional &mdash;
        either a licensed Public Adjuster or a qualified contractor who uses Xactimate &mdash;
        gives you a line-by-line comparison document. When your estimate and the carrier&apos;s
        estimate are both in Xactimate format, the differences become clear and specific.
        Instead of arguing in generalities, you can point to exact line items, quantities,
        and prices.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Submit a Formal Dispute
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        If you believe the estimate is materially inaccurate, you can submit a written
        dispute to your insurance company identifying the specific deficiencies. Our guide on{' '}
        <Link href="/resources/how-to-challenge-xactimate-estimate" className="text-[#2E74B5] underline">
          how to challenge a Xactimate estimate
        </Link>{' '}
        walks through this process step by step. The key is to be specific: identify each
        missing or incorrect item, cite the correct Xactimate line item code where possible,
        and provide supporting documentation (measurements, photos, contractor bids).
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Consider Professional Help
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        If the discrepancies are significant and the carrier is not responsive to your
        documented concerns, consider engaging a licensed Public Adjuster or an attorney who
        handles insurance claims. A Public Adjuster can prepare a comprehensive counter-estimate,
        negotiate with the carrier on your behalf, and ensure that every legitimate item is
        included. An attorney can advise you on your legal rights if the carrier&apos;s conduct
        rises to the level of bad faith.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Invoke the Appraisal Process
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Most homeowners insurance policies contain an{' '}
        <Link href="/resources/appraisal" className="text-[#2E74B5] underline">
          appraisal clause
        </Link>{' '}
        that provides a mechanism for resolving disputes over the amount of loss. If you and
        your carrier cannot agree on the value of the damage, either party can invoke appraisal.
        This process involves each side selecting an appraiser, and the two appraisers selecting
        an umpire to resolve any remaining disagreements. Appraisal is generally faster and
        less expensive than litigation, though it addresses only the dollar amount &mdash; not
        coverage disputes.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        A Note About Supplements
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The estimate you receive initially is rarely the final word. As repair work begins,
        contractors frequently discover additional damage that was not visible during the
        initial inspection &mdash; hidden water damage behind walls, compromised framing
        beneath finished surfaces, electrical or plumbing issues that only become apparent
        once demolition starts. When this happens, a &quot;supplement&quot; is submitted to
        the insurance company requesting additional payment for the newly discovered work.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Supplements are a normal and expected part of the claims process. A supplement is
        simply an addition to the original Xactimate estimate, adding new line items or
        adjusting existing ones to reflect the true scope of the damage. Do not assume that
        the initial estimate represents the full extent of your claim. If your contractor
        discovers additional damage during repairs, make sure a supplement is submitted and
        documented before the work is completed.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Understanding Your Estimate Is Your First Line of Defense
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The Xactimate estimate is the single most important document in your property damage
        claim. It defines the scope of what the insurance company will pay for, the quantities
        of work they are covering, and the prices they are willing to pay. Every dollar of
        your claim flows through this document.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        An estimate that is missing rooms, omitting necessary line items, using incorrect
        measurements, applying excessive depreciation, or excluding overhead and profit is
        an estimate that is shortchanging you. And if you do not read it, you will never know.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The good news is that you do not need to be an Xactimate expert to catch the most
        common problems. You know your home. You know which rooms were damaged. You can
        measure a wall. You can read a description and ask whether &quot;repair&quot; makes
        sense when the item in question was clearly destroyed. Start there, and if what you
        find raises concerns, seek professional guidance.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        For more on Xactimate and how it affects your claim, explore these related resources:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <Link href="/resources/xactimate" className="text-[#2E74B5] underline">
            Xactimate Estimates: What You Need to Know
          </Link>
        </li>
        <li>
          <Link href="/resources/esx-file-rights-xactimate" className="text-[#2E74B5] underline">
            Your Right to the ESX File
          </Link>
        </li>
        <li>
          <Link href="/resources/how-to-challenge-xactimate-estimate" className="text-[#2E74B5] underline">
            How to Challenge a Xactimate Estimate
          </Link>
        </li>
        <li>
          <Link href="/resources/xactimate-line-item-manipulation" className="text-[#2E74B5] underline">
            Xactimate Line Item Manipulation
          </Link>
        </li>
        <li>
          <Link href="/resources/xactimate-labor-efficiency-settings" className="text-[#2E74B5] underline">
            Xactimate Labor Efficiency Settings
          </Link>
        </li>
        <li>
          <Link href="/resources/xactimate-price-list-dates" className="text-[#2E74B5] underline">
            Xactimate Price List Dates
          </Link>
        </li>
        <li>
          <Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">
            Overhead and Profit
          </Link>
        </li>
        <li>
          <Link href="/resources/depreciation-schedules-useful-life" className="text-[#2E74B5] underline">
            Depreciation Schedules and Useful Life
          </Link>
        </li>
        <li>
          <Link href="/resources/scope-vs-price-disputes" className="text-[#2E74B5] underline">
            Scope vs. Price Disputes
          </Link>
        </li>
      </ul>
      <hr className="my-8 border-gray-300" />
      <p className="text-sm text-gray-500 italic">
        This article is for informational purposes only and does not constitute legal advice.
        Insurance policies and applicable law vary by state and by policy form. Consult with a
        licensed professional regarding your specific situation.
      </p>
      <p className="text-sm text-gray-500 mt-4 italic">
        Written by Leland Coontz III, Licensed Public Adjuster, CA License #2B53445.
      </p>
    </>
  )
}
