import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: 'Insurance Company Delay Tactics and Your Rights',
  description:
    'How insurance companies use delay to pressure you into accepting less. Learn the regulatory deadlines, how to document delays, and when to take action.',
}

export default function Content() {
  return (
    <>
      <p className="text-gray-700 leading-relaxed mb-4">
        If the lowball offer is the insurance industry&apos;s most common tactic, delay is its
        most effective. Time is always on the insurance company&apos;s side. The longer a claim
        drags on, the more desperate the homeowner becomes. Bills accumulate. The damage worsens.
        Eventually, many people accept whatever the carrier offers just to make it stop.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">California Regulatory Deadlines</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        California has some of the strongest claim handling regulations in the country. Under
        the Fair Claims Settlement Practices Regulations (10 CCR 2695), insurance companies must:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>Acknowledge your claim within 15 days</strong> of receiving notice</li>
        <li><strong>Begin investigation within 15 days</strong> of receiving notice</li>
        <li><strong>Accept or deny the claim within 40 days</strong> of receiving proof of claim</li>
        <li><strong>Pay accepted claims within 30 days</strong> of reaching agreement</li>
        <li>
          <strong>Provide written status updates every 30 days</strong> if the claim remains open
        </li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">The Multiple Adjuster Problem</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        One of the most frustrating delay tactics is the adjuster carousel. The insurance company
        assigns an adjuster to your claim. You spend weeks bringing them up to speed. Then they
        reassign your claim to a new adjuster. The process starts over. Some claims go through
        three, four, or five adjusters &mdash; each handoff adding weeks or months.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The American Policyholder Association has documented this as a deliberate insurer tactic —
        cycling through customer service representatives, managers, and adjusters so that each
        transition effectively restarts the claim process. In one case presented during 2025 Senate
        hearings, a homeowner testified that after more than 120 days and multiple personnel changes,
        the insurer had not begun repairs and was refusing to reimburse living expenses &mdash; despite the
        county declaring the home unsafe. Under California Insurance Code Section 14047 (enacted by
        SB 240, effective January 1, 2020), when a <em>residential property claim arising from a
        declared state of emergency</em> has had three or more adjusters assigned within a six-month
        period, the policyholder can request a special written status report from the insurance
        company. Note that this requirement applies specifically to emergency-declared losses, not to
        all claims. It is a separate requirement from the regular monthly status reports.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">What &quot;Proof of Claim&quot; Really Means</h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        An important concept many people do not understand: &quot;proof of claim&quot; is
        defined broadly in California regulations. It is not the same as a &quot;proof of
        loss&quot; (a formal sworn statement). Any estimate, bid, or invoice &mdash; whether
        submitted by the insured, generated by the adjuster, or even submitted by a contractor
        the insured is not interested in working with &mdash; can constitute a proof of claim.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Once a proof of claim exists, it becomes a &quot;claim-related document,&quot; and the
        insurance company&apos;s 40-day clock starts. Many adjusters do not realize this
        &mdash; or pretend they do not.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">How to Fight Delay</h2>
      <ol className="list-decimal pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>Keep a detailed communication log</strong> &mdash; dates, names, what was
          discussed, promises made
        </li>
        <li>
          <strong>Follow every call with a confirming email</strong> &mdash; &quot;Per our
          conversation today, you stated that...&quot;
        </li>
        <li>
          <strong>Cite specific regulatory deadlines</strong> in your written communications
        </li>
        <li>
          <strong>Request written status reports</strong> monthly, as required by regulation
        </li>
        <li>
          <strong>File a complaint with the California Department of Insurance</strong> if
          deadlines are violated &mdash;{' '}
          <Link href="/resources/cdi-complaint" className="text-blue-700 underline hover:text-blue-900">
            learn how here
          </Link>
        </li>
        <li>
          <strong>Consider hiring a Public Adjuster or attorney</strong> &mdash; carriers often
          move faster when a professional is involved
        </li>
      </ol>

      <CalloutBox variant="tip" title="Document Everything">
        <p>
          Every unreturned phone call, every missed deadline, every broken promise is
          potential evidence of{' '}
          <Link href="/resources/bad-faith" className="text-blue-700 underline hover:text-blue-900">
            bad faith
          </Link>. The paper trail you build during the delay is what makes
          a bad faith case possible later. Do not rely on verbal communication &mdash;
          get everything in writing.
        </p>
      </CalloutBox>

      <CalloutBox variant="warning" title="When Delay Becomes a Legal Issue">
        <p>
          A pattern of delay — missed regulatory deadlines, unreturned communications, repeated
          adjuster reassignments — is not just frustrating. It can be evidence of bad faith. If
          the insurer has missed multiple regulatory deadlines or your claim has been open for
          several months without meaningful progress, consult an attorney. An attorney can evaluate
          whether the delay supports a bad faith claim, send a formal demand that creates legal
          consequences for continued inaction, and ensure your statute of limitations is protected.
        </p>
        <p className="mt-2">
          A Public Adjuster can document delays, push the claim forward through the regulatory
          process, and build the factual record that supports a bad faith claim if legal action
          becomes necessary.
        </p>
      </CalloutBox>

      <CalloutBox variant="legal" title="Important Notice">
        <p>
          This article is provided for general educational purposes only and does not constitute
          legal advice. Insurance policies, regulations, and case law can vary significantly based
          on individual circumstances. Consult a licensed attorney for advice about your specific
          situation. If you need a referral to an attorney experienced in insurance coverage disputes,
          a licensed Public Adjuster may be able to assist.
        </p>
      </CalloutBox>
    </>
  )
}
