import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: "How Insurers Use Data and Algorithms to Deny Coverage",
  description:
    "Insurers use algorithmic risk scoring, aerial imagery, CLUE reports, and predictive analytics to price, deny, and non-renew your coverage. What to do about it.",
  summary:
    'Insurers use algorithmic risk scores, aerial imagery, CLUE reports, and predictive analytics to price, deny, and non-renew policies, often opaquely. Know what data they collect, how it affects you, and your rights to review and dispute it.',
}

export default function Content() {
  return (
    <>
      <CalloutBox variant="legal" title="This Article Is Not Legal Advice">
        <p>
          This article is educational commentary by a Licensed California Public
          Adjuster. It is not legal advice. For legal questions about your specific
          situation, consult a licensed California attorney.
        </p>
      </CalloutBox>

      <p className="text-gray-700 leading-relaxed mb-4">
        When a homeowner applies for insurance, renews a policy, or files a claim, the carrier is not making decisions based solely on the information the policyholder provides. Behind the scenes, an increasingly sophisticated array of data sources, algorithms, and predictive models is shaping every decision the carrier makes &mdash; from the premium charged, to whether coverage is offered at all, to how aggressively the claim is scrutinized, to whether the policy is renewed after a loss.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This system of algorithmic risk assessment has transformed the insurance industry over the past two decades. What was once a process driven by individual underwriters reviewing applications has become an automated, data-driven machine that scores properties, neighborhoods, and policyholders in ways that are largely invisible to the people being scored. Understanding how this system works is essential for any policyholder who wants to know why their premium increased, why their application was declined, or why their claim is being handled the way it is.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What Risk Scoring Is
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Risk scoring is the process by which an insurance company uses data and algorithms to assign a risk profile to a property, a policyholder, or both. The risk score influences the premium, the deductible, the available coverage options, and increasingly, how the carrier handles claims filed by that policyholder. A higher risk score means higher premiums, more restrictive coverage terms, and potentially more aggressive claim scrutiny.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Unlike a credit score &mdash; which is generated by a known set of credit bureaus using publicly understood criteria &mdash; insurance risk scores are proprietary. Each carrier develops its own scoring models, uses its own combination of data inputs, and assigns its own weightings to different risk factors. The policyholder typically has no visibility into the score, no understanding of how it was calculated, and no meaningful ability to challenge it.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Data Sources Insurers Use
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The volume and variety of data that carriers now collect on properties and policyholders is staggering. The following are the most significant data sources:
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        CLUE Reports
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The Comprehensive Loss Underwriting Exchange (CLUE) is a database maintained by LexisNexis that records insurance claims history for properties and individuals. A{' '}
        <Link href="/resources/clue-database" className="text-[#2E74B5] underline hover:text-blue-900">
          CLUE report
        </Link>{' '}
        shows every claim filed on a property for the past seven years, including the date of loss, the type of loss, the amount paid, and the carrier that handled the claim. Carriers consult CLUE reports when underwriting new policies, at renewal, and sometimes during the claims process. A property with multiple prior claims will score higher risk, even if the current owner was not responsible for the prior losses.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Aerial and Satellite Imagery
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Carriers now routinely use aerial and satellite imagery to inspect properties without ever sending an inspector to the location. Companies like EagleView, Nearmap, and Cape Analytics provide carriers with high-resolution images that reveal roof condition, roof age estimates, vegetation encroachment, brush clearance, structural additions, pool presence, trampoline presence, and other risk factors. The carrier may use this imagery at underwriting, at renewal, or after a claim is filed. A policyholder may receive a non-renewal notice based entirely on an aerial image that the carrier believes shows an aging roof or inadequate brush clearance &mdash; without anyone ever visiting the property.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Credit-Based Insurance Scores
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Most states allow insurers to use credit-based insurance scores as a factor in pricing and underwriting. These scores are derived from credit reports but are calculated differently from the FICO scores used by lenders. The insurance industry argues that credit-based scores are statistically correlated with claim frequency. Consumer advocates argue that they are a proxy for socioeconomic status and disproportionately affect lower-income policyholders. California is one of the few states that prohibits the use of credit scores in homeowner insurance pricing under Proposition 103 and its implementing regulations.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Building Permit Records
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Carriers access public building permit databases to identify construction activity on insured properties. Unpermitted additions, renovations without permits, or evidence of construction that was not reported to the carrier can trigger underwriting reviews, premium adjustments, or coverage restrictions. Conversely, permits for roof replacement, electrical upgrades, or seismic retrofitting may improve the property&rsquo;s risk profile.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Geographic and Neighborhood Data
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Carriers use geographic data at increasingly granular levels. Rather than pricing by ZIP code, modern carriers price by &ldquo;micro-territories&rdquo; that may be as small as a city block. The data inputs include proximity to fire stations and hydrants, historical wildfire burn maps, flood zone designations, seismic hazard zones, crime statistics, neighborhood claims frequency, and distance from the coast. A property on one side of a street may receive a dramatically different risk score than a property on the other side.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Roof Age and Condition Estimates
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Roof condition is one of the most significant factors in property risk scoring. Carriers use building permit records, aerial imagery, and algorithmic estimation models to determine when the roof was last replaced and what condition it is in. A property with a roof estimated to be over 20 years old may be scored as high risk, resulting in higher premiums, a restricted claims settlement (actual cash value instead of replacement cost for the roof), or non-renewal.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Wildfire and Brush Clearance Scores
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        In California, wildfire risk scoring has become a dominant factor in insurance availability. Carriers use models from companies like CoreLogic, Verisk, and Zesty.ai that assign wildfire risk scores to individual properties based on vegetation density, slope, historical fire perimeters, ember transport modeling, and defensible space assessments. Carriers&apos; reliance on these scores has been a significant factor in the{' '}
        <Link href="/resources/california-insurance-crisis" className="text-[#2E74B5] underline hover:text-blue-900">
          California insurance crisis
        </Link>, with carriers declining to write or renew policies in areas that their models deem too risky.
      </p>

      <CalloutBox variant="warning" title="The Black Box Problem">
        <p>
          The fundamental challenge with algorithmic risk scoring is transparency &mdash; or more precisely, the lack of it. Policyholders typically cannot see their risk score, do not know what data was used to calculate it, and have no meaningful mechanism to challenge errors. A carrier may decline to renew a policy based on an aerial image that incorrectly identifies roof damage, or a wildfire model that assigns a high risk score based on vegetation conditions that the homeowner has already addressed. Without access to the underlying data and methodology, the policyholder is fighting blind.
        </p>
      </CalloutBox>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        How Risk Scores Affect Claims Handling
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Risk scoring does not only affect pricing and underwriting. It increasingly influences how claims are handled after a loss occurs. While carriers do not publicly acknowledge using risk scores to guide claims decisions, several patterns are observable:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>SIU referral triggers.</strong> Properties or policyholders with certain risk profiles may be flagged for Special Investigations Unit (SIU) review more quickly than others. A claim from a property with a prior history of claims, a recent policy increase, or certain geographic characteristics may receive heightened scrutiny.</li>
        <li><strong>Adjuster assignment.</strong> Some carriers use algorithms to assign claims to adjusters based on the claim&rsquo;s complexity and the property&rsquo;s risk profile. Higher-risk or higher-value claims may be assigned to more experienced &mdash; or more aggressive &mdash; adjusters.</li>
        <li><strong>Initial reserve setting.</strong> The initial reserve amount (the carrier&rsquo;s internal estimate of what the claim will cost) may be influenced by algorithmic models that consider the property&rsquo;s risk profile, the type of loss, and historical claim data for similar properties.</li>
        <li><strong>Settlement offers.</strong> Predictive analytics can influence the initial settlement offer. Models that predict policyholder behavior &mdash; including the likelihood that the policyholder will hire an attorney, file a complaint, or accept a lowball offer &mdash; may guide the carrier&rsquo;s negotiation strategy.</li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Interaction with AI and Machine Learning
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The insurance industry is rapidly adopting artificial intelligence and machine learning tools that extend beyond traditional risk scoring. These tools include:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>Automated damage assessment.</strong> AI tools that analyze photographs of property damage to generate repair estimates, sometimes without a human adjuster ever visiting the property.</li>
        <li><strong>Natural language processing of claim descriptions.</strong> AI that analyzes the text of claim reports, recorded statements, and correspondence to identify patterns associated with fraud, litigation risk, or claim severity.</li>
        <li><strong>Predictive litigation models.</strong> Algorithms that predict which claims are most likely to result in litigation, allowing the carrier to adjust its handling strategy accordingly &mdash; either by settling more generously to avoid suit or by preparing a more aggressive defense early.</li>
        <li><strong>Dynamic pricing models.</strong> Machine learning models that continuously update risk scores based on new data, including real-time weather events, neighborhood construction activity, and changes in the property&rsquo;s physical condition as detected by imagery.</li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        The concern with these tools is not that they exist &mdash; data-driven decision-making can improve efficiency and accuracy &mdash; but that they operate without adequate transparency, oversight, or accountability. A machine learning model that systematically undervalues claims in certain neighborhoods, or that flags policyholders with certain demographic characteristics for heightened scrutiny, can perpetuate discrimination without any individual at the carrier intending to discriminate.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Disparate Impact Concerns
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Consumer advocates and regulators have raised significant concerns about the potential for algorithmic risk scoring to produce disparate impacts on protected classes. Even if a model does not explicitly use race, ethnicity, or income as inputs, it may use proxy variables &mdash; such as neighborhood, ZIP code, credit score, or property age &mdash; that are highly correlated with those characteristics. The result can be a system that charges higher premiums, provides less coverage, or handles claims more aggressively for communities of color and lower-income neighborhoods, even though the model appears facially neutral.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        California&rsquo;s Proposition 103 provides some protection by requiring that insurance rates not be &ldquo;excessive, inadequate, or unfairly discriminatory&rdquo; and by mandating prior approval of rate changes. However, Proposition 103 was enacted in 1988, long before algorithmic risk scoring reached its current level of sophistication. The existing regulatory framework was not designed to evaluate opaque machine learning models, and regulators are working to close this gap.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        California&rsquo;s Proposition 103 and Regulatory Limitations
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Proposition 103 requires that California auto and homeowner insurance rates not be
        &ldquo;excessive, inadequate, or unfairly discriminatory&rdquo; (Cal. Ins. Code
        &sect; 1861.05(a)), and subjects rate changes to prior approval by the CDI. Insurance
        Code &sect; 1861.02 lists specific mandatory rating factors for <em>automobile</em>
        insurance &mdash; not for homeowner insurance, which the CDI evaluates through the
        class-plan approval process under &sect; 1861.05 and 10 CCR &sect; 2360 et seq. against
        the &ldquo;unfairly discriminatory&rdquo; standard. Among the factors carriers commonly
        use in approved homeowner rating plans are location of the property, the amount of
        insurance, and the claims history. Credit-based insurance scoring is not permitted in
        California homeowner rate filings &mdash; a position the CDI has maintained since at
        least its 2003 guidance &mdash; even though most other states allow it. These
        restrictions provide California consumers with more protection than policyholders in
        most other states.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        However, Proposition 103&rsquo;s protections have limits. The CDI has limited resources to audit the complex algorithmic models that carriers submit with their rate filings. Carriers can present models that technically comply with the approved rating factors while embedding additional data inputs in ways that are difficult for regulators to detect. The CDI has been working to strengthen its capacity to review algorithmic models, but the regulatory infrastructure remains a work in progress.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        NAIC Efforts to Regulate Algorithmic Underwriting
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The National Association of Insurance Commissioners (NAIC) has recognized the regulatory challenges posed by algorithmic underwriting and has undertaken several initiatives to address them. The NAIC&rsquo;s Innovation, Cybersecurity, and Technology Committee has developed principles for the use of AI in insurance, emphasizing transparency, fairness, and accountability. The NAIC has also developed a model bulletin on the use of AI by insurers, encouraging state regulators to require carriers to:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>Disclose the use of AI and algorithmic models in underwriting, pricing, and claims decisions</li>
        <li>Test models for disparate impact and unfair discrimination</li>
        <li>Maintain governance frameworks for the development and deployment of AI tools</li>
        <li>Provide meaningful explanations to consumers when AI-driven decisions adversely affect them</li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        These efforts are still evolving, and the extent to which individual states adopt and enforce NAIC recommendations varies widely. California has been among the more active states in this area, but the gap between regulatory ambition and enforcement capacity remains significant.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Practical Steps for Policyholders
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        While policyholders cannot fully control how carriers score their properties and claims, there are concrete steps that can improve transparency and reduce the risk of adverse decisions based on inaccurate or outdated data:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>Check the CLUE report.</strong> Every consumer is entitled to one free CLUE report per year from LexisNexis. Many policyholders review it for accuracy, and dispute any claims listed that are incorrect, that belong to a prior owner, or that were inquiries rather than actual claims. For more on how CLUE reports affect coverage, see the article on the{' '}
          <Link href="/resources/clue-database" className="text-[#2E74B5] underline hover:text-blue-900">
            CLUE database
          </Link>.
        </li>
        <li><strong>Request the insurance score.</strong> Policyholders may request their insurance score from LexisNexis or the specific scoring company the carrier uses. The score itself may not be changeable, but understanding what factors are driving it can help identify correctable issues.</li>
        <li><strong>Ask what data the insurer has on the property.</strong> Asking the carrier or agent what data sources the company uses for underwriting and renewal decisions &mdash; specifically whether aerial imagery has been reviewed and whether the property has been assigned a wildfire risk score &mdash; can surface decision-driving inputs the policyholder otherwise wouldn&apos;t see.</li>
        <li><strong>Roof and brush-clearance maintenance ahead of the next renewal.</strong> If the carrier uses aerial imagery or wildfire scoring, proactively addressing the issues these tools are designed to detect tends to help. Many policyholders replace an aging roof before the carrier uses it as a basis for non-renewal, and document defensible-space maintenance with dated photographs.</li>
        <li><strong>Document property improvements.</strong> Improvements that reduce risk &mdash; a new roof, upgraded electrical, seismic retrofitting, fire-resistant landscaping &mdash; can improve the property&apos;s risk profile only if the carrier knows about them. Many policyholders notify the carrier in writing and provide documentation.</li>
        <li><strong>Challenging non-renewal decisions.</strong> If a policy is{' '}
          <Link href="/resources/nonrenewal-cancellation" className="text-[#2E74B5] underline hover:text-blue-900">
            non-renewed
          </Link>, the insured may request a written explanation of the reasons. If the non-renewal is based on data the insured believes is inaccurate &mdash; for example, an aerial image that misidentifies roof condition &mdash; a challenge with documentation showing the actual condition is one available path.
        </li>
        <li><strong>CDI complaints.</strong> Insureds who believe a carrier has used inaccurate data, an unfairly discriminatory algorithm, or a non-transparent process to make an adverse decision can file a complaint with the California Department of Insurance. Regulatory complaints create a record that may prompt review of the carrier&apos;s practices.</li>
      </ul>

      <CalloutBox variant="tip" title="Request Your Property&rsquo;s Aerial Imagery Report">
        <p>
          If your carrier has used aerial imagery in its underwriting or renewal decision, request a copy of the report. Some carriers will provide it upon request. If the imagery shows conditions that are outdated or inaccurate &mdash; for example, vegetation that has since been cleared, or a roof that has been replaced &mdash; provide current photographs and documentation to correct the record. The carrier&rsquo;s decision should be based on current conditions, not stale imagery.
        </p>
      </CalloutBox>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Related Resources
      </h2>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <Link href="/resources/clue-database" className="text-[#2E74B5] underline hover:text-blue-900">
            The CLUE Database and Your Insurance History
          </Link>
        </li>
        <li>
          <Link href="/resources/nonrenewal-cancellation" className="text-[#2E74B5] underline hover:text-blue-900">
            Non-Renewal and Cancellation
          </Link>
        </li>
        <li>
          <Link href="/resources/california-insurance-crisis" className="text-[#2E74B5] underline hover:text-blue-900">
            The California Insurance Crisis
          </Link>
        </li>
      </ul>

      <hr className="my-8 border-gray-300" />
      <p className="text-sm text-gray-500 italic">
        This article is for informational purposes only and does not constitute legal advice.
        Insurance policies and applicable law vary by state and by policy form. Consult with a
        licensed professional regarding your specific situation.
      </p>
      <p className="text-sm text-gray-500 mt-4 italic">
        Written by Leland Coontz III, Licensed Public Adjuster, CA License #2B53445.
      </p>
    </>
  )
}
