import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: "When a Contractor’s Bid Overrides Xactimate: Sub-Bids, Specialty Work, and What the EULA Actually Says",
  description:
    "A guide for policyholders, public adjusters, and attorneys on why a specialty sub-contractor’s actual bid should control over Xactimate line-item pricing and how to make that argument stick.",
  summary:
    'When a specialty subcontractor\'s actual bid exceeds Xactimate\'s line-item price, the real bid should control, because Xactimate is a pricing estimate, not a binding cost. Document the sub-bid to override understated software pricing.',
}

export default function Content() {
  return (
    <>
      <CalloutBox variant="legal" title="This Article Is Not Legal Advice">
        <p>
          This article is educational commentary by a Licensed California Public
          Adjuster. It is not legal advice. For legal questions about your specific
          situation, consult a licensed California attorney.
        </p>
      </CalloutBox>

      <p className="text-gray-700 leading-relaxed mb-4">
        <em>
          A guide for policyholders, public adjusters, and attorneys on why a specialty
          sub-contractor&apos;s actual bid should control over Xactimate line-item pricing
          &mdash; and how to make that argument stick.
        </em>
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        Your kitchen had hand-built cherry cabinetry. The cabinet maker &mdash; a third-generation
        craftsman who works out of a shop in the San Fernando Valley &mdash; inspected the fire
        damage, measured the existing cabinets, matched the wood species, the joinery style, the
        finish, and the hardware profile. He put his bid on company letterhead: $42,000 for
        fabrication and installation. His price reflects a six-week lead time, the current cost of
        select-grade cherry lumber, custom dovetail construction, and a finish process that
        requires four coats of hand-rubbed lacquer.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The insurance company&apos;s Xactimate estimate prices the same cabinetry at $18,400.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The adjuster did not call the cabinet maker. The adjuster did not visit the shop. The
        adjuster selected &quot;remove and replace base cabinet&quot; and &quot;remove and replace
        wall cabinet&quot; from a drop-down menu, entered a linear-foot measurement, and let a
        software algorithm assign a per-unit price derived from a national database of averaged
        costs. That price includes stock cabinetry &mdash; the kind you can buy at a home
        improvement warehouse and install in an afternoon. It does not contemplate custom
        fabrication. It does not contemplate a six-week build. It does not contemplate hand-rubbed
        lacquer. It does not contemplate matching existing work that was never &quot;stock&quot;
        to begin with.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The carrier will tell you that $18,400 is the correct number because that is what
        Xactimate says. The carrier is wrong. And the software&apos;s own manufacturer agrees.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Fundamental Principle: Estimates vs. Reality
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        At the center of every sub-bid dispute is a simple question: when a specialty contractor
        provides a written bid for specific work, and that bid differs from the price generated by
        Xactimate, which number controls?
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The answer is not complicated. Xactimate generates estimated pricing based on database
        averages. A sub-contractor&apos;s bid represents actual market pricing for the specific
        work on the specific property. When these two numbers diverge &mdash; and in specialty
        work, they almost always do &mdash; the bid reflects reality. It tells you what it
        actually costs to get the work done. The Xactimate number tells you what a statistical
        model thinks it should cost based on data that may be months old, geographically
        imprecise, and categorically wrong for the type of work involved.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        What Xactimate Pricing Actually Represents
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Verisk, the parent company of Xactware Solutions, publishes a Pricing Research Methodology
        document describing how its database works. Pricing data is &quot;acquired using a
        combination of surveys (phone, fax, or email), direct data feeds from suppliers, and
        completed estimates.&quot; The company uses cluster analysis to identify &quot;a single
        representative price per line item, computed from all valid price points researched within
        the market.&quot;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        That sounds precise. But Verisk itself acknowledges: &quot;There is no way to be certain
        that any published price will be appropriate for a specific contractor, repair, or
        structure.&quot; The company that maintains the database concedes that its prices may not
        be appropriate for any given contractor, repair, or structure. This is Verisk&apos;s own{' '}
        <a
          href="https://www.verisk.com/4a2266/siteassets/media/downloads/property-estimating/pricing-research-methodology.pdf"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[#2E74B5] underline"
        >
          published methodology document
        </a>.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        What a Sub-Contractor&apos;s Bid Represents
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        A sub-contractor&apos;s bid is not a statistical abstraction. It is a commitment:
        &quot;I will do this specific work, on this specific property, using these specific
        materials and methods, for this specific price.&quot; It reflects actual labor costs,
        actual material costs, and actual assessment of the complexity involved &mdash; factors
        no database can capture.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        When a cabinet maker bids $42,000 to fabricate and install custom cherry cabinetry, that
        number is not theoretical. If the homeowner writes that check, the cabinet maker builds
        the cabinets. There is no version of reality in which $18,400 produces the same result.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Specialty Work: Where Xactimate Consistently Falls Short
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate was designed primarily for standard residential construction &mdash; the kind
        of work that involves commodity materials, commonly available labor, and repeatable
        processes. It handles a straightforward drywall repair reasonably well. It handles custom
        and specialty work poorly, and sometimes not at all. The following categories of work
        routinely generate bids that exceed Xactimate pricing by significant margins.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Custom Cabinetry and Millwork
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate prices cabinetry using line items that assume stock or semi-custom cabinets
        &mdash; the mass-produced boxes available through big-box retailers and supply houses.
        When a loss involves custom cabinetry &mdash; face-frame construction with
        mortise-and-tenon joinery, inset doors, specialty wood species, hand-applied finishes
        &mdash; the Xactimate line item bears no relationship to the actual cost. A stock kitchen
        cabinet might run $150 to $300 per linear foot installed. Custom cabinetry from a skilled
        shop routinely runs $800 to $1,500 or more per linear foot. Custom millwork &mdash; crown
        molding profiles no longer commercially available, period-specific baseboards, built-in
        bookshelves, coffered ceilings &mdash; presents the same problem. When existing millwork
        must be matched by a shop running a custom knife, the cost can be three to five times the
        Xactimate price.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Natural Stone Fabrication and Installation
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        A slab of Calacatta marble can cost $80 to $250 per square foot at the fabricator before
        any cutting, polishing, or installation. Xactimate&apos;s line item for &quot;marble
        countertop&quot; does not distinguish between a $40 per square foot builder-grade marble
        and a $200 per square foot bookmatched Calacatta slab with a waterfall return. When a
        stone fabricator bids $28,000 for a kitchen with an island, peninsula, and full-height
        backsplash in honed quartzite, and Xactimate prices the same scope at $11,500, the gap
        is not the fabricator&apos;s greed. It is the software&apos;s ignorance of what the work
        actually involves.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Tile Work
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Large-format tile, intricate mosaic patterns, hand-painted tile, and installations
        requiring precision layout all involve significantly more labor than standard
        grid-pattern ceramic tile. A tile installer setting 48-inch by 48-inch porcelain panels
        in a shower with linear drains and recessed niches is performing work that has almost
        nothing in common with the &quot;ceramic tile floor&quot; line item in Xactimate. Labor
        rates for skilled tile setters in major California markets currently run $75 to $125 per
        hour. Xactimate&apos;s embedded labor rate does not approach this.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Hardwood Flooring
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Matching existing hardwood &mdash; especially exotic species, wide plank, or hand-scraped
        finishes &mdash; is one of the most consistently underpriced categories. A flooring
        contractor who must source reclaimed antique heart pine to match a 1920s Craftsman home
        is not performing the same work as someone installing prefinished red oak from a pallet.
        Xactimate does not account for sourcing discontinued profiles, matching patina, weaving
        new material into old, or the waste factor inherent in matching work.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Other Specialty Categories
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The same dynamic repeats across custom metalwork (wrought iron railings, ornamental gates
        &mdash; where the disconnect is often 200% to 400%), specialty roofing (slate, clay tile,
        copper, standing seam), historical restoration (original plaster, period hardware, leaded
        glass), pool and spa construction, and custom electrical and low-voltage work. In every
        case, the pattern is identical: Xactimate prices commodity work, the property has custom
        work, and the sub-contractor&apos;s bid reflects the difference.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Why Xactimate Underpays Specialty Work: A Structural Problem
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The gap between Xactimate pricing and specialty contractor bids is not a bug in the
        software. It is a feature of the software&apos;s design. Understanding why helps explain
        why the gap is so persistent and so predictable.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Xactimate Is Designed for the Middle of the Bell Curve
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Verisk&apos;s pricing methodology is designed to identify &quot;the most common price
        recently submitted&quot; for each line item. This is, by definition, an average &mdash;
        a central tendency. It reflects the price that most contractors most commonly charge for
        the most common version of a given task. This approach works reasonably well for commodity
        work. It fails for anything that deviates from the norm.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Custom and specialty work, by definition, deviates from the norm. A custom cabinet shop
        does not submit pricing data to Verisk. An artisan stone fabricator does not fill out
        Xactimate surveys. A master tile setter specializing in large-format porcelain
        installation does not feed completed estimates into a database. The contractors whose work
        generates the highest-quality results &mdash; and the highest legitimate costs &mdash;
        are the least likely to be represented in the data that drives Xactimate pricing.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The Database Cannot Capture Complexity
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate prices work by line item. Each line item has a description, a unit of measure,
        and a price. But specialty work does not reduce neatly to line items. The cost of
        fabricating a custom cabinet is not a function of linear feet alone &mdash; it depends on
        the species of wood, the type of joinery, the number and style of doors, the drawer
        construction method, the finish process, the hardware, and the specific dimensions
        required to fit an existing space. Xactimate cannot capture this complexity in a single
        line item. It was never designed to.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Regional and Market-Specific Variations
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate organizes pricing by geographic region, but the regions are broad enough to
        obscure significant local variations. The cost of skilled specialty labor in Beverly Hills
        is not the same as in Bakersfield. The cost of sourcing exotic hardwood in San Francisco
        is not the same as in Fresno. The cost of a licensed pool contractor in Malibu is not the
        same as in Modesto. Xactimate&apos;s regional pricing may reflect an average across a
        wide area, but it does not reflect the specific market in which the work will actually be
        performed.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Matching Existing Work Is Inherently More Expensive Than New Installation
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        This is perhaps the most important point. Insurance claims do not involve new
        construction. They involve restoration &mdash; returning a property to its pre-loss
        condition. Matching is always more expensive than new installation: it requires sourcing
        specific materials (which may be discontinued or scarce), custom fabrication to match
        existing dimensions and profiles, color and finish matching (which may require multiple
        attempts), and blending new work into old. Xactimate&apos;s line items do not distinguish
        between &quot;install new&quot; and &quot;match existing.&quot; The software treats them
        as the same task. They are not.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Xactimate EULA: The Manufacturer&apos;s Own Disclaimer
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The most powerful weapon in a sub-bid dispute is not an expert opinion, a legal brief, or
        a regulatory complaint. It is the End User License Agreement that every Xactimate user
        accepts when they log into the software. The{' '}
        <a
          href="https://www.verisk.com/privacy-policies/xactware-eula/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[#2E74B5] underline"
        >
          EULA, published by Verisk
        </a>, contains language that directly contradicts the way carriers use Xactimate pricing
        to cap claim payments.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Section 12.3: No Warranty of Pricing Accuracy
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Section 12.3 of the Xactware EULA states plainly: <strong>&quot;We do not warrant the
        accuracy of pricing information in the Price Data.&quot;</strong>
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The company that built the database, maintains the database, and charges subscription fees
        for access to the database does not stand behind the numbers in the database. The EULA
        explains that pricing data is &quot;intended to target the most representative price of
        the various price points collected&quot; and that &quot;some market price data are higher,
        and some market price data are lower than that which are reported.&quot; In plain English:
        the Xactimate price is a calculated midpoint. It will be wrong for virtually every
        contractor who does not happen to charge the exact midpoint price.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The Anti-Prohibition Clause
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The EULA contains another provision that is equally devastating to the carrier&apos;s
        position. Users agree &quot;not to prohibit or preclude deviations from the Price Data
        where contractor requirements, market conditions, demand or any other factor warrants the
        use of a different line-item price in the specific situation.&quot;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Read that carefully. The EULA does not merely permit deviations from Xactimate pricing.
        It affirmatively prohibits users from preventing deviations when real-world conditions
        warrant them. An insurer that refuses to deviate from Xactimate pricing when a legitimate
        sub-contractor bid demonstrates that the Xactimate price is insufficient is arguably
        violating the terms of its own software license.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This clause was the subject of significant advocacy by the{' '}
        <a
          href="https://www.restorationindustry.org/restoration-blog/xactware-user-license-agreement-language-restored-after-restoration-industry"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[#2E74B5] underline"
        >
          Restoration Industry Association (RIA)
        </a>, which successfully pressed Verisk to restore and strengthen this language after a
        2024 EULA revision temporarily weakened it. Aaron Brunko, President of Xactware, publicly
        acknowledged that the language was necessary to ensure that Xactimate tools &quot;deliver
        on restorers&apos; operational needs&quot; and adhere to fair pricing principles.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The Historical Data Problem
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The EULA also acknowledges that Xactimate pricing is based on historical data. By the
        time a price list reaches users, the underlying data is already at least thirty days old
        &mdash; and often older, given the lag between data collection, analysis, and publication.
        In volatile material markets &mdash; lumber prices that swing 30% in a quarter, copper
        that fluctuates weekly, specialty stone that varies by shipment &mdash; the historical
        nature of Xactimate pricing means the software is always looking backward while the
        contractor is pricing forward.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        A sub-contractor&apos;s bid reflects current costs. Xactimate reflects what costs used to
        be. In any market experiencing price increases &mdash; which describes most construction
        markets in most years &mdash; the bid will be higher because it is more current.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        How to Present a Sub-Bid Challenge
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        A sub-bid challenge is only as strong as its documentation. The goal is to create a
        record that is clear, specific, and impossible for the carrier to dismiss as unsupported.
        Here is how to build that record.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Step 1: Get the Bid in Writing on Company Letterhead
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The bid must come from the sub-contractor on the sub-contractor&apos;s own letterhead,
        signed by an authorized representative, with the contractor&apos;s license number,
        insurance information, and contact details. A verbal quote or a text message will not
        carry the same weight.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Step 2: Ensure the Bid Is Detailed and Itemized
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        A lump-sum bid is vulnerable to dismissal. The bid should itemize materials, labor, and
        other cost components in sufficient detail that the carrier can understand exactly what is
        being priced. For cabinetry, this means species of wood, type of construction, door and
        drawer count, hardware allowance, finish process, and installation method. For stone
        fabrication: slab species and grade, square footage, edge profile, cutouts, backsplash
        specifications, and template and installation costs. The more detail the bid contains,
        the harder it is for the carrier to dismiss it as inflated.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Step 3: Map the Bid to the Carrier&apos;s Xactimate Line Items
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        This step transforms a general disagreement into a specific, defensible challenge.
        Identify every Xactimate line item the sub-contractor&apos;s bid addresses and create a
        side-by-side comparison with the differential calculated for each. This demonstrates that
        the bid is not a separate estimate &mdash; it is a correction to specific line items in
        the carrier&apos;s own estimate.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Step 4: Include the EULA Language
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Attach the relevant sections of the Xactimate EULA. Quote Section 12.3 and the
        anti-prohibition clause. Point out that the carrier&apos;s own estimating tool requires
        the user to deviate from its pricing when real-world conditions demonstrate that the
        database price is inadequate.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Step 5: Document the Sub-Contractor&apos;s Qualifications
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Include the contractor&apos;s license information, years of experience, portfolio of
        comparable work, and any relevant certifications or trade association memberships. If the
        cabinet maker has thirty years of experience and is a member of the Architectural
        Woodwork Institute, that information supports the proposition that his bid reflects the
        legitimate cost of skilled artisan work.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Step 6: Present the Challenge in Writing
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Submit the challenge as a formal written supplement to the claim. Address it to the
        adjuster by name and copy the adjuster&apos;s supervisor. State clearly that the
        sub-contractor&apos;s bid represents the actual cost to restore the property to its
        pre-loss condition, and that the carrier&apos;s obligation under the policy is to pay the
        actual cost of repair &mdash; not the amount generated by a software algorithm whose own
        manufacturer disclaims its accuracy.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Carrier&apos;s Typical Responses &mdash; and Why They Fail
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        When confronted with a sub-bid that exceeds Xactimate pricing, carriers deploy a
        predictable set of responses. Each of these responses has a fundamental weakness.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        &quot;Our Estimate Is Based on Industry-Standard Pricing&quot;
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Verisk does not claim its pricing is an &quot;industry standard.&quot; It describes its
        pricing as &quot;the most representative price of the various price points collected&quot;
        &mdash; a statistical average, not a standard. And Xactimate&apos;s own EULA disclaims
        the accuracy of that pricing. A carrier cannot credibly characterize as
        &quot;industry-standard&quot; the output of a tool whose manufacturer says its prices are
        not warranted to be accurate.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        &quot;Get Three Bids&quot;
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        No standard homeowners policy &mdash; HO-3, HO-5, or any other commonly used form
        &mdash; requires the policyholder to obtain competitive bids as a prerequisite to claim
        payment. The policy requires restoration to pre-loss condition and payment of the actual
        cost to repair or replace.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The demand is also logically flawed for specialty work. If the property has custom cherry
        cabinetry built by a specific shop, there may be only one or two shops in the market
        capable of matching that work. Requiring three bids for work that only a handful of
        contractors can perform is a delay tactic, not a good-faith claims handling practice. In
        California, 10 Cal. Code Regs. &sect;2695.9(d) places the burden on the insurer, not the
        insured: the insurer must either pay the difference or provide a contractor who will do
        the work at the insurer&apos;s price.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        &quot;We&apos;ll Pay What Xactimate Says&quot;
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate is not referenced in the insurance policy. It is not a contract term. The
        insured never agreed that Xactimate pricing would govern the settlement of their claim.
        The policy promises to pay the cost to repair or replace damaged property to its pre-loss
        condition. When a carrier says &quot;we&apos;ll pay what Xactimate says,&quot; it is
        substituting a software output for a contractual obligation.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        &quot;The Bid Is Inflated&quot;
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Carriers sometimes characterize sub-contractor bids as &quot;inflated&quot; without
        substantive basis. If the carrier believes a bid is inflated, it should identify specific
        line items that exceed reasonable market pricing and provide evidence &mdash; not opinion
        &mdash; of what the correct price should be. Merely asserting that a bid is
        &quot;inflated&quot; because it exceeds Xactimate is circular reasoning: it assumes the
        conclusion it is trying to prove.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        &quot;We Can Find a Contractor Who Will Do It for Our Price&quot;
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The question is not whether any contractor somewhere will accept the carrier&apos;s
        price. The question is whether that contractor can perform the specific work required
        &mdash; matching existing custom cabinetry, fabricating the specific stone, replicating
        the specific tile pattern &mdash; to the standard necessary to restore the property to
        its pre-loss condition. A contractor who will install stock cabinets for $18,400 is not
        the same as one who will fabricate custom cherry cabinets for $42,000. If the property
        had custom cherry cabinets before the loss, the policy requires custom cherry cabinets.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        In California, 10 Cal. Code Regs. &sect;2695.9(d) addresses this directly. If the
        insurer wants to avoid paying the claimant&apos;s higher estimate, the insurer must
        &quot;provide the claimant with the name of at least one repair individual or entity that
        will make the repairs for the amount of the written estimate.&quot; The repairs &mdash;
        not a cheaper version of the repairs.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Legal Framework
      </h2>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The Policy Language: Restoration to Pre-Loss Condition
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Standard homeowners policies promise to pay the cost to &quot;repair or replace&quot;
        damaged property with material &quot;of like kind and quality.&quot; The insured is
        entitled to be restored to the condition that existed before the loss &mdash; not a
        cheaper condition, not a &quot;close enough&quot; condition. When pre-loss condition means
        custom cabinetry, the carrier owes the cost of custom cabinetry. The carrier does not get
        to substitute stock for custom and call it &quot;like kind and quality.&quot;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        California Insurance Code &sect; 2051(b) provides that the measure of recovery is
        &ldquo;the amount it would cost the insured to repair, rebuild, or replace the thing
        lost or injured less a fair and reasonable deduction for physical depreciation based
        upon its condition at the time of the injury or the policy limit, whichever is less.&rdquo;
        Under &sect; 2051.5(a), replacement cost coverage requires payment of &ldquo;the
        amount that it would cost the insured to repair, rebuild, or replace the thing lost
        or injured, without a deduction for physical depreciation, or the policy limit,
        whichever is less.&rdquo;
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        The Actual Cost Standard
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The measure of damages in a first-party property claim is the actual cost to repair or
        replace. Not the estimated cost. Not the software-generated cost. Not the cost that a
        statistical model predicts based on historical averages. The actual cost &mdash; what it
        takes, in the real market, to hire a real contractor to perform the real work.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        When a sub-contractor provides a written bid, that bid is evidence of actual cost. It is
        not the only evidence &mdash; the carrier is entitled to examine the bid, question its
        components, and challenge specific line items on substantive grounds. But it is powerful
        evidence, because it represents a real commitment from a real contractor to perform real
        work at a stated price.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        California Fair Claims Settlement Practices
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        California&apos;s{' '}
        <a
          href="https://www.insurance.ca.gov/01-consumers/130-laws-regs-hearings/05-CCR/fair-claims-regs.cfm"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[#2E74B5] underline"
        >
          Fair Claims Settlement Practices Regulations
        </a>, codified at 10 Cal. Code Regs. &sect;&sect;2695.1 through 2695.17, impose specific
        obligations on insurers in the handling of property claims. Several provisions are
        directly relevant to sub-bid disputes.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>&sect;2695.9(d)</strong> requires that when losses are settled on the basis of
        a written estimate, the estimate &ldquo;shall be of an amount which will restore the
        damaged property to no less than its condition prior to the loss&rdquo; and that the
        insurer
        &quot;shall take reasonable steps to verify that the repair or rebuilding costs utilized
        by the insurer or its claims agents are accurate and representative of costs in the local
        market area.&quot;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>&sect;2695.9(d)</strong> provides that when the claimant contends that repairs
        will exceed the insurer&apos;s estimate, the insurer must either pay the difference or
        provide a contractor who will do the work at the insurer&apos;s price. When a specialty
        contractor&apos;s bid exceeds the Xactimate estimate, the carrier cannot simply stand on
        its estimate.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        <strong>California Insurance Code{' '}
        <a
          href="https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=790.03.&lawCode=INS"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[#2E74B5] underline"
        >
          &sect;790.03(h)
        </a></strong> prohibits unfair claims settlement practices, including &quot;not
        attempting in good faith to effectuate prompt, fair and equitable settlements&quot; and
        &quot;compelling insureds to institute litigation to recover amounts due under an
        insurance policy by offering substantially less than the amounts ultimately
        recovered.&quot; When a carrier refuses to consider a legitimate sub-contractor bid and
        clings to Xactimate pricing that the software&apos;s own manufacturer disclaims, the
        carrier&apos;s conduct begins to implicate these provisions.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Case Law: Actual Cost Controls
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Courts across jurisdictions have recognized that the measure of indemnity in property
        insurance is the actual cost to repair or replace. In{' '}
        <a
          href="https://law.justia.com/cases/california/court-of-appeal/4th/81/1282.html"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[#2E74B5] underline"
        >
          <em>Fraley v. Allstate Insurance Co.</em> (2000) 81 Cal.App.4th 1282
        </a>, the California Court of Appeal reinforced that the policy&apos;s promise centers on
        the actual cost of restoring the property.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        In{' '}
        <a
          href="https://www.courtlistener.com/opinion/1551164/mee-v-safeco-insurance-company-of-america/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[#2E74B5] underline"
        >
          <em>Mee v. Safeco Insurance Company of America</em> (2006) 908 A.2d 344
        </a>, the Pennsylvania Superior Court held that repair costs must include all costs the
        insured is &quot;reasonably likely to incur&quot; &mdash; a standard that naturally
        encompasses the actual bid from a specialty sub-contractor when specialty work is
        required. In{' '}
        <a
          href="https://caselaw.findlaw.com/court/fl-supreme-court/1637393.html"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[#2E74B5] underline"
        >
          <em>Trinidad v. Florida Peninsula Insurance Co.</em> (2013) 121 So.3d 433
        </a>, the Florida Supreme Court held that the cost of repair includes all components that
        a policyholder is &quot;reasonably likely&quot; to need. If the insured reasonably needs
        a specialty contractor to restore the property to its pre-loss condition, the cost of
        that contractor is part of the measure of recovery.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Practical Examples: The Numbers Tell the Story
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The following examples illustrate how Xactimate pricing diverges from actual
        sub-contractor bids. These figures are representative of claims in California markets,
        though similar gaps occur nationwide.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Custom Kitchen Cabinetry
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        A fire damages a kitchen with custom face-frame cabinetry in quarter-sawn white oak with
        inset doors and hand-applied conversion varnish. The cabinet maker bids $54,000 for
        fabrication and installation. Xactimate, pricing the same scope as semi-custom stock
        cabinets, generates $19,200. The differential: $34,800, or 181%.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Natural Stone Countertops
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Water damage destroys countertops in a kitchen with bookmatched Calacatta marble, a
        full-height backsplash, and a waterfall-edge island. The stone fabricator bids $33,960.
        Xactimate generates $10,140. The differential: $23,820, or 235%.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Specialty Tile Shower
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        A bathroom with floor-to-ceiling hand-painted ceramic tile in a herringbone pattern with
        accent borders requires full replacement after a pipe burst. The tile contractor bids
        $21,780. Xactimate generates $6,160. The differential: $15,620, or 254%.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        In each example, the gap is not a matter of the contractor padding the price. It is a
        matter of Xactimate pricing the wrong work. The software priced standard materials and
        standard labor. The property had custom materials and required specialty labor. The
        difference is the cost of restoration to pre-loss condition &mdash; which is exactly what
        the policy promises.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Conclusion
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate is a useful tool. It is a reasonable starting point for estimating the cost of
        standard residential construction and repair. But it is not an oracle, it is not a
        contract term, and it is not a ceiling on the carrier&apos;s obligations. Its own
        manufacturer does not guarantee its accuracy. Its own license agreement requires users to
        deviate from its pricing when real-world conditions demand it.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        When a specialty sub-contractor provides a written bid for work that exceeds Xactimate
        pricing, that bid is not a problem to be overcome. It is evidence &mdash; evidence of
        what the work actually costs. The policy requires restoration to pre-loss condition. The
        sub-contractor&apos;s bid tells you what restoration to pre-loss condition costs. The
        carrier&apos;s obligation is to pay that cost, not to substitute a software-generated
        number that even the software&apos;s creator will not stand behind.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Every custom cabinet, every slab of specialty stone, every hand-set tile, every forged
        iron railing, every matched hardwood floor tells the same story: the real world is more
        expensive than Xactimate thinks it is. And the insurance policy does not promise the
        Xactimate world. It promises the real one.
      </p>

      <p className="text-gray-700 leading-relaxed mb-4">
        <em>
          The information in this article is intended for educational purposes and does not
          constitute legal advice. Policyholders and public adjusters should consult with a
          qualified attorney regarding specific claims disputes.
        </em>
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Sources and References
      </h3>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          Verisk,{' '}
          <a
            href="https://www.verisk.com/privacy-policies/xactware-eula/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Xactware End User License Agreement</em>
          </a>, Section 12.3
        </li>
        <li>
          Verisk,{' '}
          <a
            href="https://www.verisk.com/4a2266/siteassets/media/downloads/property-estimating/pricing-research-methodology.pdf"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Pricing Research Methodology</em>
          </a>
        </li>
        <li>
          Restoration Industry Association,{' '}
          <a
            href="https://www.restorationindustry.org/restoration-blog/xactware-user-license-agreement-language-restored-after-restoration-industry"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Xactware User License Agreement Language Restored After RIA AGA and Verisk Meeting</em>
          </a>
        </li>
        <li>
          Chip Merlin,{' '}
          <a
            href="https://www.propertyinsurancecoveragelaw.com/blog/xactimate-price-warning-xactimate-finally-admits-it-is-not-so-exact/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Xactimate Price Warning &mdash; Xactimate Finally Admits It Is Not So Exact!</em>
          </a>
        </li>
        <li>
          United Policyholders,{' '}
          <a
            href="https://uphelp.org/claim-guidance-publications/xactimate-demystified/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Xactimate Demystified</em>
          </a>
        </li>
        <li>
          California Department of Insurance,{' '}
          <a
            href="https://www.insurance.ca.gov/01-consumers/130-laws-regs-hearings/05-CCR/fair-claims-regs.cfm"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Fair Claims Settlement Practices Regulations</em>
          </a>{' '}
          (10 CCR 2695.1&ndash;2695.17)
        </li>
        <li>
          Cal. Code Regs. tit. 10, &sect;2695.9 &mdash;{' '}
          <a
            href="https://www.law.cornell.edu/regulations/california/10-CCR-2695.9"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            law.cornell.edu
          </a>
        </li>
        <li>
          Cal. Ins. Code &sect;790.03 &mdash;{' '}
          <a
            href="https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=790.03.&lawCode=INS"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            leginfo.legislature.ca.gov
          </a>
        </li>
        <li>
          <a
            href="https://law.justia.com/cases/california/court-of-appeal/4th/81/1282.html"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Fraley v. Allstate Ins. Co.</em>
          </a>{' '}
          (2000) 81 Cal.App.4th 1282
        </li>
        <li>
          <a
            href="https://www.courtlistener.com/opinion/1551164/mee-v-safeco-insurance-company-of-america/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Mee v. Safeco Insurance Company of America</em>
          </a>{' '}
          (2006) 908 A.2d 344 (Pa. Super.)
        </li>
        <li>
          <a
            href="https://caselaw.findlaw.com/court/fl-supreme-court/1637393.html"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Trinidad v. Florida Peninsula Ins. Co.</em>
          </a>{' '}
          (2013) 121 So.3d 433 (Fla.)
        </li>
        <li>
          Chip Merlin,{' '}
          <a
            href="https://www.propertyinsurancecoveragelaw.com/blog/insurance-regulations-prohibit-an-insurer-from-just-standing-by-its-repair-estimate-when-an-insureds-estimate-demonstrates-the-cost-to-repair-is-more-another-california-practice-tip/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#2E74B5] underline"
          >
            <em>Insurance Regulations Prohibit an Insurer From Just Standing By Its Repair Estimate</em>
          </a>
        </li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Sources &amp; Further Reading
      </h2>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>Property Insurance Coverage Law Blog (Merlin Law Group)</strong> &mdash; Merlin Law Group has written on the gap between contractor sub-bids and Xactimate pricing in claim disputes. Search the blog for &ldquo;Xactimate&rdquo; and &ldquo;sub-bid.&rdquo;
        </li>
        <li>
          <strong>United Policyholders</strong> &mdash; Consumer-advocacy resources on estimating disputes and contractor pricing (uphelp.org).
        </li>
        <li>
          <strong>Verisk / Xactimate documentation</strong> &mdash; Verisk is the publisher of Xactimate; its materials describe how the price list is built and intended to be used.
        </li>
      </ul>

      <hr className="my-8 border-gray-300" />
      <p className="text-sm text-gray-500 italic">
        This article is for informational purposes only and does not constitute legal advice.
        Insurance policies and applicable law vary by state and by policy form. Consult with a
        licensed professional regarding your specific situation.
      </p>
      <p className="text-sm text-gray-500 mt-4 italic">
        Written by Leland Coontz III, Licensed Public Adjuster, CA License #2B53445.
      </p>
    </>
  )
}
