import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: 'Systematic Underinsurance and Class Action Litigation Against Carriers',
  description:
    'How insurers systematically undervalue properties at policy inception, leaving entire classes of policyholders underinsured when losses occur, and the class action litigation that has followed.',
  summary:
    'Insurers often undervalue homes at policy inception, leaving whole classes of policyholders underinsured when disaster strikes. This pattern has driven class-action litigation challenging the carriers\' replacement-cost estimating practices.',
}

export default function Content() {
  return (
    <>
      <CalloutBox variant="legal" title="This Article Is Not Legal Advice">
        <p>
          This article is educational commentary by a Licensed California Public
          Adjuster. It is not legal advice. For legal questions about your specific
          situation, consult a licensed California attorney.
        </p>
      </CalloutBox>

      <p className="text-gray-700 leading-relaxed mb-4">
        When a single policyholder discovers that their dwelling coverage is inadequate after a
        loss, it is easy to frame the problem as an individual mistake &mdash; a failure to
        update coverage limits, an oversight at renewal, a misunderstanding of replacement cost.
        But when hundreds or thousands of policyholders insured by the same carrier all find
        themselves underinsured after the same catastrophe, the pattern points to something far
        more troubling: a systematic failure in how the carrier estimated replacement costs at
        the point of sale.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Systematic underinsurance occurs when a carrier&rsquo;s valuation tools, underwriting
        practices, or cost estimation models consistently produce replacement cost figures that
        fall below actual rebuilding costs. The result is that policyholders who relied on
        their carrier&rsquo;s expertise to set appropriate coverage limits discover, only after
        a catastrophic loss, that their limits are tens or hundreds of thousands of dollars
        short. This is not a problem that affects a few unlucky individuals. It is a
        class-wide phenomenon that has generated significant litigation across the country.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        How Carrier Valuation Tools Create the Problem
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Most homeowners do not independently calculate the replacement cost of their dwelling.
        They rely on their insurance carrier or agent to provide an estimate, typically
        generated through proprietary replacement cost estimation tools. The most widely used
        tools include Marshall &amp; Swift/Boeckh (now CoreLogic), Xactware&rsquo;s 360Value,
        and e2Value. These tools take property characteristics &mdash; square footage, year
        built, construction type, number of stories, roof type, and similar features &mdash;
        and produce an estimated replacement cost that becomes the basis for the policy&rsquo;s
        dwelling limit.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The fundamental problem is that these tools are only as accurate as the data entered
        and the assumptions built into their algorithms. Multiple sources of error can produce
        systematically low estimates:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>Incomplete or inaccurate property data.</strong> If the tool uses default
          values for features it does not know &mdash; such as interior finishes, custom
          cabinetry, built-in features, or upgrades &mdash; the default is almost always the
          lower-cost option. A home with granite countertops, hardwood floors, and custom
          millwork may be estimated as though it has laminate, carpet, and builder-grade trim.
        </li>
        <li>
          <strong>Outdated cost databases.</strong> Construction costs fluctuate significantly
          based on regional labor markets, material costs, and demand. If the cost data
          underlying the estimation tool lags behind actual market conditions, every estimate
          generated by that tool will be low.
        </li>
        <li>
          <strong>Failure to account for local building code requirements.</strong> Replacement
          cost means rebuilding to current code, which may require upgrades that did not exist
          when the home was originally constructed. Estimation tools that do not incorporate
          current local code requirements will understate the true cost of rebuilding.
        </li>
        <li>
          <strong>Ignoring demand surge.</strong> After a widespread catastrophe, the cost of
          labor and materials in the affected area can increase by 30 to 50 percent or more
          due to simultaneous demand. Standard estimation tools do not account for this price
          inflation, which means the entire insured population in a disaster zone is
          underinsured from the moment the event occurs.
        </li>
        <li>
          <strong>Systematic bias in algorithm design.</strong> Some plaintiffs&rsquo;
          attorneys and consumer advocates have alleged that certain carriers deliberately
          configure their valuation tools to produce lower estimates, reducing premium
          obligations for the carrier while shifting the risk of inadequate limits onto the
          policyholder.
        </li>
      </ul>

      <CalloutBox variant="warning" title="The Policyholder Trusted the Carrier">
        <p>
          When a carrier or agent uses a replacement cost estimation tool and presents the
          resulting figure to the policyholder as an appropriate coverage limit, the
          policyholder reasonably relies on that professional judgment. The carrier cannot
          later disclaim responsibility for the inadequacy of a limit it helped set.
        </p>
      </CalloutBox>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Individual Underinsurance vs. Systematic Underinsurance
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Individual underinsurance is different from systematic underinsurance.
        Individual underinsurance results from a specific policyholder&rsquo;s
        choices or circumstances &mdash; declining recommended coverage amounts, failing to
        report renovations, or selecting a lower limit to reduce premium. In those situations,
        the policyholder bears meaningful responsibility for the coverage gap.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Systematic underinsurance is different. It occurs when the carrier&rsquo;s own
        processes &mdash; the tools it uses, the data it collects, the assumptions it applies
        &mdash; produce inadequate coverage limits across a broad swath of its book of
        business. The distinguishing characteristics include:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          The same estimation tool or methodology is used for thousands of policies.
        </li>
        <li>
          The resulting coverage shortfalls are directionally consistent &mdash; nearly all
          affected policies are underinsured, not overinsured.
        </li>
        <li>
          The shortfalls are proportionally similar across properties of different types and
          values, indicating a systemic bias rather than random error.
        </li>
        <li>
          Policyholders who relied on the carrier&rsquo;s estimate had no independent way to
          know the limit was inadequate until a loss occurred.
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        When this pattern emerges, the carrier&rsquo;s conduct is not merely negligent on an
        individual basis &mdash; it reflects an institutional practice that harmed a
        definable class of policyholders. That is precisely the scenario that class action
        litigation is designed to address.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Notable Class Actions and Litigation
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The problem of systematic underinsurance has generated class action litigation against
        major carriers, particularly in the aftermath of large-scale wildfire and hurricane
        events. Several categories of claims have emerged:
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Post-Wildfire Underinsurance Claims in California
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        California&rsquo;s devastating wildfire seasons have exposed the underinsurance
        problem on a massive scale. After events such as the 2017 Tubbs Fire in Santa Rosa,
        the 2018 Camp Fire in Paradise, and subsequent wildfire disasters, thousands of
        policyholders discovered that their dwelling coverage fell far short of actual
        rebuilding costs. Consumer advocacy organizations, including United Policyholders,
        documented that underinsurance rates among wildfire survivors frequently exceeded 60
        percent of affected households.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Litigation following these events alleged that carriers used replacement cost
        estimation tools they knew to be inaccurate, failed to update cost data to reflect
        California&rsquo;s construction cost environment, and did not advise policyholders
        that their limits might be inadequate. Firms such as Cotchett, Pitre &amp; McCarthy
        and Lieff Cabraser Heimann &amp; Bernstein have represented policyholders in class
        and mass actions arising from wildfire underinsurance disputes.
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Hurricane-Related Undervaluation Claims
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Similar patterns have emerged after major hurricane events in Florida, Louisiana, and
        along the Gulf Coast. Policyholder class actions have alleged that carriers
        systematically undervalued properties in coastal regions, producing coverage limits
        that were insufficient to rebuild in the post-hurricane construction environment.
        Merlin Law Group, a nationally recognized policyholder advocacy firm, has described
        systematic underinsurance as &ldquo;one of the most widespread and least understood
        problems in property insurance.&rdquo;
      </p>

      <h3 className="text-xl font-semibold text-[#1F3964] mb-3">
        Estimation Tool Accuracy Litigation
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Some class actions have targeted the estimation tools themselves, or the manner in
        which carriers used them. Allegations in these cases typically include claims that
        carriers selected tool settings that minimized replacement cost estimates, overrode
        higher estimates produced by the tool in favor of lower figures, or failed to enter
        known property features that would have increased the estimate. These cases raise
        questions about whether the carrier&rsquo;s conduct constituted breach of contract,
        negligent misrepresentation, or unfair business practices.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Coinsurance Penalty as Double Punishment
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        For commercial policyholders, systematic underinsurance creates a particularly
        punishing outcome through the{' '}
        <Link href="/resources/coinsurance-penalty" className="text-[#2E74B5] underline hover:text-blue-900">
          coinsurance penalty
        </Link>
        . When a commercial property policy includes a coinsurance clause &mdash; typically
        requiring insurance equal to 80 or 90 percent of replacement cost &mdash; the
        policyholder who is underinsured does not simply face a coverage gap for the
        uninsured portion. The policyholder is penalized on the entire claim, receiving
        a proportionally reduced payment even for losses well within the policy limit.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This means the carrier benefits twice from systematic undervaluation: it collects a
        lower premium (because the limit is lower), and when a loss occurs, it pays even less
        than the inadequate limit by applying the coinsurance penalty. The policyholder, who
        relied on the carrier&rsquo;s valuation tool to set what the policyholder believed
        was an adequate limit, absorbs the entire shortfall.
      </p>

      <CalloutBox variant="important" title="Coinsurance and Carrier-Set Limits">
        <p>
          If the carrier or its agent used a valuation tool to recommend the coverage limit,
          and that limit later proves insufficient to satisfy the coinsurance requirement, the
          policyholder should challenge any coinsurance penalty. The carrier should not be
          permitted to penalize a policyholder for relying on the carrier&rsquo;s own
          inadequate estimate. Policyholders facing this situation should consult with a
          Public Adjuster or coverage attorney immediately.
        </p>
      </CalloutBox>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        California Regulatory Framework
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        California has enacted some of the strongest consumer protections in the country
        regarding replacement cost estimates, in large part because of the wildfire
        underinsurance crisis. Key regulatory provisions include:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>California Insurance Code &sect; 10101.</strong> This statute prohibits
          the issuance or renewal of a residential property insurance policy unless the
          insurer delivers the standardized California Residential Property Insurance
          Disclosure (the form mandated by &sect; 10102) and the California Residential
          Property Insurance Bill of Rights (described in &sect; 10103.5). It is a
          disclosure-delivery requirement, not a replacement-cost-estimate requirement.
        </li>
        <li>
          <strong>California Insurance Code &sect; 10102.</strong> This section mandates
          the content of the standardized Residential Property Insurance Disclosure form,
          which describes the principal residential dwelling coverage types &mdash; Actual
          Cash Value, Replacement Cost, Extended Replacement Cost, and Guaranteed
          Replacement Cost &mdash; and warns consumers that the form is not part of the
          policy and that only the policy controls coverage and amounts payable.
        </li>
        <li>
          <strong>California Insurance Code &sect; 10103.4 (AB 1797).</strong> This is the
          provision most directly relevant to the systematic-underinsurance problem. When
          the insurer provides replacement cost coverage under &sect; 10102, the insurer
          must, at least every other year at renewal, either (1) provide an updated estimate
          of the cost to rebuild or replace the dwelling that complies with 10 CCR
          &sect;&sect; 2695.180&ndash;2695.183, or (2) offer renewal coverage limits based
          on an inflation factor reflecting construction costs in the insured&rsquo;s area.
        </li>
        <li>
          <strong>10 CCR &sect;&sect; 2695.180&ndash;2695.183 (CDI Replacement Cost
          Estimate Regulations).</strong> These regulations define what counts as a
          replacement cost estimate, specify the factors that must be considered, prohibit
          misleading or incomplete estimates, and impose documentation requirements. This
          is where the substantive duty to use reasonable methodologies and current
          construction-market data lives.
        </li>
        <li>
          <strong>AB 2756 (2018) and &sect; 2051.5.</strong> Following major wildfire
          events, California enacted AB 2756 (Dodd), which strengthened post-disaster
          consumer protections. The statute works alongside Cal. Ins. Code &sect; 2051.5
          to reinforce the insured&rsquo;s rights to use replacement cost benefits to
          rebuild or to purchase a replacement home at a different location, to access
          extensions including ordinance-or-law and extended replacement cost, and to
          receive meaningful insurer assistance during the rebuild-or-relocate decision.
          AB 2756 does not create the periodic-estimate requirement; that lives in
          &sect; 10103.4.
        </li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What Policyholders Can Do to Protect Themselves
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        While the burden of accurate valuation should rest with the carrier that collects the
        premium, the reality is that policyholders must take proactive steps to verify their
        coverage limits. The following strategies can help identify and close coverage gaps
        before a loss occurs:
      </p>
      <ol className="list-decimal pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>Obtain an independent replacement cost estimate.</strong> Do not rely
          solely on the carrier&rsquo;s valuation tool. Hire a licensed contractor, appraiser,
          or Public Adjuster to provide an independent estimate of what it would cost to
          rebuild the structure from the ground up, including demolition, debris removal,
          foundation work, and construction to current code. Compare that figure to the
          dwelling limit on the declarations page.
        </li>
        <li>
          <strong>Review the carrier&rsquo;s estimate in detail.</strong> Under Cal. Ins.
          Code &sect; 10103.4 and 10 CCR &sect;&sect; 2695.180&ndash;2695.183, policyholders
          should receive periodic updated replacement cost estimates and have the right to
          documentation supporting those estimates. Review the estimate for accuracy
          &mdash; check whether the correct square footage, construction type, number of
          bathrooms, roof material, and interior finish levels are reflected.
        </li>
        <li>
          <strong>Account for code upgrade costs.</strong> Replacement cost means rebuilding
          to current code, which may require expensive upgrades (seismic retrofitting, energy
          efficiency requirements, fire-resistant materials) that were not part of the original
          construction. Ensure the coverage limit accounts for these{' '}
          <Link href="/resources/code-upgrade-coverage" className="text-[#2E74B5] underline hover:text-blue-900">
            code upgrade costs
          </Link>.
        </li>
        <li>
          <strong>Update coverage after renovations.</strong> Any renovation that adds value
          to the structure &mdash; kitchen remodels, bathroom additions, room conversions,
          upgraded electrical or plumbing systems &mdash; increases replacement cost. Notify
          the carrier and request a revised estimate after any significant work.
        </li>
        <li>
          <strong>Monitor construction cost trends in the area.</strong> If construction costs
          in the region are rising rapidly (as they have been throughout much of California),
          the coverage limit set two or three years ago may already be outdated. Request a
          new estimate at each renewal, even if the carrier does not offer one.
        </li>
      </ol>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Guaranteed Replacement Cost Endorsements
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The single most effective protection against underinsurance is a{' '}
        <Link href="/resources/replacement-cost-vs-guaranteed" className="text-[#2E74B5] underline hover:text-blue-900">
          guaranteed replacement cost endorsement
        </Link>
        . This endorsement obligates the carrier to pay whatever it actually costs to rebuild
        the structure, even if that amount exceeds the dwelling limit on the declarations
        page. The policyholder is protected against estimation errors, construction cost
        inflation, demand surge, and code upgrade costs.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        However, guaranteed replacement cost endorsements have become increasingly difficult
        to obtain in California, particularly in wildfire-prone areas. Many carriers have
        stopped offering them entirely, and others have replaced them with &ldquo;extended
        replacement cost&rdquo; endorsements that provide only a percentage above the stated
        limit &mdash; typically 25 to 50 percent. While an extended replacement cost
        endorsement is better than nothing, it still leaves the policyholder exposed if
        actual rebuilding costs exceed the limit plus the extension.
      </p>

      <CalloutBox variant="tip" title="Practical Tip: Request the Endorsement in Writing">
        <p>
          When applying for or renewing a homeowners policy, request a guaranteed replacement
          cost endorsement in writing. If the carrier declines to offer one, ask for a written
          explanation of why. This creates a paper trail that may be relevant if a coverage
          dispute arises later. At minimum, request the highest available extended replacement
          cost percentage.
        </p>
      </CalloutBox>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Role of Agents and Brokers
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Insurance agents and brokers have a duty to advise their clients on appropriate
        coverage levels. When an agent runs a replacement cost estimation tool and presents
        the result to the policyholder without verifying its accuracy, without explaining its
        limitations, or without recommending that the policyholder obtain an independent
        estimate, the agent may share liability for the resulting coverage gap.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        In California, the duty of an insurance broker is well established. A broker who
        fails to procure the coverage requested by the client, or who fails to advise the
        client of foreseeable coverage deficiencies, may be liable for negligence. The
        policyholder-side coverage bar has written extensively about the obligations of
        agents and brokers in the coverage-placement process.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Policyholders who discover they were underinsured after a loss should review the
        communications they received from their agent or broker at the time the policy was
        placed and at each renewal. If the agent recommended the coverage limit based on a
        replacement cost estimation tool without disclosing its limitations, or if the agent
        failed to recommend available endorsements such as guaranteed or extended replacement
        cost, a claim against the agent may be viable in addition to any claim against the
        carrier.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What to Do After Discovering Underinsurance
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        If a policyholder discovers after a loss that their coverage limits are inadequate,
        several steps should be taken immediately:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>Do not accept the carrier&rsquo;s first estimate as final.</strong> The
          carrier&rsquo;s initial estimate of the loss may itself be low, compounding the
          underinsurance problem. Obtain independent estimates from licensed contractors.
        </li>
        <li>
          <strong>Request the carrier&rsquo;s replacement cost estimate from inception.</strong>{' '}
          Under California law, policyholders have the right to review the documentation the
          carrier used to set the coverage limit. Errors in that estimate may support claims
          for reformation or additional coverage.
        </li>
        <li>
          <strong>Review all available endorsements.</strong> Check whether the policy includes
          extended replacement cost, ordinance or law coverage, or other endorsements that may
          provide additional funds beyond the stated dwelling limit.
        </li>
        <li>
          <strong>Consult with a Public Adjuster and an attorney.</strong> Underinsurance
          claims involve both{' '}
          <Link href="/resources/scope-of-loss" className="text-[#2E74B5] underline hover:text-blue-900">
            scope and valuation disputes
          </Link>{' '}
          (where a Public Adjuster can help maximize recovery within the policy limits) and
          potential coverage or bad faith claims (where an attorney may be needed to pursue
          recovery beyond the limits).
        </li>
        <li>
          <strong>Investigate whether other policyholders are similarly affected.</strong> If
          the underinsurance appears to be part of a broader pattern, connecting with other
          affected policyholders (through organizations like United Policyholders or through
          class counsel) can strengthen individual claims and enable class-wide relief.
        </li>
      </ul>

      {/* ── Related Reading ── */}
      <CalloutBox variant="tip" title="Related Reading">
        <ul className="list-disc pl-4 space-y-1">
          <li>
            <Link href="/resources/coinsurance-penalty" className="text-[#2E74B5] underline hover:text-blue-900">
              Coinsurance Penalties Explained
            </Link>{' '}
            &mdash; How the penalty works and why it catches policyholders off guard
          </li>
          <li>
            <Link href="/resources/replacement-cost-vs-guaranteed" className="text-[#2E74B5] underline hover:text-blue-900">
              Replacement Cost vs. Guaranteed Replacement Cost
            </Link>{' '}
            &mdash; Understanding the critical difference in coverage endorsements
          </li>
          <li>
            <Link href="/resources/signs-you-are-underinsured" className="text-[#2E74B5] underline hover:text-blue-900">
              Signs You Are Underinsured
            </Link>{' '}
            &mdash; Red flags that your coverage limits may be inadequate
          </li>
          <li>
            <Link href="/resources/misleading-replacement-cost-estimates" className="text-[#2E74B5] underline hover:text-blue-900">
              Misleading Replacement Cost Estimates
            </Link>{' '}
            &mdash; How carrier estimation tools produce inaccurate results
          </li>
        </ul>
      </CalloutBox>

      {/* ── Sources & Further Reading ── */}
      <h2 className="text-2xl font-bold text-[#1F3964] mb-4 mt-10">
        Sources &amp; Further Reading
      </h2>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>
          <strong>United Policyholders</strong> &mdash; A nationally recognized nonprofit
          consumer advocacy organization that has extensively documented underinsurance
          rates following California wildfires and other catastrophes. United Policyholders
          provides resources for disaster survivors including coverage analysis tools and
          connections to policyholder attorneys. Search for their wildfire underinsurance
          research at uphelp.org.
        </li>
        <li>
          <strong>Cotchett, Pitre &amp; McCarthy, LLP</strong> &mdash; A California-based
          plaintiffs&rsquo; firm that has represented wildfire survivors in class and mass
          actions involving underinsurance and carrier valuation practices. Search for their
          wildfire litigation publications.
        </li>
        <li>
          <strong>Lieff Cabraser Heimann &amp; Bernstein, LLP</strong> &mdash; A national
          plaintiffs&rsquo; firm that has litigated insurance class actions, including
          claims involving systematic undervaluation of insured properties. Search for
          their insurance class action practice materials.
        </li>
        <li>
          <strong>Merlin Law Group</strong> &mdash; A nationally recognized policyholder
          advocacy firm whose attorneys have written extensively about the underinsurance
          crisis and the inadequacy of carrier replacement cost estimation tools. Search
          for their blog at propertyinsurancecoveragelaw.com.
        </li>
        <li>
          <strong>Policyholder-side coverage commentary</strong> &mdash; Published
          analyses from the national policyholder-side bar address broker and agent
          liability for coverage-placement failures, including underinsurance attributable
          to inadequate replacement-cost estimating.
        </li>
        <li>
          <strong>California Department of Insurance</strong> &mdash; The CDI has issued
          regulatory guidance on replacement cost estimation requirements under California
          Insurance Code Sections 10101&ndash;10103 and has investigated carrier valuation
          practices following major wildfire events. Search for CDI bulletins and notices
          at insurance.ca.gov.
        </li>
        <li>
          <strong>California Insurance Code &sect;&sect; 10101&ndash;10103.5 and
          &sect; 10103.4</strong> &mdash; The disclosure-delivery framework and the
          periodic replacement-cost-estimate requirement for residential property insurers
          in California. The substantive estimate methodology requirements appear in 10
          CCR &sect;&sect; 2695.180&ndash;2695.183. Available through
          leginfo.legislature.ca.gov.
        </li>
      </ul>

      {/* ── Disclaimer ── */}
      <CalloutBox variant="legal" title="Disclaimer">
        <p>
          This article is for general educational purposes only and does not constitute legal
          advice. Nothing in this article should be construed as a legal opinion or as a
          substitute for consultation with a qualified attorney. Insurance policies, regulations,
          and applicable law vary by state and by policy form. The class action cases referenced
          are illustrative of the types of claims that have been brought; this article does not
          represent that any particular outcome was reached or that similar claims will succeed
          in all circumstances. Consult a licensed attorney or Public Adjuster for advice on your
          specific situation.
        </p>
        <p className="mt-2">
          <strong>Author:</strong> Leland Coontz III, Licensed Public Adjuster, CA License #2B53445
        </p>
      </CalloutBox>

      <div className="bg-[#EFF4FB] border border-[#C5D9F0] rounded-xl p-6 text-center mt-8">
        <h3 className="text-lg font-bold text-[#1F3964] mb-2">
          Concerned About Underinsurance?
        </h3>
        <p className="text-gray-600 text-sm mb-4">
          A Licensed Public Adjuster can review your policy limits, compare them to independent
          replacement cost estimates, and help you understand whether your coverage is adequate
          before a loss occurs &mdash; or maximize your recovery if one already has.
        </p>
        <Link
          href="/contact"
          className="inline-block bg-[#C9A84C] hover:bg-[#A8872E] text-white font-semibold px-6 py-3 rounded-lg transition-colors"
        >
          Request a Free Claim Review &rarr;
        </Link>
      </div>
    </>
  )
}
