import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: 'Xactimate Is Not the Law: Why Carrier Estimates Are Not Binding on Your Claim',
  description:
    'Xactimate dominates insurance estimating, but it is not a legal standard. Verisk\'s own EULA disclaims pricing accuracy. Multiple federal courts have rejected Xactimate as determinative. California regulations require actual market costs. Learn why your insurer\'s Xactimate estimate is a starting point — not the final word.',
  summary:
    'Xactimate is an estimating tool, not a legal standard, and Verisk\'s own EULA disclaims its pricing accuracy. Courts have rejected it as determinative, and California requires actual market costs, so a carrier\'s Xactimate number is a starting point, not the final word.',
}

export default function Content() {
  return (
    <>
      <CalloutBox variant="legal" title="This Article Is Not Legal Advice">
        <p>
          This article is educational in nature and reflects the author&rsquo;s interpretation of insurance law as a Licensed Public Adjuster. It is not legal advice. Every claim involves unique facts, policy language, and circumstances. If you believe your insurer has improperly relied on Xactimate to underpay your claim, consult with a licensed attorney who specializes in insurance coverage disputes.
        </p>
      </CalloutBox>

      <p className="text-gray-700 leading-relaxed mb-4">
        If you have filed a property insurance claim in the last two decades, you have almost certainly received an estimate generated by Xactimate. The software, owned by Verisk Analytics through its Xactware Solutions subsidiary, is used by approximately 90% of property insurers in the United States. It has become so dominant that many adjusters, contractors, and even some attorneys treat a Xactimate estimate as though it were an authoritative determination of repair cost.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        It is not. Xactimate is a software tool. It generates estimates based on inputs provided by the user. Its pricing data is a baseline &mdash; a starting point for negotiation, not a ceiling on what repairs actually cost. And the company that makes it says so explicitly.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Despite this, insurance companies routinely present Xactimate estimates as though they represent the objective, final cost to repair damaged property. They tell policyholders that &ldquo;Xactimate says&rdquo; a repair costs a certain amount, as though the software were a regulatory body or a court. When a contractor&rsquo;s bid comes in higher, the carrier points to its Xactimate estimate and refuses to pay the difference.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This practice has no legal basis. Multiple federal courts have rejected Xactimate as a determinative measure of repair cost. State regulators require that estimates reflect actual local market conditions &mdash; not software defaults. And Verisk&rsquo;s own licensing agreement disclaims the accuracy of its pricing data.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Verisk&rsquo;s Own Disclaimer: The EULA That Carriers Ignore
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Every user of Xactimate agrees to an End User License Agreement (EULA) before using
        the software. Section 12.3 of the current Xactware EULA contains a disclaimer that
        insurance companies rarely mention to policyholders: Xactware &ldquo;do[es] not
        warrant the accuracy of pricing information in the Price Data,&rdquo; and Price Data
        &ldquo;is intended to represent historical information and should be used as a
        baseline or place to begin creation of an estimate.&rdquo; The EULA goes on to say
        Verisk provides Price Data for informational purposes only and that users must
        ensure that estimates reflect actual materials, equipment, and labor pricing &mdash;
        not just the software default. The full EULA is published on Verisk&rsquo;s site;
        the EULA was last broadly updated in April 2024, and the substance of this
        no-warranty-on-pricing disclaimer has been the subject of high-profile
        Restoration Industry Association advocacy and reporting.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Read that carefully. The company that makes Xactimate tells its own users that
        Price Data is a historical baseline and disclaims any warranty of pricing
        accuracy. It places the burden of verifying actual local market pricing squarely on
        the user &mdash; which, in an insurance claim, is the carrier&rsquo;s adjuster.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        When an insurance company presents a Xactimate estimate as the final determination
        of what your repairs cost, it is treating as authoritative a tool that its own
        manufacturer disclaims warranty over. The carrier has agreed, by accepting the
        EULA, that pricing should be verified against actual conditions. When the carrier
        skips that verification and simply pays the Xactimate default, it is not following
        the software manufacturer&rsquo;s own instructions.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4 text-sm italic">
        The current Xactware EULA is published at{' '}
        <a href="https://www.verisk.com/privacy-policies/xactware-eula/" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">verisk.com/privacy-policies/xactware-eula/</a>.
        Verify the current text directly before relying on a specific phrasing, as Verisk
        periodically updates the agreement.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Who Owns Xactimate &mdash; and Why It Matters
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Understanding Xactimate&rsquo;s ownership structure helps explain why its pricing
        defaults may not reflect actual repair costs. Xactimate is developed by Xactware
        Solutions, which is a subsidiary of Verisk Analytics. The Insurance Services Office
        (ISO) &mdash; Verisk&rsquo;s principal predecessor &mdash; was founded as a
        not-for-profit consortium on April 1, 1971, consolidating various property/casualty
        rating bureaus into a single information provider for the insurance industry. ISO
        transitioned to for-profit status in 1997, and Verisk Analytics was established in
        2008 to serve as ISO&rsquo;s parent holding company. Verisk acquired Xactware in
        2006 (before forming the Verisk holding entity) and went public in October 2009 in
        what was then the largest U.S. IPO of the year.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Verisk&rsquo;s primary customers are insurance companies. Its revenue depends on selling products and services to the insurance industry. While Verisk maintains that its pricing data is objective and market-based, the reality is that the company&rsquo;s financial incentives are aligned with the interests of carriers, not policyholders. When Xactimate&rsquo;s default pricing consistently comes in below what contractors actually charge, that is not a coincidence &mdash; it is a feature that makes the product attractive to its paying customers.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This does not mean Xactimate is inherently dishonest. It means that a tool designed primarily for insurance company use should not be treated as a neutral arbiter of repair costs. The software is a <em>tool</em>. Like any tool, its output depends entirely on the skill and judgment of the person using it &mdash; and on whether that person has adjusted the defaults to reflect actual local conditions.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What Xactimate Pricing Actually Represents
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate generates repair cost estimates using a database of material and labor prices organized by geographic region. Verisk collects pricing data through surveys, vendor reporting, and other sources, then publishes monthly or quarterly price lists that users can select when building an estimate.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Mike Fulton, Vice President of Claims at Verisk, has publicly described Xactimate pricing as reflecting a &ldquo;willing buyer and willing seller&rdquo; transaction &mdash; an idealized market condition that may or may not reflect the reality of a specific repair in a specific location at a specific time. Fulton has also acknowledged that when Xactimate produces a low estimate, the problem is typically that the user &ldquo;doesn&rsquo;t understand the policy&rdquo; or has failed to adjust the software&rsquo;s defaults for site-specific conditions.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The Restoration Industry Association (RIA) and Xactware have issued a joint statement acknowledging that standardized pricing is a starting point and that actual costs vary by market, season, project complexity, and labor availability. This joint statement reinforces what the EULA already says: the software produces a baseline, not a binding determination.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        In practice, several factors routinely cause Xactimate defaults to understate actual repair costs:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>Labor rates.</strong> Xactimate&rsquo;s default labor rates may not reflect prevailing wages in the specific market, particularly in high-cost metropolitan areas or after a disaster when demand for skilled labor surges.</li>
        <li><strong>Material pricing.</strong> Default material costs may lag behind actual market prices, especially during periods of supply chain disruption or demand surge following widespread catastrophic events.</li>
        <li><strong>Yield and waste factors.</strong> Default waste percentages may understate the actual material waste inherent in many repair scenarios, particularly for matching existing finishes or working in occupied structures.</li>
        <li><strong>Overhead and profit.</strong> The software includes a field for <Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">general contractor overhead and profit</Link>, but many carrier adjusters leave it at zero &mdash; effectively assuming no general contractor is needed even when multiple trades are involved.</li>
        <li><strong>Line item omissions.</strong> The estimate is only as complete as the adjuster makes it. Missing line items &mdash; permits, temporary protection, content manipulation, equipment charges &mdash; are not the software&rsquo;s fault, but they consistently reduce the estimate below actual cost.</li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        How Courts Have Treated Xactimate
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Reported decisions involving Xactimate are not uniformly favorable to either side,
        and policyholder counsel should be careful about generalizing. Several recent rulings
        have, in fact, gone <em>against</em> homeowners who tried to challenge a carrier
        for using Xactimate, holding that insurers are not contractually required to use any
        particular estimating method. See, for example, <em>Belotti v. State Farm Fire
        &amp; Cas. Co.</em>, 2025 U.S. Dist. LEXIS 54471 (M.D. Pa. Mar. 2025) (dismissing
        proposed class action where State Farm used Xactimate&apos;s &ldquo;new
        construction&rdquo; pricing), and <em>Sheahan v. State Farm Gen. Ins. Co.</em>,
        442 F. Supp. 3d 1178 (N.D. Cal. 2020) (dismissing wildfire victims&apos; antitrust
        and California UCL claims related to Xactimate pricing, with prejudice). These
        decisions are not a holding that Xactimate is correct &mdash; they decided
        narrower contract and antitrust questions &mdash; but the article would mislead a
        reader who took them as authority that Xactimate cannot be the carrier&rsquo;s
        starting point.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The earlier Katrina-era class action <em>Schafer v. State Farm Fire &amp; Cas.
        Co.</em>, 507 F. Supp. 2d 587 (E.D. La. 2007), examined plaintiffs&apos;
        allegations that State Farm pressured adjusters to use deflated Xactware
        pricing after the storm; the case is most useful as background for the policy
        critique of standardized pricing in disaster markets rather than as a
        substantive holding that Xactimate output is invalid.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The more defensible policyholder argument is not &ldquo;the courts have rejected
        Xactimate.&rdquo; It is the argument the software manufacturer itself makes in the
        EULA: the Price Data is a baseline that must be verified against the actual local
        market, and a printed Xactimate page is only as good as the inputs the adjuster
        selected. Where carriers run defaults and treat the output as final, the criticism
        is not that the case law has banned Xactimate &mdash; it is that the carrier has
        not satisfied its own software vendor&apos;s instructions for using the tool.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3">
        The ESX File: What the Native Output Reveals
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Separate from the case-law debate, the discovery question of whether a
        policyholder is entitled to the carrier&rsquo;s native Xactimate{' '}
        <Link href="/resources/esx-file-rights-xactimate" className="text-[#2E74B5] underline">ESX file</Link>{' '}
        has been actively litigated, with at least some federal magistrates ordering
        production of the native file rather than a flattened PDF. The ESX file contains
        all of the inputs, settings, price list selections, and adjustments (or lack
        thereof) that produced the final number. The exact ruling that controls in any
        specific case is jurisdiction-specific; before relying on a particular ESX-file
        order, an insured&apos;s attorney should verify it against the controlling
        precedent in the relevant district. For more on the practical mechanics of
        getting the native file, see our companion article.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The ESX-file analysis matters because a printed Xactimate estimate does not tell
        the full story. To evaluate whether the estimate is accurate, you need to see how
        it was built. If the adjuster selected an outdated price list, used default waste
        factors instead of site-specific ones, omitted applicable line items, or failed
        to include{' '}
        <Link href="/resources/three-trade-rule" className="text-[#2E74B5] underline">
          overhead and profit
        </Link>, all of that is visible in the ESX file.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        California Law: Estimates Must Reflect Actual Market Costs
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        California&rsquo;s Fair Claims Settlement Practices Regulations impose specific requirements on how insurers estimate repair costs. Title 10, California Code of Regulations, Section 2695.9 requires that:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>Repair estimates must restore damaged property to &ldquo;no less than its condition prior to the loss&rdquo; and reflect &ldquo;accepted trade standards for good and workmanlike construction.&rdquo;</li>
        <li>The insurer must verify that repair costs are &ldquo;accurate and representative of costs in the local market area.&rdquo;</li>
        <li>Labor costs are not subject to depreciation.</li>
        <li>The policyholder has the right to choose their own contractor.</li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        These requirements are fundamentally incompatible with treating Xactimate defaults as the final word on repair cost. A Xactimate estimate built using out-of-date price lists, default labor rates that don&rsquo;t reflect the local market, and zero overhead and profit does not meet the standard of being &ldquo;accurate and representative of costs in the local market area.&rdquo; The regulation requires the insurer to verify actual costs &mdash; not to generate a software estimate and call it done.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The California Department of Insurance has enforced these standards against carriers who rely on standardized estimates without verifying local market conditions. When an insurer&rsquo;s Xactimate estimate produces a number 30% below what local contractors are actually charging, that estimate does not comply with 10 CCR 2695.9.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Daily Journal Weighs In
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        On April 15, 2026, the <em>Daily Journal</em> published an article by attorneys{' '}
        <strong>Shant A. Karnikian</strong> (Managing Partner of Kabateck LLP) and{' '}
        <strong>Barret Alexander</strong> titled &ldquo;Xactimate is not the law: How
        insurers use one software program to underpay wildfire claims.&rdquo; The article
        examined the growing legal challenge to Xactimate&rsquo;s role in California
        wildfire claims, analyzing how insurers rely on the software &mdash; often using
        outdated data and adjustable inputs &mdash; to undervalue repair costs. The
        authors concluded that policyholder counsel should ground their challenges in
        actual market conditions and policy terms, rather than letting the carrier&rsquo;s
        Xactimate output stand unchallenged.{' '}
        <a href="https://www.dailyjournal.com/articles/390846-xactimate-is-not-the-law-how-insurers-use-one-software-program-to-underpay-wildfire-claims" target="_blank" rel="noopener noreferrer" className="text-[#2E74B5] underline">
          Read the Daily Journal article
        </a>{' '}
        (subscription required).
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What This Means for Your Claim
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        If your insurance company has offered you a settlement based on a Xactimate estimate, understand what you are looking at:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>It is a starting point.</strong> The manufacturer of the software says so. The courts say so. State regulators say so. A Xactimate estimate is one piece of evidence about what repairs might cost &mdash; it is not the final answer.</li>
        <li><strong>The inputs matter more than the output.</strong> A Xactimate estimate is only as accurate as the person who built it. If the adjuster used outdated pricing, default waste factors, or omitted line items, the estimate will be low &mdash; and the problem is the adjuster, not the software.</li>
        <li><strong>Your contractor&rsquo;s bid is relevant evidence.</strong> Courts have consistently held that actual contractor bids reflecting local market conditions are relevant to determining repair cost. Your insurer cannot dismiss a legitimate contractor bid simply because &ldquo;Xactimate says&rdquo; something different.</li>
        <li><strong>You can request the ESX file.</strong> The native Xactimate file contains all the settings and inputs that produced the estimate. Reviewing the ESX file is the most effective way to identify where the carrier&rsquo;s estimate departs from actual market conditions.</li>
        <li><strong>The carrier bears the burden of verification.</strong> Under Verisk&rsquo;s own EULA, the user is responsible for verifying that pricing reflects actual local costs. If the carrier simply ran the defaults without verification, the estimate does not meet the standard the software manufacturer set for its own product.</li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        How to Challenge a Xactimate-Based Estimate
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        If you believe your insurer&rsquo;s Xactimate estimate understates your repair costs, there are several concrete steps you can take:
      </p>
      <ol className="list-decimal pl-6 space-y-3 text-gray-700 mb-6">
        <li><strong>Get contractor bids.</strong> Obtain at least two bids from licensed, reputable contractors in your area. These bids reflect what your repairs actually cost in the current market.</li>
        <li><strong>Request the ESX file.</strong> Ask your insurer for the native Xactimate file, not just the printed estimate. Review it for outdated price lists, default settings, and <Link href="/resources/how-to-challenge-xactimate-estimate" className="text-[#2E74B5] underline">common errors</Link>.</li>
        <li><strong>Check the price list date.</strong> Xactimate pricing is tied to a specific price list, updated monthly or quarterly. If the carrier used a price list from before your loss date or from a period when prices have since increased, the estimate may be based on stale data.</li>
        <li><strong>Verify labor rates.</strong> Compare the Xactimate labor rates against what contractors in your area actually charge. In many markets, Xactimate&rsquo;s default labor rates are significantly below prevailing wages.</li>
        <li><strong>Check for missing line items.</strong> A <Link href="/resources/xactimate-line-item-manipulation" className="text-[#2E74B5] underline">common carrier tactic</Link> is to omit line items that are necessary for the repair. Permits, content manipulation, temporary protection, equipment rental, and cleanup are frequently left out.</li>
        <li><strong>Engage a professional.</strong> A <Link href="/resources/public-adjuster" className="text-[#2E74B5] underline">licensed Public Adjuster</Link> or an attorney experienced in insurance claims can build a competing Xactimate estimate using the correct inputs and challenge the carrier&rsquo;s estimate line by line.</li>
      </ol>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Bottom Line
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate is a tool. It is a useful tool when used properly &mdash; with current pricing data, site-specific adjustments, complete line items, and professional judgment. But it is not the law. It is not a regulation. It is not a court ruling. And it is not binding on policyholders.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        When your insurance company tells you that &ldquo;Xactimate says&rdquo; your repairs cost a certain amount, the correct response is: &ldquo;Xactimate is a starting point. What do my repairs actually cost?&rdquo;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The manufacturer of the software agrees. The courts agree. And so should your insurer.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Related Articles
      </h2>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">Overhead &amp; Profit: When Your Claim Should Include O&amp;P</Link></li>
        <li><Link href="/resources/three-trade-rule" className="text-[#2E74B5] underline">The Three-Trade Rule: Why Your Insurance Company Owes O&amp;P</Link></li>
        <li><Link href="/resources/how-to-challenge-xactimate-estimate" className="text-[#2E74B5] underline">How to Challenge a Xactimate Estimate</Link></li>
        <li><Link href="/resources/esx-file-rights-xactimate" className="text-[#2E74B5] underline">ESX File Rights: Getting the Native Xactimate File</Link></li>
        <li><Link href="/resources/xactimate-pricing-user-responsibility" className="text-[#2E74B5] underline">When Xactimate Estimates Are Low, Blame the User &mdash; Not the Software</Link></li>
        <li><Link href="/resources/sub-bids-vs-xactimate-pricing" className="text-[#2E74B5] underline">When a Contractor&rsquo;s Bid Overrides Xactimate</Link></li>
      </ul>
      <hr className="my-8 border-gray-300" />
      <p className="text-sm text-gray-500 italic">
        This article is for informational purposes only and does not constitute legal advice.
        Insurance policies and applicable law vary by state and by policy form. Consult with a
        licensed professional regarding your specific situation.
      </p>
      <p className="text-sm text-gray-500 mt-4 italic">
        Written by Leland Coontz III, Licensed Public Adjuster, CA License #2B53445.
      </p>
    </>
  )
}
