import Link from 'next/link'
import { CalloutBox } from '@/components/content/CalloutBox'

export const meta = {
  title: 'Xactimate Is Not the Law: Why Carrier Estimates Are Not Binding on Your Claim',
  description:
    'Xactimate dominates insurance estimating, but it is not a legal standard. Verisk\'s own EULA disclaims pricing accuracy. Multiple federal courts have rejected Xactimate as determinative. California regulations require actual market costs. Learn why your insurer\'s Xactimate estimate is a starting point — not the final word.',
  summary:
    'Xactimate is an estimating tool, not a legal standard, and Verisk\'s own EULA disclaims its pricing accuracy. Courts have rejected it as determinative, and California requires actual market costs, so a carrier\'s Xactimate number is a starting point, not the final word.',
}

export default function Content() {
  return (
    <>
      <CalloutBox variant="legal" title="This Article Is Not Legal Advice">
        <p>
          This article is educational in nature and reflects the author&rsquo;s interpretation of insurance law as a Licensed Public Adjuster. It is not legal advice. Every claim involves unique facts, policy language, and circumstances. If you believe your insurer has improperly relied on Xactimate to underpay your claim, consult with a licensed attorney who specializes in insurance coverage disputes.
        </p>
      </CalloutBox>

      <p className="text-gray-700 leading-relaxed mb-4">
        If you have filed a property insurance claim in the last two decades, you have almost certainly received an estimate generated by Xactimate. The software, owned by Verisk Analytics through its Xactware Solutions subsidiary, is used by approximately 90% of property insurers in the United States. It has become so dominant that many adjusters, contractors, and even some attorneys treat a Xactimate estimate as though it were an authoritative determination of repair cost.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        It is not. Xactimate is a software tool. It generates estimates based on inputs provided by the user. Its pricing data is a baseline &mdash; a starting point for negotiation, not a ceiling on what repairs actually cost. And the company that makes it says so explicitly.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Despite this, insurance companies routinely present Xactimate estimates as though they represent the objective, final cost to repair damaged property. They tell policyholders that &ldquo;Xactimate says&rdquo; a repair costs a certain amount, as though the software were a regulatory body or a court. When a contractor&rsquo;s bid comes in higher, the carrier points to its Xactimate estimate and refuses to pay the difference.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This practice has no legal basis. Multiple federal courts have rejected Xactimate as a determinative measure of repair cost. State regulators require that estimates reflect actual local market conditions &mdash; not software defaults. And Verisk&rsquo;s own licensing agreement disclaims the accuracy of its pricing data.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Verisk&rsquo;s Own Disclaimer: The EULA That Carriers Ignore
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Every user of Xactimate agrees to an End User License Agreement (EULA) before using the software. Section 12.3 of the Xactimate EULA contains a critical disclaimer that insurance companies rarely mention to policyholders:
      </p>
      <blockquote className="border-l-4 border-[#C9A84C] bg-amber-50 p-4 my-6 text-gray-700 text-sm leading-relaxed italic">
        &ldquo;Pricing data provided by Xactware is intended as a baseline to begin the estimation process. Xactware does not guarantee the accuracy, reliability, or completeness of pricing data for any particular geographic area or project. Users are responsible for verifying that pricing is accurate and representative of actual costs in the applicable market.&rdquo;
      </blockquote>
      <p className="text-gray-700 leading-relaxed mb-4">
        Read that carefully. The company that makes Xactimate tells its own users that the pricing is a &ldquo;baseline to begin the estimation process.&rdquo; It does not guarantee accuracy. It does not guarantee reliability. It does not guarantee completeness. And it places the burden of verification squarely on the user &mdash; which, in an insurance claim, is the carrier&rsquo;s adjuster.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        When an insurance company presents a Xactimate estimate as the final determination of what your repairs cost, it is treating as authoritative a tool that its own manufacturer says is merely a starting point. The carrier has agreed, by accepting the EULA, that the pricing must be verified against actual local market conditions. When the carrier skips that verification and simply pays the Xactimate default, it is not following the software manufacturer&rsquo;s own instructions.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Who Owns Xactimate &mdash; and Why It Matters
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Understanding Xactimate&rsquo;s ownership structure helps explain why its pricing defaults may not reflect actual repair costs. Xactimate is developed by Xactware Solutions, which is a subsidiary of Verisk Analytics. Verisk was formed in 1971 as the Insurance Services Office (ISO) &mdash; an organization created by and for the insurance industry to provide data, analytics, and risk assessment tools. Verisk acquired Xactware in 2006 and went public in 2009.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Verisk&rsquo;s primary customers are insurance companies. Its revenue depends on selling products and services to the insurance industry. While Verisk maintains that its pricing data is objective and market-based, the reality is that the company&rsquo;s financial incentives are aligned with the interests of carriers, not policyholders. When Xactimate&rsquo;s default pricing consistently comes in below what contractors actually charge, that is not a coincidence &mdash; it is a feature that makes the product attractive to its paying customers.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This does not mean Xactimate is inherently dishonest. It means that a tool designed primarily for insurance company use should not be treated as a neutral arbiter of repair costs. The software is a <em>tool</em>. Like any tool, its output depends entirely on the skill and judgment of the person using it &mdash; and on whether that person has adjusted the defaults to reflect actual local conditions.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What Xactimate Pricing Actually Represents
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate generates repair cost estimates using a database of material and labor prices organized by geographic region. Verisk collects pricing data through surveys, vendor reporting, and other sources, then publishes monthly or quarterly price lists that users can select when building an estimate.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        Mike Fulton, Vice President of Claims at Verisk, has publicly described Xactimate pricing as reflecting a &ldquo;willing buyer and willing seller&rdquo; transaction &mdash; an idealized market condition that may or may not reflect the reality of a specific repair in a specific location at a specific time. Fulton has also acknowledged that when Xactimate produces a low estimate, the problem is typically that the user &ldquo;doesn&rsquo;t understand the policy&rdquo; or has failed to adjust the software&rsquo;s defaults for site-specific conditions.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The Restoration Industry Association (RIA) and Xactware have issued a joint statement acknowledging that standardized pricing is a starting point and that actual costs vary by market, season, project complexity, and labor availability. This joint statement reinforces what the EULA already says: the software produces a baseline, not a binding determination.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        In practice, several factors routinely cause Xactimate defaults to understate actual repair costs:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>Labor rates.</strong> Xactimate&rsquo;s default labor rates may not reflect prevailing wages in the specific market, particularly in high-cost metropolitan areas or after a disaster when demand for skilled labor surges.</li>
        <li><strong>Material pricing.</strong> Default material costs may lag behind actual market prices, especially during periods of supply chain disruption or demand surge following widespread catastrophic events.</li>
        <li><strong>Yield and waste factors.</strong> Default waste percentages may understate the actual material waste inherent in many repair scenarios, particularly for matching existing finishes or working in occupied structures.</li>
        <li><strong>Overhead and profit.</strong> The software includes a field for <Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">general contractor overhead and profit</Link>, but many carrier adjusters leave it at zero &mdash; effectively assuming no general contractor is needed even when multiple trades are involved.</li>
        <li><strong>Line item omissions.</strong> The estimate is only as complete as the adjuster makes it. Missing line items &mdash; permits, temporary protection, content manipulation, equipment charges &mdash; are not the software&rsquo;s fault, but they consistently reduce the estimate below actual cost.</li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Courts Have Spoken: Xactimate Is Not Determinative
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Multiple federal courts have addressed the role of Xactimate in insurance disputes, and the consensus is clear: a Xactimate estimate is evidence of repair cost, but it is not determinative. Courts have consistently held that Xactimate output does not bind policyholders, does not establish the actual cost of repair, and does not relieve insurers of their obligation to pay what repairs actually cost.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3">
        Belotti v. Allstate Fire &amp; Casualty Insurance Co. (M.D. Pa. 2025)
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The court rejected Allstate&rsquo;s argument that its Xactimate estimate represented the actual cost of repair. The court found that a software-generated estimate, standing alone, does not establish what it actually costs to repair damaged property in a specific location. The policyholder&rsquo;s contractor bids and testimony about actual market conditions were relevant evidence that the jury could consider.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3">
        Schafer v. State Farm Fire &amp; Casualty Co. (E.D. La. 2007)
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        In this post-Hurricane Katrina case, the court questioned the reliability of Xactimate estimates in a market where labor and material costs had been dramatically affected by the catastrophe. The court recognized that standardized software pricing may not reflect the actual cost environment following a disaster &mdash; precisely the situation where accurate cost estimation matters most.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3">
        Sheahan v. CSAA Insurance Exchange (N.D. Cal. 2020)
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The court addressed whether a Xactimate estimate could serve as the definitive measure of replacement cost. The court found that the insurer could not rely solely on its Xactimate output to establish the cost of repair when the policyholder presented contrary evidence of what repairs actually cost in the local market.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3">
        Skender v. Auto-Owners Insurance Co. (S.D. Ind. 2024)
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The court rejected the carrier&rsquo;s reliance on Xactimate as the sole basis for its valuation. The decision reinforced the principle that software-generated estimates are one form of evidence among many, and that actual contractor costs, local market conditions, and the specific circumstances of the repair are all relevant to determining what a loss actually costs to repair.
      </p>

      <h3 className="text-xl font-bold text-[#1F3964] mb-3">
        The ESX File and Judge Varholak&rsquo;s Ruling
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        In a landmark discovery ruling, Magistrate Judge Michael E. Varholak of the District of Colorado held that policyholders are entitled to the underlying <Link href="/resources/esx-file-rights-xactimate" className="text-[#2E74B5] underline">ESX file</Link> &mdash; the native Xactimate file &mdash; from the carrier&rsquo;s estimate. The ESX file contains all the inputs, settings, price list selections, and adjustments (or lack thereof) that produced the final number. Judge Varholak&rsquo;s ruling recognized that a printed Xactimate estimate does not tell the full story. To evaluate whether the estimate is accurate, you need to see how it was built.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        This ruling is significant because it treats Xactimate estimates as what they are: user-generated outputs that depend on the choices made by the person who created them. If the adjuster selected an outdated price list, used default waste factors instead of site-specific ones, omitted applicable line items, or failed to include <Link href="/resources/three-trade-rule" className="text-[#2E74B5] underline">overhead and profit</Link>, all of that is visible in the ESX file.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        California Law: Estimates Must Reflect Actual Market Costs
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        California&rsquo;s Fair Claims Settlement Practices Regulations impose specific requirements on how insurers estimate repair costs. Title 10, California Code of Regulations, Section 2695.9 requires that:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li>Repair estimates must restore damaged property to &ldquo;no less than its condition prior to the loss&rdquo; and reflect &ldquo;accepted trade standards for good and workmanlike construction.&rdquo;</li>
        <li>The insurer must verify that repair costs are &ldquo;accurate and representative of costs in the local market area.&rdquo;</li>
        <li>Labor costs are not subject to depreciation.</li>
        <li>The policyholder has the right to choose their own contractor.</li>
      </ul>
      <p className="text-gray-700 leading-relaxed mb-4">
        These requirements are fundamentally incompatible with treating Xactimate defaults as the final word on repair cost. A Xactimate estimate built using out-of-date price lists, default labor rates that don&rsquo;t reflect the local market, and zero overhead and profit does not meet the standard of being &ldquo;accurate and representative of costs in the local market area.&rdquo; The regulation requires the insurer to verify actual costs &mdash; not to generate a software estimate and call it done.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The California Department of Insurance has enforced these standards against carriers who rely on standardized estimates without verifying local market conditions. When an insurer&rsquo;s Xactimate estimate produces a number 30% below what local contractors are actually charging, that estimate does not comply with 10 CCR 2695.9.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Daily Journal Weighs In
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        In an April 2026 article published in the <em>Daily Journal</em>, attorneys George Karnikian and Armen Alexander examined the growing legal challenge to Xactimate&rsquo;s role in insurance claims. The article analyzed recent case law, regulatory enforcement actions, and the fundamental tension between standardized software pricing and the legal obligation to pay what repairs actually cost. The authors concluded that treating Xactimate as determinative is legally indefensible and that policyholders and their advocates should challenge carrier estimates that rely on unverified software defaults.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        What This Means for Your Claim
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        If your insurance company has offered you a settlement based on a Xactimate estimate, understand what you are looking at:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><strong>It is a starting point.</strong> The manufacturer of the software says so. The courts say so. State regulators say so. A Xactimate estimate is one piece of evidence about what repairs might cost &mdash; it is not the final answer.</li>
        <li><strong>The inputs matter more than the output.</strong> A Xactimate estimate is only as accurate as the person who built it. If the adjuster used outdated pricing, default waste factors, or omitted line items, the estimate will be low &mdash; and the problem is the adjuster, not the software.</li>
        <li><strong>Your contractor&rsquo;s bid is relevant evidence.</strong> Courts have consistently held that actual contractor bids reflecting local market conditions are relevant to determining repair cost. Your insurer cannot dismiss a legitimate contractor bid simply because &ldquo;Xactimate says&rdquo; something different.</li>
        <li><strong>You can request the ESX file.</strong> The native Xactimate file contains all the settings and inputs that produced the estimate. Reviewing the ESX file is the most effective way to identify where the carrier&rsquo;s estimate departs from actual market conditions.</li>
        <li><strong>The carrier bears the burden of verification.</strong> Under Verisk&rsquo;s own EULA, the user is responsible for verifying that pricing reflects actual local costs. If the carrier simply ran the defaults without verification, the estimate does not meet the standard the software manufacturer set for its own product.</li>
      </ul>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        How to Challenge a Xactimate-Based Estimate
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        If you believe your insurer&rsquo;s Xactimate estimate understates your repair costs, there are several concrete steps you can take:
      </p>
      <ol className="list-decimal pl-6 space-y-3 text-gray-700 mb-6">
        <li><strong>Get contractor bids.</strong> Obtain at least two bids from licensed, reputable contractors in your area. These bids reflect what your repairs actually cost in the current market.</li>
        <li><strong>Request the ESX file.</strong> Ask your insurer for the native Xactimate file, not just the printed estimate. Review it for outdated price lists, default settings, and <Link href="/resources/how-to-challenge-xactimate-estimate" className="text-[#2E74B5] underline">common errors</Link>.</li>
        <li><strong>Check the price list date.</strong> Xactimate pricing is tied to a specific price list, updated monthly or quarterly. If the carrier used a price list from before your loss date or from a period when prices have since increased, the estimate may be based on stale data.</li>
        <li><strong>Verify labor rates.</strong> Compare the Xactimate labor rates against what contractors in your area actually charge. In many markets, Xactimate&rsquo;s default labor rates are significantly below prevailing wages.</li>
        <li><strong>Check for missing line items.</strong> A <Link href="/resources/xactimate-line-item-manipulation" className="text-[#2E74B5] underline">common carrier tactic</Link> is to omit line items that are necessary for the repair. Permits, content manipulation, temporary protection, equipment rental, and cleanup are frequently left out.</li>
        <li><strong>Engage a professional.</strong> A <Link href="/resources/public-adjuster" className="text-[#2E74B5] underline">licensed public adjuster</Link> or an attorney experienced in insurance claims can build a competing Xactimate estimate using the correct inputs and challenge the carrier&rsquo;s estimate line by line.</li>
      </ol>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        The Bottom Line
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Xactimate is a tool. It is a useful tool when used properly &mdash; with current pricing data, site-specific adjustments, complete line items, and professional judgment. But it is not the law. It is not a regulation. It is not a court ruling. And it is not binding on policyholders.
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        When your insurance company tells you that &ldquo;Xactimate says&rdquo; your repairs cost a certain amount, the correct response is: &ldquo;Xactimate is a starting point. What do my repairs actually cost?&rdquo;
      </p>
      <p className="text-gray-700 leading-relaxed mb-4">
        The manufacturer of the software agrees. The courts agree. And so should your insurer.
      </p>

      <h2 className="text-2xl font-bold text-[#1F3964] mb-4">
        Related Articles
      </h2>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
        <li><Link href="/resources/overhead-and-profit" className="text-[#2E74B5] underline">Overhead &amp; Profit: When Your Claim Should Include O&amp;P</Link></li>
        <li><Link href="/resources/three-trade-rule" className="text-[#2E74B5] underline">The Three-Trade Rule: Why Your Insurance Company Owes O&amp;P</Link></li>
        <li><Link href="/resources/how-to-challenge-xactimate-estimate" className="text-[#2E74B5] underline">How to Challenge a Xactimate Estimate</Link></li>
        <li><Link href="/resources/esx-file-rights-xactimate" className="text-[#2E74B5] underline">ESX File Rights: Getting the Native Xactimate File</Link></li>
        <li><Link href="/resources/xactimate-pricing-user-responsibility" className="text-[#2E74B5] underline">When Xactimate Estimates Are Low, Blame the User &mdash; Not the Software</Link></li>
        <li><Link href="/resources/sub-bids-vs-xactimate-pricing" className="text-[#2E74B5] underline">When a Contractor&rsquo;s Bid Overrides Xactimate</Link></li>
      </ul>
      <hr className="my-8 border-gray-300" />
      <p className="text-sm text-gray-500 italic">
        This article is for informational purposes only and does not constitute legal advice.
        Insurance policies and applicable law vary by state and by policy form. Consult with a
        licensed professional regarding your specific situation.
      </p>
      <p className="text-sm text-gray-500 mt-4 italic">
        Written by Leland Coontz III, Licensed Public Adjuster, CA License #2B53445.
      </p>
    </>
  )
}
