/**
 * Excel export utility using SheetJS (xlsx).
 * Runs entirely in the browser — no server required.
 *
 * Generates a workbook with three sheets:
 *   1. My Checked Items  — only items the user marked as owned
 *   2. Complete List     — all 3,750 items (for reference / future use)
 *   3. Instructions      — how to use the file / PA contact info
 */

import * as XLSX from 'xlsx'
import type { ContentRoom, InventoryState } from '@/lib/types'

const PA_CONTACT = 'InsuranceClaimsInfo.com  |  Leland Coontz III, CA Lic. #2B53445  |  (Contact via website)'

export function exportToExcel(
  rooms: ContentRoom[],
  state: InventoryState,
  userName?: string
) {
  const wb = XLSX.utils.book_new()
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  // ── Sheet 1: Checked items only ─────────────────────────────────────────
  const checkedRows: (string | number)[][] = [
    ['PERSONAL PROPERTY INVENTORY', '', '', '', '', ''],
    [`Prepared for: ${userName ?? 'Claimant'}`, '', '', `Date: ${today}`, '', ''],
    ['', '', '', '', '', ''],
    ['Room', 'Category', 'Item', 'Quantity', 'Unit Value ($)', 'Total Value ($)'],
  ]

  let grandTotal = 0

  for (const room of rooms) {
    for (const cat of room.categories) {
      for (const item of cat.items) {
        if (!state.checked.has(item.id)) continue
        const d = state.details[item.id]
        const qty = parseInt(d?.qty ?? '1') || 1
        const unitVal = parseFloat(d?.value ?? '0') || 0
        const lineTotal = qty * unitVal
        grandTotal += lineTotal
        checkedRows.push([room.name, cat.name, item.name, qty, unitVal || '', lineTotal || ''])
      }
    }
  }

  checkedRows.push(['', '', '', '', 'GRAND TOTAL', grandTotal || ''])
  checkedRows.push(['', '', '', '', '', ''])
  checkedRows.push([PA_CONTACT, '', '', '', '', ''])

  const ws1 = XLSX.utils.aoa_to_sheet(checkedRows)
  ws1['!cols'] = [{ wch: 20 }, { wch: 28 }, { wch: 40 }, { wch: 10 }, { wch: 16 }, { wch: 16 }]
  XLSX.utils.book_append_sheet(wb, ws1, 'My Checked Items')

  // ── Sheet 2: Complete list (all items) ──────────────────────────────────
  const allRows: (string | number)[][] = [
    ['Room', 'Category', 'Item', 'I Own This (Y)', 'Quantity', 'Est. Value ($)', 'Notes'],
  ]

  for (const room of rooms) {
    for (const cat of room.categories) {
      for (const item of cat.items) {
        const owned = state.checked.has(item.id)
        const d = state.details[item.id]
        allRows.push([
          room.name,
          cat.name,
          item.name,
          owned ? 'Y' : '',
          owned ? (parseInt(d?.qty ?? '1') || 1) : '',
          owned && d?.value ? parseFloat(d.value) : '',
          d?.notes ?? '',
        ])
      }
    }
  }

  const ws2 = XLSX.utils.aoa_to_sheet(allRows)
  ws2['!cols'] = [{ wch: 20 }, { wch: 28 }, { wch: 40 }, { wch: 14 }, { wch: 10 }, { wch: 16 }, { wch: 30 }]
  XLSX.utils.book_append_sheet(wb, ws2, 'Complete List')

  // ── Sheet 3: Instructions ───────────────────────────────────────────────
  const instrRows = [
    ['INSTRUCTIONS & TIPS'],
    [''],
    ['This spreadsheet was generated by InsuranceClaimsInfo.com'],
    [''],
    ['SHEET 1 — MY CHECKED ITEMS'],
    ['  Items you marked as owned, with quantities and estimated values.'],
    ['  This is your primary working document for your insurance claim.'],
    [''],
    ['SHEET 2 — COMPLETE LIST'],
    ['  All 3,750+ items for reference. Add Y in column D for any you missed.'],
    [''],
    ['TIPS FOR MAXIMIZING YOUR CLAIM:'],
    ['  1. Go room by room — do not rush. Take breaks and come back.'],
    ['  2. Look for receipts, bank/credit card statements, Amazon orders.'],
    ['  3. Check your photos (Google Photos, iCloud) for images of items.'],
    ['  4. Ask family members — they often remember items you forget.'],
    ['  5. Seasonal items (holiday decor, ski gear, camping) are often overlooked.'],
    ['  6. Small items add up fast: office supplies, cleaning products, spices.'],
    ['  7. In California, you are entitled to Actual Cash Value (ACV) first,'],
    ['     then Replacement Cost Value (RCV) once items are replaced.'],
    ['  8. Keep all receipts for replacement purchases.'],
    [''],
    ['YOUR RIGHTS UNDER CALIFORNIA LAW:'],
    ['  • Fair Claims Settlement Practices Act (10 CCR 2695)'],
    ['  • Insurer must respond to your claim within 15 days'],
    ['  • Insurer must accept or deny within 40 days of proof of loss'],
    ['  • You have the right to a public adjuster to represent you'],
    [''],
    ['NEED PROFESSIONAL HELP WITH YOUR CLAIM?'],
    [PA_CONTACT],
    ['Visit InsuranceClaimsInfo.com for free guides and resources.'],
  ]

  const ws3 = XLSX.utils.aoa_to_sheet(instrRows)
  ws3['!cols'] = [{ wch: 80 }]
  XLSX.utils.book_append_sheet(wb, ws3, 'Instructions')

  // ── Save ────────────────────────────────────────────────────────────────
  const filename = `Personal-Property-Inventory-${new Date().toISOString().slice(0, 10)}.xlsx`
  XLSX.writeFile(wb, filename)
}
