/**
 * Build-time script to generate related article mappings.
 * Uses keyword overlap + tag similarity (audience, claimType, subcategory) for scoring.
 * Reads from article-registry.json and article-tags.json (generated by other scripts).
 * Run with: npx tsx scripts/generate-related-articles.ts
 */

import * as fs from 'fs'
import * as path from 'path'

const DATA_DIR = path.resolve(__dirname, '../public/data')
const registryPath = path.join(DATA_DIR, 'article-registry.json')
const tagsPath = path.join(DATA_DIR, 'article-tags.json')

const registry: Record<string, { title: string; description: string }> =
  JSON.parse(fs.readFileSync(registryPath, 'utf-8'))

const tagsData: Record<string, {
  audience?: string[]
  claimType?: string[]
  contentType?: string
  jurisdiction?: string
  subcategory?: string
}> = JSON.parse(fs.readFileSync(tagsPath, 'utf-8'))

interface Article {
  slug: string
  title: string
  description: string
  keywords: string[]
  audience: string[]
  claimTypes: string[]
  subcategory: string | null
  contentType: string | null
}

const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of',
  'with', 'by', 'from', 'is', 'it', 'its', 'are', 'was', 'were', 'be', 'been',
  'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
  'should', 'may', 'might', 'can', 'this', 'that', 'these', 'those', 'what',
  'which', 'who', 'whom', 'how', 'when', 'where', 'why', 'not', 'no', 'nor',
  'if', 'then', 'than', 'so', 'as', 'up', 'out', 'about', 'into', 'over',
  'after', 'before', 'between', 'under', 'again', 'further', 'once', 'here',
  'there', 'all', 'each', 'every', 'both', 'few', 'more', 'most', 'other',
  'some', 'such', 'only', 'own', 'same', 'too', 'very', 'just', 'because',
  'through', 'during', 'while', 'also', 'their', 'they', 'them', 'your', 'you',
  'we', 'our', 'my', 'me', 'he', 'she', 'him', 'her', 'his',
  'learn', 'guide', 'complete', 'comprehensive', 'need', 'know', 'understanding',
  'insurance', 'claim', 'claims', 'insurer', 'policy', 'california',
])

function extractKeywords(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 2 && !STOP_WORDS.has(w))
}

const articles: Article[] = Object.entries(registry).map(([slug, meta]) => {
  const tags = tagsData[slug] || {}
  const keywords = [...new Set([
    ...extractKeywords(meta.title),
    ...extractKeywords(meta.description),
    ...slug.split('-').filter(w => w.length > 2 && !STOP_WORDS.has(w)),
  ])]
  return {
    slug,
    title: meta.title,
    description: meta.description,
    keywords,
    audience: tags.audience || [],
    claimTypes: tags.claimType || [],
    subcategory: tags.subcategory || null,
    contentType: tags.contentType || null,
  }
})

console.log(`Processing ${articles.length} articles for cross-references...`)

// Build keyword-to-articles index
const keywordIndex: Record<string, Set<number>> = {}
articles.forEach((article, idx) => {
  for (const kw of article.keywords) {
    if (!keywordIndex[kw]) keywordIndex[kw] = new Set()
    keywordIndex[kw].add(idx)
  }
})

// Scoring weights
const KEYWORD_WEIGHT = 1.0
const CLAIM_TYPE_WEIGHT = 0.3
const SUBCATEGORY_WEIGHT = 0.4
const AUDIENCE_WEIGHT = 0.15

function tagOverlap(a: string[], b: string[]): number {
  if (a.length === 0 || b.length === 0) return 0
  const setB = new Set(b)
  const shared = a.filter(x => setB.has(x)).length
  return shared / Math.max(a.length, b.length)
}

const relatedMap: Record<string, string[]> = {}

for (let i = 0; i < articles.length; i++) {
  const article = articles[i]
  const scores: { idx: number; score: number }[] = []

  // Gather keyword candidates
  const candidateCounts: Record<number, number> = {}
  for (const kw of article.keywords) {
    const matches = keywordIndex[kw]
    if (!matches || matches.size > articles.length * 0.3) continue
    for (const j of matches) {
      if (j === i) continue
      candidateCounts[j] = (candidateCounts[j] || 0) + 1
    }
  }

  for (const [jStr, count] of Object.entries(candidateCounts)) {
    const j = parseInt(jStr)
    const other = articles[j]

    // Keyword similarity (modified Jaccard)
    const keywordScore = count / Math.sqrt(article.keywords.length * other.keywords.length)

    // Tag-based boosts
    const claimTypeBoost = tagOverlap(article.claimTypes, other.claimTypes) * CLAIM_TYPE_WEIGHT
    const audienceBoost = tagOverlap(article.audience, other.audience) * AUDIENCE_WEIGHT
    const subcategoryBoost =
      (article.subcategory && article.subcategory === other.subcategory) ? SUBCATEGORY_WEIGHT : 0

    const totalScore = (keywordScore * KEYWORD_WEIGHT) + claimTypeBoost + audienceBoost + subcategoryBoost
    scores.push({ idx: j, score: totalScore })
  }

  scores.sort((a, b) => b.score - a.score)

  // Diversify: avoid showing 4 articles from the exact same subcategory
  const selected: number[] = []
  const subcategoryCounts: Record<string, number> = {}
  for (const s of scores) {
    if (selected.length >= 4) break
    const sub = articles[s.idx].subcategory || '_none'
    const currentSubCount = subcategoryCounts[sub] || 0
    if (currentSubCount >= 2) continue
    selected.push(s.idx)
    subcategoryCounts[sub] = currentSubCount + 1
  }

  relatedMap[article.slug] = selected.map(idx => articles[idx].slug)
}

if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true })
}

const outputPath = path.join(DATA_DIR, 'related-articles.json')
fs.writeFileSync(outputPath, JSON.stringify(relatedMap, null, 0))
console.log(`Generated related articles map for ${Object.keys(relatedMap).length} articles`)
console.log(`Written to: ${outputPath}`)
